/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"

#include "Entities/StdH/StdH.h"
#define BLOOD_SPILL_RED RGBAToColor(250,20,20,255)
#define BLOOD_SPILL_GREEN RGBAToColor(0,250,0,255)

#include <Entities/Bullet.h>
#include <Entities/Bullet_tables.h>
CEntityEvent *EBulletInit::MakeCopy(void) { CEntityEvent *peeCopy = new EBulletInit(*this); return peeCopy;}
EBulletInit::EBulletInit() : CEntityEvent(EVENTCODE_EBulletInit) {;
 ClearToDefault(penOwner);
 ClearToDefault(fDamage);
};
#line 45 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"

void CBullet_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) 
{
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINSTONE);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINSAND);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINREDSAND);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINWATER);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINSTONENOSOUND);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINSANDNOSOUND);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINREDSANDNOSOUND);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETSTAINWATERNOSOUND);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BLOODSPILL);
  pdec->PrecacheClass(CLASS_BASIC_EFFECT, BET_BULLETTRAIL);
}

void CBullet::SetDefaultProperties(void) {
  m_penOwner = NULL;
  m_fDamage = 0.0f;
  m_vTarget = FLOAT3D(0 , 0 , 0);
  m_vTargetCopy = FLOAT3D(0 , 0 , 0);
  m_vHitPoint = FLOAT3D(0 , 0 , 0);
  m_iBullet = 0;
  m_EdtDamage = DMT_BULLET ;
  m_fBulletSize = 0.0f;
  CEntity::SetDefaultProperties();
}
  
#line 85 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::SetDamage(FLOAT fDamage) {
#line 86 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_fDamage  = fDamage ;
#line 87 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 90 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::CalcTarget(FLOAT fRange) {
#line 92 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
AnglesToDirectionVector  (GetPlacement  () . pl_OrientationAngle  , m_vTarget );
#line 93 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTarget  *= fRange ;
#line 94 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTarget  += GetPlacement  () . pl_PositionVector ;
#line 95 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTargetCopy  = m_vTarget ;
#line 96 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 98 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::CalcTarget(CEntity * pen,FLOAT fRange) {
#line 99 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vTarget ;
#line 102 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
EntityInfo  * peiTarget  = (EntityInfo  *) (pen  -> GetEntityInfo  ());
#line 103 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
GetEntityInfoPosition  (pen  , peiTarget  -> vTargetCenter  , vTarget );
#line 106 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTarget  = (vTarget  - GetPlacement  () . pl_PositionVector ) . Normalize  ();
#line 107 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTarget  *= fRange ;
#line 108 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTarget  += GetPlacement  () . pl_PositionVector ;
#line 109 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTargetCopy  = m_vTarget ;
#line 110 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 113 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::CalcJitterTarget(FLOAT fR) {
#line 114 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vJitter ;
#line 125 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fZ  = FRnd  () * 2.0f - 1.0f;
#line 126 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fA  = FRnd  () * 360.0f;
#line 127 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fT  = Sqrt  (1 - (fZ  * fZ ));
#line 128 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vJitter  (1) = fT  * CosFast  (fA );
#line 129 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vJitter  (2) = fT  * SinFast  (fA );
#line 130 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vJitter  (3) = fZ ;
#line 131 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vJitter  = vJitter  * fR  * FRnd  ();
#line 134 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTarget  = m_vTargetCopy  + vJitter ;
#line 135 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 138 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::CalcJitterTargetFixed(FLOAT fX,FLOAT fY,FLOAT fJitter) {
#line 139 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fRndX  = FRnd  () * 2.0f - 1.0f;
#line 140 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fRndY  = FRnd  () * 2.0f - 1.0f;
#line 141 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vX  , vY ;
#line 142 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
const FLOATmatrix3D & m  = GetRotationMatrix  ();
#line 143 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vX  (1) = m  (1 , 1);vX  (2) = m  (2 , 1);vX  (3) = m  (3 , 1);
#line 144 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vY  (1) = m  (1 , 2);vY  (2) = m  (2 , 2);vY  (3) = m  (3 , 2);
#line 146 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vTarget  = m_vTargetCopy  + (vX  * (fX  + fRndX  * fJitter )) + (vY  * (fY  + fRndY  * fJitter ));
#line 147 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 150 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::LaunchBullet(BOOL bSound,BOOL bTrail,BOOL bHitFX) 
#line 151 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 153 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
CCastRay  crRay  (m_penOwner  , GetPlacement  () . pl_PositionVector  , m_vTarget );
#line 154 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
crRay  . cr_bHitPortals  = TRUE ;
#line 155 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
crRay  . cr_bHitTranslucentPortals  = TRUE ;
#line 156 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_COLLISIONBOX ;
#line 157 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
crRay  . cr_bPhysical  = FALSE ;
#line 158 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
crRay  . cr_fTestR  = m_fBulletSize ;
#line 159 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vHitDirection ;
#line 160 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
AnglesToDirectionVector  (GetPlacement  () . pl_OrientationAngle  , vHitDirection );
#line 162 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
INDEX ctCasts  = 0;
#line 163 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
while(ctCasts  < 10)
#line 164 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 165 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(ctCasts  == 0)
#line 166 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 168 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
GetWorld  () -> CastRay  (crRay );
#line 169 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 170 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
else 
#line 171 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 173 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
GetWorld  () -> ContinueCast  (crRay );
#line 174 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 175 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ctCasts  ++;
#line 178 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(crRay  . cr_penHit  == NULL )
#line 179 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 180 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
break ;
#line 181 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 183 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
InflictDirectDamage  (crRay  . cr_penHit  , m_penOwner  , m_EdtDamage  , m_fDamage  , 
#line 184 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
crRay  . cr_vHit  , vHitDirection );
#line 186 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_vHitPoint  = crRay  . cr_vHit ;
#line 189 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(crRay  . cr_penHit  -> GetRenderType  () == RT_BRUSH  && crRay  . cr_pbpoBrushPolygon  != NULL )
#line 190 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 191 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
CBrushPolygon  * pbpo  = crRay  . cr_pbpoBrushPolygon ;
#line 192 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vHitNormal  = FLOAT3D (pbpo  -> bpo_pbplPlane  -> bpl_plAbsolute );
#line 194 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
INDEX iSurfaceType  = pbpo  -> bpo_bppProperties  . bpp_ubSurfaceType ;
#line 195 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
BulletHitType  bhtType  = BHT_BRUSH_STONE ;
#line 197 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
INDEX iContent  = pbpo  -> bpo_pbscSector  -> GetContentType  ();
#line 198 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
CContentType  & ct  = GetWorld  () -> wo_actContentTypes  [ iContent  ];
#line 200 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(ct  . ct_ulFlags  & CTF_BREATHABLE_GILLS )
#line 201 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 203 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(iSurfaceType  == SURFACE_WATER )
#line 204 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 205 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vHitNormal  = - vHitNormal ;
#line 206 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
bhtType  = BHT_BRUSH_WATER ;
#line 207 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 209 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
else 
#line 210 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 211 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
bhtType  = BHT_BRUSH_UNDER_WATER ;
#line 212 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 213 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 214 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
else 
#line 215 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 216 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(iSurfaceType  == SURFACE_SAND ){bhtType  = BHT_BRUSH_SAND ;}
#line 217 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(iSurfaceType  == SURFACE_RED_SAND ){bhtType  = BHT_BRUSH_RED_SAND ;}
#line 218 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(iSurfaceType  == SURFACE_WATER ){bhtType  = BHT_BRUSH_WATER ;}
#line 219 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 221 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
BOOL bPassable  = pbpo  -> bpo_ulFlags  & (BPOF_PASSABLE  | BPOF_SHOOTTHRU );
#line 222 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(! bPassable  || iSurfaceType  == SURFACE_WATER ){
#line 223 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SpawnHitTypeEffect  (bhtType  , bSound  , vHitNormal  , crRay  . cr_vHit  , vHitDirection  , FLOAT3D (0.0f , 0.0f , 0.0f));
#line 224 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 225 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(! bPassable ){
#line 226 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
break ;
#line 227 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 229 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}else {
#line 232 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(crRay  . cr_penHit  -> GetEntityInfo  () != NULL ){
#line 233 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(((EntityInfo  *) crRay  . cr_penHit  -> GetEntityInfo  ()) -> Eeibt  == EIBT_FLESH )
#line 234 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 235 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
CEntity  * penOfFlesh  = crRay  . cr_penHit ;
#line 236 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vHitNormal  = (GetPlacement  () . pl_PositionVector  - m_vTarget ) . Normalize  ();
#line 237 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vOldHitPos  = crRay  . cr_vHit ;
#line 238 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vDistance ;
#line 241 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
GetWorld  () -> ContinueCast  (crRay );
#line 242 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(crRay  . cr_penHit  != NULL  && crRay  . cr_pbpoBrushPolygon  != NULL  && 
#line 243 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
crRay  . cr_penHit  -> GetRenderType  () == RT_BRUSH )
#line 244 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 245 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vDistance  = crRay  . cr_vHit  - vOldHitPos ;
#line 246 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vHitNormal  = FLOAT3D (crRay  . cr_pbpoBrushPolygon  -> bpo_pbplPlane  -> bpl_plAbsolute );
#line 247 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 248 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
else 
#line 249 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 250 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vDistance  = FLOAT3D (0.0f , 0.0f , 0.0f);
#line 251 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vHitNormal  = FLOAT3D (0 , 0 , 0);
#line 252 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 254 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(IsOfClass  (penOfFlesh  , "Gizmo") || 
#line 255 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
IsOfClass  (penOfFlesh  , "Beast"))
#line 256 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 258 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SpawnHitTypeEffect  (BHT_ACID  , bSound  , vHitNormal  , crRay  . cr_vHit  , vHitDirection  , vDistance );
#line 259 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 260 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
else 
#line 261 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 263 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SpawnHitTypeEffect  (BHT_FLESH  , bSound  , vHitNormal  , crRay  . cr_vHit  , vHitDirection  , vDistance );
#line 264 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 265 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
break ;
#line 266 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 267 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 270 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
break ;
#line 271 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 272 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 276 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(crRay  . cr_penHit  == NULL  && m_vHitPoint  == FLOAT3D (0.0F , 0.0F , 0.0F)){
#line 277 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
bTrail  = FALSE ;
#line 278 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 280 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bTrail )
#line 281 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 282 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SpawnTrail  ();
#line 283 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 284 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 287 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::DestroyBullet(void) {
#line 288 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
Destroy  ();
#line 289 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 297 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::SpawnHitTypeEffect(enum BulletHitType bhtType,BOOL bSound,FLOAT3D vHitNormal,FLOAT3D vHitPoint,
#line 298 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vDirection,FLOAT3D vDistance) 
#line 299 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 300 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
switch(bhtType )
#line 301 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 302 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
case BHT_BRUSH_STONE : 
#line 303 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
case BHT_BRUSH_SAND : 
#line 304 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
case BHT_BRUSH_RED_SAND : 
#line 305 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
case BHT_BRUSH_WATER : 
#line 306 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
case BHT_BRUSH_UNDER_WATER : 
#line 307 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 309 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ESpawnEffect  ese ;
#line 310 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bSound )
#line 311 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 312 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_STONE ){ese  . betType  = BET_BULLETSTAINSTONE ;};
#line 313 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_SAND ){ese  . betType  = BET_BULLETSTAINSAND ;};
#line 314 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_RED_SAND ){ese  . betType  = BET_BULLETSTAINREDSAND ;};
#line 315 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_WATER ){ese  . betType  = BET_BULLETSTAINWATER ;};
#line 316 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_UNDER_WATER ){ese  . betType  = BET_BULLETSTAINUNDERWATER ;};
#line 317 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 318 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
else 
#line 319 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 320 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_STONE ){ese  . betType  = BET_BULLETSTAINSTONENOSOUND ;};
#line 321 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_SAND ){ese  . betType  = BET_BULLETSTAINSANDNOSOUND ;};
#line 322 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_RED_SAND ){ese  . betType  = BET_BULLETSTAINREDSANDNOSOUND ;};
#line 323 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_WATER ){ese  . betType  = BET_BULLETSTAINWATERNOSOUND ;};
#line 324 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_BRUSH_UNDER_WATER ){ese  . betType  = BET_BULLETSTAINUNDERWATERNOSOUND ;};
#line 325 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 327 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . vNormal  = vHitNormal ;
#line 328 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 329 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vDirection  = (vHitPoint  - GetPlacement  () . pl_PositionVector ) . Normalize  ();
#line 331 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fNx  = vHitNormal  (1);
#line 332 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fNy  = vHitNormal  (2);
#line 333 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fNz  = vHitNormal  (3);
#line 334 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fNV  = fNx  * vDirection  (1) + fNy  * vDirection  (2) + fNz  * vDirection  (3);
#line 335 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fRVx  = vDirection  (1) - 2 * fNx  * fNV ;
#line 336 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fRVy  = vDirection  (2) - 2 * fNy  * fNV ;
#line 337 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fRVz  = vDirection  (3) - 2 * fNz  * fNV ;
#line 338 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . vStretch  = FLOAT3D (fRVx  , fRVy  , fRVz );
#line 339 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SpawnEffect  (vHitPoint  , ese );
#line 340 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
break ;
#line 341 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 342 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
case BHT_FLESH : 
#line 343 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
case BHT_ACID : 
#line 344 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 346 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ESpawnEffect  ese ;
#line 347 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 349 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fDistance  = vDistance  . Length  ();
#line 350 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(fDistance  > 0.01f && ! (IRnd  () % 2))
#line 351 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 353 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . betType  = BET_BLOODSPILL ;
#line 354 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(bhtType  == BHT_ACID )
#line 355 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 356 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . colMuliplier  = BLOOD_SPILL_GREEN ;
#line 357 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 358 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
else 
#line 359 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 360 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . colMuliplier  = BLOOD_SPILL_RED ;
#line 361 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 362 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . vNormal  = vHitNormal ;
#line 363 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(fDistance  < 25.0f)
#line 364 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 365 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
GetNormalComponent  (vDistance  / fDistance  , vHitNormal  , ese  . vDirection );
#line 366 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fLength  = ese  . vDirection  . Length  ();
#line 367 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
fLength  = Clamp  (fLength  * 3 , 1.0f , 3.0f);
#line 368 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
fDistance  = Clamp  (log10f  (fDistance ) , 0.5f , 2.0f);
#line 369 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . vStretch  = FLOAT3D (fDistance  , fLength  * fDistance  , 1.0f);
#line 370 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SpawnEffect  (vHitPoint  , ese );
#line 371 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 372 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 373 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
break ;
#line 374 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 375 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 376 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 378 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::SpawnTrail(void) 
#line 379 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 381 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
const FLOAT3D & v0  = GetPlacement  () . pl_PositionVector ;
#line 382 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
const FLOAT3D & v1  = m_vHitPoint ;
#line 384 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vD  = v1  - v0 ;
#line 385 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fD  = vD  . Length  ();
#line 387 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(fD  < 1.0f){
#line 389 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
return ;
#line 390 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 393 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT fLen  = Min  (20.0f , fD );
#line 395 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vPos ;
#line 396 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
if(fLen  < fD ){
#line 397 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vPos  = Lerp  (v0  , v1  , FRnd  () * (fD  - fLen ) / fD );
#line 398 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}else {
#line 399 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vPos  = v0 ;
#line 400 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
#line 402 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ESpawnEffect  ese ;
#line 403 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
UBYTE  ubRndH  = UBYTE  (8 + FRnd  () * 32);
#line 404 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
UBYTE  ubRndS  = UBYTE  (8 + FRnd  () * 32);
#line 405 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
UBYTE  ubRndV  = UBYTE  (224 + FRnd  () * 32);
#line 406 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
UBYTE  ubRndA  = UBYTE  (32 + FRnd  () * 128);
#line 407 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . colMuliplier  = HSVToColor  (ubRndH  , ubRndS  , ubRndV ) | ubRndA ;
#line 408 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . betType  = BET_BULLETTRAIL ;
#line 409 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . vNormal  = vD  / fD ;
#line 410 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ese  . vStretch  = FLOAT3D (0.1f , fLen  , 1.0f);
#line 411 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SpawnEffect  (vPos  , ese );
#line 412 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
  
#line 415 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
void CBullet::SpawnEffect(const FLOAT3D & vHit,const ESpawnEffect & eSpawnEffect) 
#line 416 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
{
#line 417 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
FLOAT3D vDirection ;
#line 418 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
vDirection  = (m_vTarget  - GetPlacement  () . pl_PositionVector ) . Normalize  ();
#line 419 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
CPlacement3D plHit  = CPlacement3D (vHit  - vDirection  * 0.1f , GetPlacement  () . pl_OrientationAngle );
#line 420 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
CEntityPointer penHit  = CreateEntity  (plHit  , CLASS_BASIC_EFFECT );
#line 421 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
penHit  -> Initialize  (eSpawnEffect );
#line 422 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
}
BOOL CBullet::
#line 426 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBullet_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EBulletInit, "CBullet::Main expects 'EBulletInit' as input!");  const EBulletInit &eInit = (const EBulletInit &)__eeInput;
#line 429 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
ASSERT  (eInit  . penOwner  != NULL );
#line 430 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_penOwner  = eInit  . penOwner ;
#line 431 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_fDamage  = eInit  . fDamage ;
#line 433 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
InitAsVoid  ();
#line 434 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 435 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 438 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
m_iBullet  = 0;
#line 439 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
Return(STATE_CURRENT,EVoid());
#line 439 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Bullet.es"
return TRUE; ASSERT(FALSE); return TRUE;};