/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"

#include "Entities/StdH/StdH.h"

#include <Entities/EnemySpawner.h>
#include <Entities/EnemySpawner_tables.h>
void CEnemySpawner::SetDefaultProperties(void) {
  m_penTarget = NULL;
  m_strDescription = "";
  m_strName = "Enemy spawner";
  m_fInnerCircle = 0.0f;
  m_fOuterCircle = 0.0f;
  m_tmDelay = 0.0f;
  m_tmSingleWait = 0.1f;
  m_tmGroupWait = 0.1f;
  m_ctGroupSize = 1;
  m_ctTotal = 1;
  m_penPatrol = NULL;
  m_estType = EST_SIMPLE ;
  m_bTelefrag = FALSE ;
  m_bSpawnEffect = TRUE ;
  m_bDoubleInSerious = FALSE ;
  m_penSeriousTarget = NULL;
  m_soSpawn.SetOwner(this);
m_soSpawn.Stop_internal();
  m_iInGroup = 0;
  CRationalEntity::SetDefaultProperties();
}
  
#line 68 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
void CEnemySpawner::Precache(void) {
#line 69 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
PrecacheClass  (CLASS_BASIC_EFFECT  , BET_TELEPORT );
#line 70 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
  
#line 72 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
const CTString & CEnemySpawner::GetDescription(void)const {
#line 73 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
((CTString &) m_strDescription ) . PrintF  ("-><none>");
#line 74 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penTarget  != NULL ){
#line 75 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
((CTString &) m_strDescription ) . PrintF  ("->%s" , (const char  *) m_penTarget  -> GetName  ());
#line 76 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penSeriousTarget  != NULL ){
#line 77 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
((CTString &) m_strDescription ) . PrintF  ("->%s, %s" , 
#line 78 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
(const char  *) m_penTarget  -> GetName  () , (const char  *) m_penSeriousTarget  -> GetName  ());
#line 79 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 80 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 81 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
((CTString &) m_strDescription ) = EnemySpawnerType_enum  . NameForValue  (INDEX (m_estType )) 
#line 82 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
+ m_strDescription ;
#line 83 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return m_strDescription ;
#line 84 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
  
#line 87 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
BOOL CEnemySpawner::CheckTemplateValid(CEntity * pen) 
#line 88 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
{
#line 89 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(pen  == NULL  || ! IsDerivedFromClass  (pen  , "Enemy Base")){
#line 90 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return FALSE ;
#line 91 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 92 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_estType  == EST_TELEPORTER ){
#line 93 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return ! (((CEnemyBase  &) * pen ) . m_bTemplate );
#line 94 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}else {
#line 95 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return ((CEnemyBase  &) * pen ) . m_bTemplate ;
#line 96 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 97 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
  
#line 99 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
BOOL CEnemySpawner::IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget) 
#line 100 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
{
#line 101 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(slPropertyOffset  == offsetof  (CEnemySpawner  , m_penTarget ))
#line 102 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
{
#line 103 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return CheckTemplateValid  (penTarget );
#line 104 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 105 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
else if(slPropertyOffset  == offsetof  (CEnemySpawner  , m_penPatrol ))
#line 106 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
{
#line 107 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return (penTarget  != NULL  && IsDerivedFromClass  (penTarget  , "Enemy Marker"));
#line 108 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 109 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
else if(slPropertyOffset  == offsetof  (CEnemySpawner  , m_penSeriousTarget ))
#line 110 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
{
#line 111 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return CheckTemplateValid  (penTarget );
#line 112 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 113 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return CEntity  :: IsTargetValid  (slPropertyOffset  , penTarget );
#line 114 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
  
#line 117 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
BOOL CEnemySpawner::FillEntityStatistics(EntityStats * pes) 
#line 118 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
{
#line 119 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penTarget  == NULL ){return FALSE ;}
#line 120 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_penTarget  -> FillEntityStatistics  (pes );
#line 121 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pes  -> es_ctCount  = m_ctTotal ;
#line 122 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pes  -> es_strName  += " (spawned)";
#line 123 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penSeriousTarget  != NULL ){
#line 124 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pes  -> es_strName  += " (has serious)";
#line 125 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 126 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return TRUE ;
#line 127 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
  
#line 130 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
void CEnemySpawner::SpawnEntity(BOOL bCopy) {
#line 132 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(CheckTemplateValid  (m_penTarget )){
#line 134 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
CEntity  * pen  = NULL ;
#line 135 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(bCopy ){
#line 137 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pen  = GetWorld  () -> CopyEntityInWorld  (* m_penTarget  , 
#line 138 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
CPlacement3D (FLOAT3D (- 32000.0f + FRnd  () * 200.0f , - 32000.0f + FRnd  () * 200.0f , 0) , ANGLE3D (0 , 0 , 0)));
#line 141 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pen  -> End  ();
#line 142 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
CEnemyBase  * peb  = ((CEnemyBase  *) pen );
#line 143 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
peb  -> m_bTemplate  = FALSE ;
#line 144 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_estType  == EST_RESPAWNER  || m_estType  == EST_RESPAWNERBYONE ){
#line 145 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
peb  -> m_penSpawnerTarget  = this ;
#line 146 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 147 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penPatrol  != NULL ){
#line 148 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
peb  -> m_penMarker  = m_penPatrol ;
#line 149 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 150 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pen  -> Initialize  ();
#line 151 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}else {
#line 152 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pen  = m_penTarget ;
#line 153 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_penTarget  = NULL ;
#line 154 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 157 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
FLOAT fEntityR  = 0;
#line 158 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(pen  -> en_pciCollisionInfo  != NULL ){
#line 159 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
fEntityR  = pen  -> en_pciCollisionInfo  -> GetMaxFloorRadius  ();
#line 160 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 161 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
FLOAT fOuterCircle  = ClampDn  (m_fOuterCircle  - fEntityR  , 0.0f);
#line 162 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
FLOAT fInnerCircle  = ClampUp  (m_fInnerCircle  + fEntityR  , fOuterCircle );
#line 164 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
FLOAT fR  = fInnerCircle  + FRnd  () * (fOuterCircle  - fInnerCircle );
#line 165 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
FLOAT fA  = FRnd  () * 360.0f;
#line 166 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
CPlacement3D pl  (FLOAT3D (CosFast  (fA ) * fR  , 0.05f , SinFast  (fA ) * fR ) , ANGLE3D (0 , 0 , 0));
#line 167 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pl  . RelativeToAbsolute  (GetPlacement  ());
#line 170 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pen  -> Teleport  (pl  , m_bTelefrag );
#line 173 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_bSpawnEffect ){
#line 174 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
ESpawnEffect  ese ;
#line 175 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 176 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
ese  . betType  = BET_TELEPORT ;
#line 177 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
ese  . vNormal  = FLOAT3D (0 , 1 , 0);
#line 178 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
FLOATaabbox3D box ;
#line 179 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
pen  -> GetBoundingBox  (box );
#line 180 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
FLOAT fEntitySize  = box  . Size  () . MaxNorm  () * 2;
#line 181 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
ese  . vStretch  = FLOAT3D (fEntitySize  , fEntitySize  , fEntitySize );
#line 182 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
CEntityPointer penEffect  = CreateEntity  (pl  , CLASS_BASIC_EFFECT );
#line 183 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
penEffect  -> Initialize  (ese );
#line 184 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 185 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 186 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
BOOL CEnemySpawner::
#line 191 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SpawnGroup(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_SpawnGroup
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::SpawnGroup expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 194 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_iInGroup  = 0;
#line 196 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Jump(STATE_CURRENT,0x01300003, FALSE, EInternal());return TRUE;}BOOL CEnemySpawner::H0x01300003_SpawnGroup_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300003
if(!(TRUE )){ Jump(STATE_CURRENT,0x01300004, FALSE, EInternal());return TRUE;}
#line 199 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SpawnEntity  (TRUE );
#line 202 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_ctTotal  --;
#line 204 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_ctTotal  <= 0){
#line 206 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Return(STATE_CURRENT,EEnd  ());
#line 206 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return TRUE;
#line 207 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 210 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_iInGroup  ++;
#line 212 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_iInGroup  >= m_ctGroupSize ){
#line 214 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Return(STATE_CURRENT,EReturn  ());
#line 214 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return TRUE;
#line 215 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 218 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(m_tmSingleWait );
Jump(STATE_CURRENT, 0x01300001, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300001_SpawnGroup_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300001
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01300002, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return FALSE;}ASSERT(FALSE);break;
#line 222 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}return TRUE;}BOOL CEnemySpawner::H0x01300002_SpawnGroup_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300002
Jump(STATE_CURRENT,0x01300003, FALSE, EInternal());return TRUE;
#line 223 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}BOOL CEnemySpawner::H0x01300004_SpawnGroup_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300004
 ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 227 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Simple(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_Simple
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::Simple expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 230 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01300006, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300006_Simple_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300006
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):{const ETrigger&e= (ETrigger&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01300007, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01300007, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return FALSE;}ASSERT(FALSE);break;
#line 235 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}return TRUE;}BOOL CEnemySpawner::H0x01300007_Simple_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300007

#line 238 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(!(m_tmDelay  > 0)){ Jump(STATE_CURRENT,0x0130000a, FALSE, EInternal());return TRUE;}
#line 240 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(m_tmDelay );
Jump(STATE_CURRENT, 0x01300008, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300008_Simple_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01300009, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x01300009_Simple_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300009
;Jump(STATE_CURRENT,0x0130000a, FALSE, EInternal());return TRUE;}BOOL CEnemySpawner::H0x0130000a_Simple_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130000a

#line 244 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Jump(STATE_CURRENT,0x0130000f, FALSE, EInternal());return TRUE;}BOOL CEnemySpawner::H0x0130000f_Simple_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130000f
if(!(TRUE )){ Jump(STATE_CURRENT,0x01300010, FALSE, EInternal());return TRUE;}
#line 246 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
STATE_CEnemySpawner_SpawnGroup, TRUE;
Jump(STATE_CURRENT, 0x0130000b, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x0130000b_Simple_06(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130000b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemySpawner_SpawnGroup, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0130000c, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x0130000c_Simple_07(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130000c
const EReturn&__e= (EReturn&)__eeInput;
;
#line 248 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(m_tmGroupWait );
Jump(STATE_CURRENT, 0x0130000d, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x0130000d_Simple_08(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130000d
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0130000e, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x0130000e_Simple_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130000e
;Jump(STATE_CURRENT,0x0130000f, FALSE, EInternal());return TRUE;
#line 249 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}BOOL CEnemySpawner::H0x01300010_Simple_11(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300010
 ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 253 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Teleporter(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_Teleporter
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::Teleporter expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 256 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01300012, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300012_Teleporter_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300012
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):{const ETrigger&e= (ETrigger&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01300013, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01300013, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return FALSE;}ASSERT(FALSE);break;
#line 261 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}return TRUE;}BOOL CEnemySpawner::H0x01300013_Teleporter_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300013

#line 264 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(!(m_tmDelay  > 0)){ Jump(STATE_CURRENT,0x01300016, FALSE, EInternal());return TRUE;}
#line 266 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(m_tmDelay );
Jump(STATE_CURRENT, 0x01300014, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300014_Teleporter_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300014
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01300015, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x01300015_Teleporter_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300015
;Jump(STATE_CURRENT,0x01300016, FALSE, EInternal());return TRUE;}BOOL CEnemySpawner::H0x01300016_Teleporter_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300016

#line 270 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SpawnEntity  (FALSE );
#line 273 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Return(STATE_CURRENT,EEnd  ());
#line 273 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 277 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Respawner(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_Respawner
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::Respawner expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 280 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Jump(STATE_CURRENT,0x01300021, FALSE, EInternal());return TRUE;}BOOL CEnemySpawner::H0x01300021_Respawner_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300021
if(!(TRUE )){ Jump(STATE_CURRENT,0x01300022, FALSE, EInternal());return TRUE;}
#line 282 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01300018, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300018_Respawner_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300018
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):{const ETrigger&e= (ETrigger&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01300019, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01300019, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return FALSE;}ASSERT(FALSE);break;
#line 287 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}return TRUE;}BOOL CEnemySpawner::H0x01300019_Respawner_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300019

#line 289 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(!(m_tmDelay  > 0)){ Jump(STATE_CURRENT,0x0130001c, FALSE, EInternal());return TRUE;}
#line 291 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(m_tmDelay );
Jump(STATE_CURRENT, 0x0130001a, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x0130001a_Respawner_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130001a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0130001b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x0130001b_Respawner_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130001b
;Jump(STATE_CURRENT,0x0130001c, FALSE, EInternal());return TRUE;}BOOL CEnemySpawner::H0x0130001c_Respawner_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130001c

#line 295 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
STATE_CEnemySpawner_SpawnGroup, TRUE;
Jump(STATE_CURRENT, 0x0130001d, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x0130001d_Respawner_06(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130001d
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemySpawner_SpawnGroup, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0130001e, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x0130001e_Respawner_07(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130001e
const EReturn&__e= (EReturn&)__eeInput;
;
#line 297 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_estType  == EST_RESPAWNERBYONE ){
#line 299 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_ctGroupSize  = 1;
#line 300 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 302 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x0130001f, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x0130001f_Respawner_08(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130001f
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01300020, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x01300020_Respawner_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300020
;Jump(STATE_CURRENT,0x01300021, FALSE, EInternal());return TRUE;
#line 303 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}BOOL CEnemySpawner::H0x01300022_Respawner_11(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300022
 ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 306 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
DestroyableInactive(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_DestroyableInactive
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::DestroyableInactive expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 308 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01300024, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300024_DestroyableInactive_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300024
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_EActivate: Jump(STATE_CURRENT,0x01300025, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x01300025_DestroyableInactive_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300025
const EActivate&__e= (EActivate&)__eeInput;
;
#line 309 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Jump(STATE_CURRENT, STATE_CEnemySpawner_DestroyableActive, TRUE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 312 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
DestroyableActiveSpawning(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_DestroyableActiveSpawning
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::DestroyableActiveSpawning expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 315 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Jump(STATE_CURRENT,0x0130002b, FALSE, EInternal());return TRUE;}BOOL CEnemySpawner::H0x0130002b_DestroyableActiveSpawning_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130002b
if(!(TRUE )){ Jump(STATE_CURRENT,0x0130002c, FALSE, EInternal());return TRUE;}
#line 317 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
STATE_CEnemySpawner_SpawnGroup, TRUE;
Jump(STATE_CURRENT, 0x01300027, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300027_DestroyableActiveSpawning_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300027
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemySpawner_SpawnGroup, TRUE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01300028, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x01300028_DestroyableActiveSpawning_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300028
const EReturn&__e= (EReturn&)__eeInput;
;
#line 319 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(m_tmGroupWait );
Jump(STATE_CURRENT, 0x01300029, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300029_DestroyableActiveSpawning_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300029
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0130002a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x0130002a_DestroyableActiveSpawning_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130002a
;Jump(STATE_CURRENT,0x0130002b, FALSE, EInternal());return TRUE;
#line 320 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}BOOL CEnemySpawner::H0x0130002c_DestroyableActiveSpawning_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130002c
 ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 322 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
DestroyableActive(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_DestroyableActive
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::DestroyableActive expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 324 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
STATE_CEnemySpawner_DestroyableActiveSpawning, TRUE;
Jump(STATE_CURRENT, 0x0130002e, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x0130002e_DestroyableActive_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130002e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemySpawner_DestroyableActiveSpawning, TRUE, EVoid());return TRUE;case EVENTCODE_EDeactivate: Jump(STATE_CURRENT,0x0130002f, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x0130002f_DestroyableActive_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0130002f
const EDeactivate&__e= (EDeactivate&)__eeInput;
;
#line 325 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Jump(STATE_CURRENT, STATE_CEnemySpawner_DestroyableInactive, TRUE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 329 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Destroyable(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_Destroyable
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::Destroyable expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 332 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
STATE_CEnemySpawner_DestroyableInactive, TRUE;
Jump(STATE_CURRENT, 0x01300031, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300031_Destroyable_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300031
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemySpawner_DestroyableInactive, TRUE, EVoid());return TRUE;case EVENTCODE_EStop: Jump(STATE_CURRENT,0x01300032, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x01300032_Destroyable_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300032
const EStop&__e= (EStop&)__eeInput;
;
#line 334 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Return(STATE_CURRENT,EEnd  ());
#line 334 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CEnemySpawner::
#line 337 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEnemySpawner_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEnemySpawner::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 339 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
InitAsEditorModel  ();
#line 340 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 341 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 344 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetModel  (MODEL_ENEMYSPAWNER );
#line 345 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetModelMainTexture  (TEXTURE_ENEMYSPAWNER );
#line 348 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_fInnerCircle  > m_fOuterCircle ){
#line 349 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_fInnerCircle  = m_fOuterCircle ;
#line 350 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 353 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penTarget  != NULL ){
#line 354 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(! IsDerivedFromClass  (m_penTarget  , "Enemy Base")){
#line 355 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
WarningMessage  ("Target '%s' is of wrong class!" , (const char  *) m_penTarget  -> GetName  ());
#line 356 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_penTarget  = NULL ;
#line 357 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 358 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 359 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penSeriousTarget  != NULL ){
#line 360 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(! IsDerivedFromClass  (m_penSeriousTarget  , "Enemy Base")){
#line 361 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
WarningMessage  ("Target '%s' is of wrong class!" , (const char  *) m_penSeriousTarget  -> GetName  ());
#line 362 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_penSeriousTarget  = NULL ;
#line 363 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 364 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 367 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAfter(_pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x01300033, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300033_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300033
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01300034, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEnemySpawner::H0x01300034_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300034
;
#line 369 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_bDoubleInSerious  && GetSP  () -> sp_gdGameDifficulty  == CSessionProperties  :: GD_EXTREME ){
#line 370 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_ctGroupSize  *= 2;
#line 371 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_ctTotal  *= 2;
#line 372 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 373 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_penSeriousTarget  != NULL  && GetSP  () -> sp_gdGameDifficulty  == CSessionProperties  :: GD_EXTREME ){
#line 374 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
m_penTarget  = m_penSeriousTarget ;
#line 375 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 377 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01300035, FALSE, EBegin());return TRUE;}BOOL CEnemySpawner::H0x01300035_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300035
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;

#line 379 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
if(m_estType  == EST_SIMPLE ){
#line 380 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Call(STATE_CURRENT, STATE_CEnemySpawner_Simple, TRUE, EVoid());return TRUE;
#line 381 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}else if(m_estType  == EST_TELEPORTER ){
#line 382 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Call(STATE_CURRENT, STATE_CEnemySpawner_Teleporter, TRUE, EVoid());return TRUE;
#line 383 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}else if(m_estType  == EST_RESPAWNER  || m_estType  == EST_RESPAWNERBYONE  || m_estType  == EST_TRIGGERED ){
#line 384 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Call(STATE_CURRENT, STATE_CEnemySpawner_Respawner, TRUE, EVoid());return TRUE;
#line 385 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}else if(m_estType  == EST_DESTROYABLE ){
#line 386 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Call(STATE_CURRENT, STATE_CEnemySpawner_Destroyable, TRUE, EVoid());return TRUE;
#line 387 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}
#line 388 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeactivate):{const EDeactivate&e= (EDeactivate&)__eeInput;

#line 390 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
UnsetTimer();Jump(STATE_CURRENT,0x01300036, FALSE, EInternal());return TRUE;
#line 391 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):{const EStop&e= (EStop&)__eeInput;

#line 393 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
UnsetTimer();Jump(STATE_CURRENT,0x01300036, FALSE, EInternal());return TRUE;
#line 394 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}ASSERT(FALSE);break;case(EVENTCODE_EEnd):{const EEnd&e= (EEnd&)__eeInput;

#line 396 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
UnsetTimer();Jump(STATE_CURRENT,0x01300036, FALSE, EInternal());return TRUE;
#line 397 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 398 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
}return TRUE;}BOOL CEnemySpawner::H0x01300036_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01300036

#line 400 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Destroy  ();
#line 402 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
Return(STATE_CURRENT,EVoid());
#line 402 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/EnemySpawner.es"
return TRUE; ASSERT(FALSE); return TRUE;};