/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _Entities_HealthItem_INCLUDED
#define _Entities_HealthItem_INCLUDED 1
#include <Entities/Item.h>
extern DECL_DLL CEntityPropertyEnumType HealthItemType_enum;
enum HealthItemType {
  HIT_PILL = 0,
  HIT_SMALL = 1,
  HIT_MEDIUM = 2,
  HIT_LARGE = 3,
  HIT_SUPER = 4,
};
DECL_DLL inline void ClearToDefault(HealthItemType &e) { e = (HealthItemType)0; } ;
#define EVENTCODE_EHealth 0x03210000
class DECL_DLL EHealth : public CEntityEvent {
public:
EHealth();
CEntityEvent *MakeCopy(void);
FLOAT fHealth;
BOOL bOverTopHealth;
};
DECL_DLL inline void ClearToDefault(EHealth &e) { e = EHealth(); } ;
extern "C" DECL_DLL CDLLEntityClass CHealthItem_DLLClass;
class CHealthItem : public CItem {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  enum HealthItemType m_EhitType;
  BOOL m_bOverTopHealth;
  INDEX m_iSoundComponent;
   
#line 89 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/HealthItem.es"
void Precache(void);
   
#line 99 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/HealthItem.es"
BOOL FillEntityStatistics(EntityStats * pes);
   
#line 119 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/HealthItem.es"
void RenderParticles(void);
   
#line 146 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/HealthItem.es"
void SetProperties(void);
   
#line 221 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/HealthItem.es"
void AdjustDifficulty(void);
#define  STATE_CHealthItem_ItemCollected 0x03210001
  BOOL 
#line 228 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/HealthItem.es"
ItemCollected(const CEntityEvent &__eeInput);
#define  STATE_CHealthItem_Main 1
  BOOL 
#line 272 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/HealthItem.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _Entities_HealthItem_INCLUDED
