/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"

#include "Entities/StdH/StdH.h"
#include "Models/Enemies/MAMUTMAN/Mamutman.h"

#include <Entities/Mamutman.h>
#include <Entities/Mamutman_tables.h>
#line 25 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"

// info structure
static EntityInfo eiMamutman = {
  EIBT_FLESH, 60.0f,
  0.0f, 2.0f, 0.0f,
  0.0f, 1.5f, 0.0f,
};

#define FIRE    FLOAT3D(0.0f, 0.8f, 0.0f)

#define FRONT 0
#define MIDDLE 1
#define REAR 2

void CMamutman::SetDefaultProperties(void) {
  m_penBullet = NULL;
  m_bSpawned = FALSE ;
  m_bSpawnedPosition = 0;
  CEnemyBase::SetDefaultProperties();
}
  
#line 66 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void * CMamutman::GetEntityInfo(void) {
#line 67 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
return & eiMamutman ;
#line 68 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 71 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 72 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 73 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
{
#line 75 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
if(! IsOfClass  (penInflictor  , "Mamutman") && ! IsOfClass  (penInflictor  , "Mamut")){
#line 76 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 77 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
#line 78 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 82 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
INDEX CMamutman::AnimForDeath(void) {
#line 83 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
INDEX iAnim ;
#line 84 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
switch(IRnd  () % 2){
#line 85 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
case 0: iAnim  = MAMUTMAN_ANIM_DEATH01 ;break ;
#line 86 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
case 1: iAnim  = MAMUTMAN_ANIM_DEATH02 ;break ;
#line 87 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
default  : iAnim  = MAMUTMAN_ANIM_DEATH01 ;
#line 88 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
#line 89 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (iAnim  , 0);
#line 90 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
return iAnim ;
#line 91 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 93 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::DeathNotify(void) {
#line 94 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
ChangeCollisionBoxIndexWhenPossible  (MAMUTMAN_COLLISION_BOX_DEATH );
#line 95 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
en_fDensity  = 500.0f;
#line 96 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 99 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::StandingAnim(void) {
#line 100 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_STAND  , AOF_LOOPING  | AOF_NORESTART );
#line 101 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 102 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::WalkingAnim(void) {
#line 103 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 104 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 105 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::RunningAnim(void) {
#line 106 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_RUN  , AOF_LOOPING  | AOF_NORESTART );
#line 107 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 108 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::RotatingAnim(void) {
#line 109 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 110 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 113 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::IdleSound(void) {
#line 114 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 115 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 116 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::SightSound(void) {
#line 117 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 118 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 119 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::WoundSound(void) {
#line 120 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 121 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 122 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::DeathSound(void) {
#line 123 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 124 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 130 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::PrepareBullet(void) {
#line 132 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
CPlacement3D plBullet ;
#line 133 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
plBullet  . pl_OrientationAngle  = ANGLE3D (0 , 0 , 0);
#line 134 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
plBullet  . pl_PositionVector  = FIRE ;
#line 135 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
plBullet  . RelativeToAbsolute  (GetPlacement  ());
#line 137 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_penBullet  = CreateEntity  (plBullet  , CLASS_BULLET );
#line 139 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
EBulletInit  eInit ;
#line 140 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
eInit  . penOwner  = this ;
#line 141 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
eInit  . fDamage  = 1.0f;
#line 142 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_penBullet  -> Initialize  (eInit );
#line 143 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
((CBullet  &) * m_penBullet ) . CalcTarget  (m_penEnemy  , 100);
#line 144 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
  
#line 147 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
void CMamutman::FireBullet(void) {
#line 148 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
((CBullet  &) * m_penBullet ) . LaunchBullet  (TRUE  , TRUE  , TRUE );
#line 149 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
((CBullet  &) * m_penBullet ) . DestroyBullet  ();
#line 150 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
BOOL CMamutman::
#line 158 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
FallOnFloor(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CMamutman_FallOnFloor
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CMamutman::FallOnFloor expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 160 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_bSpawned  = FALSE ;
#line 161 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
switch(m_bSpawnedPosition ){
#line 162 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
case FRONT : 
#line 163 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_FALLFROMMAMUTFIRST  , 0);
#line 164 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
GiveImpulseTranslationRelative  (FLOAT3D (FRnd  () * 4 + 8.0f , FRnd  () + 10.0f , FRnd  () + 2.0f));
#line 165 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
break ;
#line 166 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
case MIDDLE : 
#line 167 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_FALLFROMMAMUTSECOND  , 0);
#line 168 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
GiveImpulseTranslationRelative  (FLOAT3D (- FRnd  () * 4 - 8.0f , FRnd  () + 10.0f , FRnd  () + 2.0f));
#line 169 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
break ;
#line 170 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
case REAR : 
#line 171 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_FALLFROMMAMUTTHIRD  , 0);
#line 172 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
GiveImpulseTranslationRelative  (FLOAT3D (0.0f , FRnd  () + 10.0f , FRnd  () * 2 + 2.0f));
#line 173 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
break ;
#line 174 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
#line 176 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(10.0f);
Jump(STATE_CURRENT, 0x01460001, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x01460001_FallOnFloor_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460001
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETouch):{const ETouch&et= (ETouch&)__eeInput;

#line 180 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
if(et  . penOther  -> GetRenderType  () & RT_BRUSH ){
#line 181 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StopMoving  ();
#line 182 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
UnsetTimer();Jump(STATE_CURRENT,0x01460002, FALSE, EInternal());return TRUE;
#line 183 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
#line 184 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
return TRUE;
#line 185 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;

#line 188 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StopMoving  ();
#line 189 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SendEvent  (EDeath  ());
#line 190 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE;
#line 191 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01460002, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 193 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}return TRUE;}BOOL CMamutman::H0x01460002_FallOnFloor_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460002

#line 196 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StopMoving  ();
#line 197 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_GETUP01  , 0);
#line 198 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (MAMUTMAN_ANIM_GETUP01 ));
Jump(STATE_CURRENT, 0x01460003, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x01460003_FallOnFloor_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460003
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01460004, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;

#line 203 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StopMoving  ();
#line 204 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SendEvent  (EDeath  ());
#line 205 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE;
#line 206 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 207 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}return TRUE;}BOOL CMamutman::H0x01460004_FallOnFloor_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460004

#line 208 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Return(STATE_CURRENT,EReturn  ());
#line 208 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CMamutman::
#line 217 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
BeWounded(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CMamutman_BeWounded
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EDamage, "CMamutman::BeWounded expects 'EDamage' as input!");  const EDamage &eDamage = (const EDamage &)__eeInput;
#line 219 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StopMoving  ();
#line 221 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
if(!(IRnd  () & 1)){ Jump(STATE_CURRENT,0x01460014, FALSE, EInternal());return TRUE;}
#line 222 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_FALL01  , 0);
#line 223 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (MAMUTMAN_ANIM_FALL01 ));
Jump(STATE_CURRENT, 0x01460006, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x01460006_BeWounded_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460006
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01460007, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x01460007_BeWounded_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460007
;
#line 224 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(0.2f + FRnd  () / 3);
Jump(STATE_CURRENT, 0x01460008, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x01460008_BeWounded_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01460009, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x01460009_BeWounded_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460009
;
#line 225 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_GETUP01  , 0);
#line 226 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (MAMUTMAN_ANIM_GETUP01 ));
Jump(STATE_CURRENT, 0x0146000a, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x0146000a_BeWounded_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0146000a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0146000b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x0146000b_BeWounded_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0146000b
;Jump(STATE_CURRENT,0x01460013, FALSE, EInternal());return TRUE;}BOOL CMamutman::H0x01460014_BeWounded_15(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460014
if(!(TRUE )){ Jump(STATE_CURRENT,0x01460012, FALSE, EInternal());return TRUE;}
#line 229 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_FALL02  , 0);
#line 230 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (MAMUTMAN_ANIM_FALL02 ));
Jump(STATE_CURRENT, 0x0146000c, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x0146000c_BeWounded_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0146000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0146000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x0146000d_BeWounded_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0146000d
;
#line 231 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(0.2f + FRnd  () / 3);
Jump(STATE_CURRENT, 0x0146000e, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x0146000e_BeWounded_09(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0146000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0146000f, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x0146000f_BeWounded_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0146000f
;
#line 232 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_GETUP02  , 0);
#line 233 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (MAMUTMAN_ANIM_GETUP02 ));
Jump(STATE_CURRENT, 0x01460010, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x01460010_BeWounded_11(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460010
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01460011, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x01460011_BeWounded_12(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460011
;Jump(STATE_CURRENT,0x01460012, FALSE, EInternal());return TRUE;}BOOL CMamutman::H0x01460012_BeWounded_13(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460012
Jump(STATE_CURRENT,0x01460013, FALSE, EInternal());return TRUE;}
BOOL CMamutman::H0x01460013_BeWounded_14(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460013

#line 235 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Return(STATE_CURRENT,EReturn  ());
#line 235 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CMamutman::
#line 243 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CMamutman_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CMamutman::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 245 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StandingAnim  ();
#line 246 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
PrepareBullet  ();
#line 247 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fLockOnEnemyTime  = 0.2f + FRnd  () / 8;
#line 248 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
STATE_CEnemyBase_LockOnEnemy, FALSE;
Jump(STATE_CURRENT, 0x01460016, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x01460016_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460016
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_LockOnEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01460017, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x01460017_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460017
const EReturn&__e= (EReturn&)__eeInput;
;
#line 251 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StartModelAnim  (MAMUTMAN_ANIM_ATTACK02  , 0);
#line 252 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 253 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
FireBullet  ();
#line 254 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetTimerAfter(FRnd  () / 3 + 0.6f);
Jump(STATE_CURRENT, 0x01460018, FALSE, EBegin());return TRUE;}BOOL CMamutman::H0x01460018_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460018
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01460019, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CMamutman::H0x01460019_Fire_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01460019
;
#line 256 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Return(STATE_CURRENT,EReturn  ());
#line 256 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CMamutman::
#line 264 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CMamutman_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CMamutman::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 266 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
InitAsModel  ();
#line 267 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 268 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetCollisionFlags  (ECF_MODEL );
#line 269 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 270 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetHealth  (40.0f);
#line 271 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fMaxHealth  = 40.0f;
#line 272 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
en_tmMaxHoldBreath  = 5.0f;
#line 273 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
en_fDensity  = 1000.0f;
#line 276 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetModel  (MODEL_MAMUTMAN );
#line 277 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
SetModelMainTexture  (TEXTURE_MAMUTMAN );
#line 278 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
if(! m_bSpawned ){
#line 279 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
StandingAnim  ();
#line 280 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
}
#line 282 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fWalkSpeed  = FRnd  () + 1.5f;
#line 283 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 25.0f);
#line 284 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fAttackRunSpeed  = FRnd  () * 2.0f + 10.0f;
#line 285 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 286 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fCloseRunSpeed  = FRnd  () * 2.0f + 10.0f;
#line 287 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 289 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fAttackDistance  = 60.0f;
#line 290 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fCloseDistance  = 0.0f;
#line 291 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fStopDistance  = 17.0f;
#line 292 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fAttackFireTime  = 1.0f;
#line 293 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fCloseFireTime  = 1.0f;
#line 294 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fIgnoreRange  = 200.0f;
#line 296 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fBlowUpAmount  = 20.0f;
#line 297 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fBodyParts  = 4;
#line 298 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_fDamageWounded  = 30.0f;
#line 299 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
m_iScore  = 500;
#line 302 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Mamutman.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};