/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#define ENTITYCLASS CModelHolder

CEntityProperty CModelHolder_properties[] = {
 CEntityProperty(CEntityProperty::EPT_FILENAME, NULL, (0x000000cb<<8)+1, _offsetof(CModelHolder, m_fnModel), "Model", 'M', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FILENAME, NULL, (0x000000cb<<8)+2, _offsetof(CModelHolder, m_fnTexture), "Texture", 'T', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000cb<<8)+3, _offsetof(CModelHolder, m_fStretchAll), "StretchAll", 'S', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000cb<<8)+4, _offsetof(CModelHolder, m_fStretchX), "StretchX", 'X', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000cb<<8)+5, _offsetof(CModelHolder, m_fStretchY), "StretchY", 'Y', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x000000cb<<8)+6, _offsetof(CModelHolder, m_fStretchZ), "StretchZ", 'Z', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x000000cb<<8)+7, _offsetof(CModelHolder, m_strName), "Name", 'N', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_STRING, NULL, (0x000000cb<<8)+12, _offsetof(CModelHolder, m_strDescription), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000cb<<8)+8, _offsetof(CModelHolder, m_bColliding), "Colliding", 'C', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANIMATION, NULL, (0x000000cb<<8)+9, _offsetof(CModelHolder, m_iModelAnimation), "Model animation", 'A', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANIMATION, NULL, (0x000000cb<<8)+10, _offsetof(CModelHolder, m_iTextureAnimation), "Texture animation", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000cb<<8)+11, _offsetof(CModelHolder, m_bClusterShadows), "Cluster shadows", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000cb<<8)+13, _offsetof(CModelHolder, m_bBackground), "Background", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000000cb<<8)+14, _offsetof(CModelHolder, m_bCustomShading), "Custom shading", 'H', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANGLE3D, NULL, (0x000000cb<<8)+15, _offsetof(CModelHolder, m_aShadingDirection), "Light direction", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x000000cb<<8)+16, _offsetof(CModelHolder, m_colLight), "Light color", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_COLOR, NULL, (0x000000cb<<8)+17, _offsetof(CModelHolder, m_colAmbient), "Ambient color", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FILENAME, NULL, (0x000000cb<<8)+18, _offsetof(CModelHolder, m_fnmLightAnimation), "Light animation file", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANIMATION, NULL, (0x000000cb<<8)+19, _offsetof(CModelHolder, m_iLightAnimation), "Light animation", 0, 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ANIMOBJECT, NULL, (0x000000cb<<8)+20, _offsetof(CModelHolder, m_aoLightAnimation), "", 0, 0, 0),
};
#define CModelHolder_propertiesct ARRAYCOUNT(CModelHolder_properties)

CEntityComponent CModelHolder_components[] = {
  CEntityComponent()
};
#define CModelHolder_componentsct 0


CEventHandlerEntry CModelHolder_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CModelHolder::
#line 186 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/ModelHolder.es"
Main),DEBUGSTRING("CModelHolder::Main")},
};
#define CModelHolder_handlersct ARRAYCOUNT(CModelHolder_handlers)

CEntity *CModelHolder_New(void) { return new CModelHolder; };
void CModelHolder_OnInitClass(void) {};
void CModelHolder_OnEndClass(void) {};
void CModelHolder_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CModelHolder_OnWorldEnd(CWorld *pwo) {};
void CModelHolder_OnWorldInit(CWorld *pwo) {};
void CModelHolder_OnWorldTick(CWorld *pwo) {};
void CModelHolder_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CModelHolder, CEntity, "ModelHolder", "", 0x000000cb);
DECLARE_CTFILENAME(_fnmCModelHolder_tbn, "");
