/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _Entities_Projectile_INCLUDED
#define _Entities_Projectile_INCLUDED 1
#include <Entities/BasicEffects.h>
#include <Entities/Light.h>
extern DECL_DLL CEntityPropertyEnumType ProjectileType_enum;
enum ProjectileType {
  PRT_ROCKET = 0,
  PRT_GRENADE = 1,
  PRT_FLAME = 2,
  PRT_LASER_RAY = 3,
  PRT_WALKER_ROCKET = 4,
  PRT_CATMAN_FIRE = 10,
  PRT_HEADMAN_FIRECRACKER = 11,
  PRT_HEADMAN_ROCKETMAN = 12,
  PRT_HEADMAN_BOMBERMAN = 13,
  PRT_BONEMAN_FIRE = 14,
  PRT_WOMAN_FIRE = 15,
  PRT_DRAGONMAN_FIRE = 16,
  PRT_DRAGONMAN_STRONG_FIRE = 17,
  PRT_STONEMAN_FIRE = 18,
  PRT_STONEMAN_BIG_FIRE = 19,
  PRT_STONEMAN_LARGE_FIRE = 20,
  PRT_LAVAMAN_BIG_BOMB = 21,
  PRT_LAVAMAN_BOMB = 22,
  PRT_LAVAMAN_STONE = 23,
  PRT_ICEMAN_FIRE = 27,
  PRT_ICEMAN_BIG_FIRE = 28,
  PRT_ICEMAN_LARGE_FIRE = 29,
  PRT_HUANMAN_FIRE = 41,
  PRT_FISHMAN_FIRE = 42,
  PRT_MANTAMAN_FIRE = 43,
  PRT_CYBORG_LASER = 44,
  PRT_CYBORG_BOMB = 45,
  PRT_LAVA_COMET = 50,
  PRT_BEAST_PROJECTILE = 51,
  PRT_BEAST_BIG_PROJECTILE = 52,
  PRT_BEAST_DEBRIS = 53,
  PRT_BEAST_BIG_DEBRIS = 54,
  PRT_DEVIL_LASER = 55,
  PRT_DEVIL_ROCKET = 56,
  PRT_DEVIL_GUIDED_PROJECTILE = 57,
};
DECL_DLL inline void ClearToDefault(ProjectileType &e) { e = (ProjectileType)0; } ;
extern DECL_DLL CEntityPropertyEnumType ProjectileMovingType_enum;
enum ProjectileMovingType {
  PMT_FLYING = 0,
  PMT_SLIDING = 1,
  PMT_GUIDED = 2,
};
DECL_DLL inline void ClearToDefault(ProjectileMovingType &e) { e = (ProjectileMovingType)0; } ;
#define EVENTCODE_ELaunchProjectile 0x01f50000
class DECL_DLL ELaunchProjectile : public CEntityEvent {
public:
ELaunchProjectile();
CEntityEvent *MakeCopy(void);
CEntityPointer penLauncher;
enum ProjectileType prtType;
FLOAT fSpeed;
};
DECL_DLL inline void ClearToDefault(ELaunchProjectile &e) { e = ELaunchProjectile(); } ;
extern "C" DECL_DLL CDLLEntityClass CProjectile_DLLClass;
class DECL_DLL  CProjectile : public CMovableModelEntity {
public:
virtual CEntity *GetPredictionPair(void) { return m_penPrediction; };
virtual void SetPredictionPair(CEntity *penPair) { m_penPrediction = penPair; };
   virtual void SetDefaultProperties(void);
  CEntityPointer m_penLauncher;
  enum ProjectileType m_prtType;
  enum ProjectileMovingType m_pmtMove;
  CEntityPointer m_penParticles;
  CEntityPointer m_penTarget;
  FLOAT m_fSpeed;
  FLOAT m_fIgnoreTime;
  FLOAT m_fFlyTime;
  FLOAT m_fStartTime;
  FLOAT m_fDamageAmount;
  FLOAT m_fRangeDamageAmount;
  FLOAT m_fDamageHotSpotRange;
  FLOAT m_fDamageFallOffRange;
  FLOAT m_fSoundRange;
  BOOL m_bExplode;
  BOOL m_bLightSource;
  BOOL m_bCanHitHimself;
  BOOL m_bCanBeDestroyed;
  FLOAT m_fWaitAfterDeath;
  FLOAT m_aRotateSpeed;
  FLOAT m_tmExpandBox;
  FLOAT m_tmInvisibility;
  CSoundObject m_soEffect;
  CEntityPointer m_penPrediction;
CLightSource m_lsLightSource;
   
#line 455 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PreMoving(void);
   
#line 466 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PostMoving(void);
   
#line 481 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void Read_t(CTStream * istr);
   void DumpSync_t(CTStream & strm,INDEX iExtensiveSyncCheck);
   
#line 509 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
CLightSource * GetLightSource(void);
   void Copy(CEntity & enOther,ULONG ulFlags);
   
#line 529 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
BOOL AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient);
   
#line 547 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void SetupLightSource(BOOL bLive);
   
#line 651 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void RenderParticles(void);
   
#line 723 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PlayerRocket(void);
   
#line 761 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void WalkerRocket(void);
   
#line 796 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void WalkerRocketExplosion(void);
   
#line 800 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PlayerRocketExplosion(void);
   
#line 836 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PlayerGrenade(void);
   
#line 869 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PlayerGrenadeExplosion(void);
   
#line 909 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PlayerFlame(void);
   
#line 940 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PlayerLaserRay(void);
   
#line 970 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void PlayerLaserWave(void);
   
#line 993 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void CatmanProjectile(void);
   
#line 1020 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void HeadmanFirecracker(void);
   
#line 1044 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void HeadmanRocketman(void);
   
#line 1074 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void HeadmanBomberman(void);
   
#line 1100 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void HeadmanBombermanExplosion(void);
   
#line 1125 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void CyborgBombExplosion(void);
   
#line 1154 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BonemanProjectile(void);
   
#line 1181 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void WomanProjectile(void);
   
#line 1208 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void DragonmanProjectile(INDEX iType);
   
#line 1244 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void ElementalRock(INDEX iSize,INDEX iType);
   
#line 1302 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void LavaManBomb(void);
   
#line 1363 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void LavamanBombExplosion(void);
   
#line 1435 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void LavamanBombDebrisExplosion(void);
   
#line 1476 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void HuanmanProjectile(void);
   
#line 1505 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastProjectile(void);
   
#line 1539 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastBigProjectile(void);
   
#line 1573 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastDebris(void);
   
#line 1602 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastBigDebris(void);
   
#line 1631 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastDebrisExplosion(void);
   
#line 1653 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastBigDebrisExplosion(void);
   
#line 1675 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastProjectileExplosion(void);
   
#line 1731 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BeastBigProjectileExplosion(void);
   
#line 1788 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void FishmanProjectile(void);
   
#line 1815 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void MantamanProjectile(void);
   
#line 1841 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void DevilLaser(void);
   
#line 1864 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void DevilRocket(void);
   
#line 1896 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void DevilRocketExplosion(void);
   
#line 1934 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void DevilGuidedProjectile(void);
   
#line 1967 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void DevilGuidedProjectileExplosion(void);
   
#line 2024 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void CyborgLaser(void);
   
#line 2046 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void CyborgBomb(void);
   
#line 2078 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void LavaBall(void);
   
#line 2104 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void LavaBallExplosion(void);
   
#line 2124 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void ProjectileTouch(CEntityPointer penHit);
   
#line 2152 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void ProjectileHitted(void);
   
#line 2169 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void SpawnEffect(const CPlacement3D & plEffect,const ESpawnEffect & eSpawnEffect);
   
#line 2179 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
void BounceSound(void);
   
#line 2193 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
ANGLE GetRotationSpeed(ANGLE aWantedAngle,ANGLE aRotateSpeed,FLOAT fWaitFrequency);
#define  STATE_CProjectile_ProjectileFly 0x01f50001
  BOOL 
#line 2221 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
ProjectileFly(const CEntityEvent &__eeInput);
  BOOL H0x01f50002_ProjectileFly_01(const CEntityEvent &__eeInput);
  BOOL H0x01f50003_ProjectileFly_02(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_ProjectileGuidedFly 0x01f50004
  BOOL 
#line 2276 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
ProjectileGuidedFly(const CEntityEvent &__eeInput);
  BOOL H0x01f50005_ProjectileGuidedFly_01(const CEntityEvent &__eeInput);
  BOOL H0x01f50006_ProjectileGuidedFly_02(const CEntityEvent &__eeInput);
  BOOL H0x01f50007_ProjectileGuidedFly_03(const CEntityEvent &__eeInput);
  BOOL H0x01f50008_ProjectileGuidedFly_04(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_ProjectileSlide 0x01f50009
  BOOL 
#line 2372 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
ProjectileSlide(const CEntityEvent &__eeInput);
  BOOL H0x01f5000a_ProjectileSlide_01(const CEntityEvent &__eeInput);
  BOOL H0x01f5000b_ProjectileSlide_02(const CEntityEvent &__eeInput);
#define  STATE_CProjectile_Main 1
  BOOL 
#line 2435 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/Projectile.es"
Main(const CEntityEvent &__eeInput);
  BOOL H0x01f5000c_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x01f5000d_Main_02(const CEntityEvent &__eeInput);
  BOOL H0x01f5000e_Main_03(const CEntityEvent &__eeInput);
  BOOL H0x01f5000f_Main_04(const CEntityEvent &__eeInput);
  BOOL H0x01f50010_Main_05(const CEntityEvent &__eeInput);
  BOOL H0x01f50011_Main_06(const CEntityEvent &__eeInput);
  BOOL H0x01f50012_Main_07(const CEntityEvent &__eeInput);
  BOOL H0x01f50013_Main_08(const CEntityEvent &__eeInput);
  BOOL H0x01f50014_Main_09(const CEntityEvent &__eeInput);
  BOOL H0x01f50015_Main_10(const CEntityEvent &__eeInput);
  BOOL H0x01f50016_Main_11(const CEntityEvent &__eeInput);
  BOOL H0x01f50017_Main_12(const CEntityEvent &__eeInput);
  BOOL H0x01f50018_Main_13(const CEntityEvent &__eeInput);
  BOOL H0x01f50019_Main_14(const CEntityEvent &__eeInput);
};
#endif // _Entities_Projectile_INCLUDED
