/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"

#include "Entities/StdH/StdH.h"

#include <Entities/RobotDriving.h>
#include <Entities/RobotDriving_tables.h>
#line 29 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"

// info structure
static EntityInfo eiRobotDriving = {
  EIBT_ROBOT, 100.0f, // mass[kg]
  0.0f, 1.5f, 0.0f,   // source
  0.0f, 1.5f, 0.0f,   // target
};

#define FIRE_POS  FLOAT3D(0.0f, 1.0f, -1.0f)

void CRobotDriving::SetDefaultProperties(void) {
  m_rdcChar = RDC_R2D2 ;
  m_fSize = 1.0f;
  m_soFire0.SetOwner(this);
m_soFire0.Stop_internal();
  m_soFire1.SetOwner(this);
m_soFire1.Stop_internal();
  CEnemyBase::SetDefaultProperties();
}
  
#line 72 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void * CRobotDriving::GetEntityInfo(void) {
#line 73 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
return & eiRobotDriving ;
#line 74 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 77 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 78 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 79 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
{
#line 81 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
if(! IsOfSameClass  (penInflictor  , this )){
#line 82 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 83 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
#line 84 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 87 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::StandingAnim(void) {
#line 89 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 90 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::WalkingAnim(void) {
#line 92 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 93 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::RunningAnim(void) {
#line 95 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 96 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::RotatingAnim(void) {
#line 98 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 101 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::IdleSound(void) {
#line 102 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 103 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 104 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::SightSound(void) {
#line 105 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 106 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 107 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::WoundSound(void) {
#line 108 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 109 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
  
#line 110 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
void CRobotDriving::DeathSound(void) {
#line 111 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 112 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
BOOL CRobotDriving::
#line 118 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CRobotDriving_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CRobotDriving::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 120 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
if(!(m_rdcChar  == RDC_R2D2 )){ Jump(STATE_CURRENT,0x014d000d, FALSE, EInternal());return TRUE;}
#line 123 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fLockOnEnemyTime  = 0.5f;
#line 124 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
STATE_CEnemyBase_LockOnEnemy, FALSE;
Jump(STATE_CURRENT, 0x014d0001, FALSE, EBegin());return TRUE;}BOOL CRobotDriving::H0x014d0001_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_LockOnEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x014d0002, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CRobotDriving::H0x014d0002_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0002
const EReturn&__e= (EReturn&)__eeInput;
;
#line 126 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
StopMoving  ();
#line 129 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
ShootProjectile  (PRT_CYBORG_LASER  , FIRE_POS  * m_fSize  , ANGLE3D (0 , 0 , 0));
#line 130 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PlaySound  (m_soFire0  , SOUND_FIRE_LASER  , SOF_3D );
#line 131 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetTimerAfter(0.25f);
Jump(STATE_CURRENT, 0x014d0003, FALSE, EBegin());return TRUE;}BOOL CRobotDriving::H0x014d0003_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x014d0004, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CRobotDriving::H0x014d0004_Fire_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0004
;
#line 132 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
ShootProjectile  (PRT_CYBORG_LASER  , FIRE_POS  * m_fSize  , ANGLE3D (0 , 0 , 0));
#line 133 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PlaySound  (m_soFire1  , SOUND_FIRE_LASER  , SOF_3D );
#line 136 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
StandingAnim  ();
#line 137 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetTimerAfter(FRnd  () * 0.1f + 0.1f);
Jump(STATE_CURRENT, 0x014d0005, FALSE, EBegin());return TRUE;}BOOL CRobotDriving::H0x014d0005_Fire_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x014d0006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CRobotDriving::H0x014d0006_Fire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0006
;Jump(STATE_CURRENT,0x014d000c, FALSE, EInternal());return TRUE;}BOOL CRobotDriving::H0x014d000d_Fire_13(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d000d
if(!(TRUE )){ Jump(STATE_CURRENT,0x014d000b, FALSE, EInternal());return TRUE;}
#line 143 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
if(Abs  (en_vGravityDir  % CalcDelta  (m_penEnemy )) > 5.0f){
#line 144 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
Return(STATE_CURRENT,EEnd  ());
#line 144 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
return TRUE;
#line 145 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
#line 147 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fLockOnEnemyTime  = 0.5f;
#line 148 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
STATE_CEnemyBase_LockOnEnemy, FALSE;
Jump(STATE_CURRENT, 0x014d0007, FALSE, EBegin());return TRUE;}BOOL CRobotDriving::H0x014d0007_Fire_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0007
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CEnemyBase_LockOnEnemy, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x014d0008, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CRobotDriving::H0x014d0008_Fire_08(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0008
const EReturn&__e= (EReturn&)__eeInput;
;
#line 152 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
FLOAT fSpeed  = Sqrt  (en_fGravityA  * (CalcDist  (m_penEnemy ) * 1.25f));
#line 154 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
EntityInfo  * peiTarget  = (EntityInfo  *) (m_penEnemy  -> GetEntityInfo  ());
#line 155 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
FLOAT3D vShootTarget ;
#line 156 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
GetEntityInfoPosition  (m_penEnemy  , peiTarget  -> vTargetCenter  , vShootTarget );
#line 158 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
CPlacement3D pl ;
#line 159 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PreparePropelledProjectile  (pl  , vShootTarget  , FLOAT3D (0.0f , 1.5f , - 0.7f) , ANGLE3D (0 , 45.0f , 0));
#line 160 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
CEntityPointer penProjectile  = CreateEntity  (pl  , CLASS_PROJECTILE );
#line 161 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
ELaunchProjectile  eLaunch ;
#line 162 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
eLaunch  . penLauncher  = this ;
#line 163 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
eLaunch  . prtType  = PRT_HEADMAN_BOMBERMAN ;
#line 164 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
eLaunch  . fSpeed  = fSpeed ;
#line 165 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
penProjectile  -> Initialize  (eLaunch );
#line 168 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
PlaySound  (m_soFire0  , SOUND_FIRE_LASER  , SOF_3D );
#line 169 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
StopMoving  ();
#line 171 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
StandingAnim  ();
#line 172 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetTimerAfter(FRnd  () * 0.1f + 0.1f);
Jump(STATE_CURRENT, 0x014d0009, FALSE, EBegin());return TRUE;}BOOL CRobotDriving::H0x014d0009_Fire_09(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d0009
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x014d000a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CRobotDriving::H0x014d000a_Fire_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d000a
;Jump(STATE_CURRENT,0x014d000b, FALSE, EInternal());return TRUE;}BOOL CRobotDriving::H0x014d000b_Fire_11(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d000b
Jump(STATE_CURRENT,0x014d000c, FALSE, EInternal());return TRUE;}
BOOL CRobotDriving::H0x014d000c_Fire_12(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x014d000c

#line 175 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
Return(STATE_CURRENT,EReturn  ());
#line 175 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CRobotDriving::
#line 183 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
Death(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CRobotDriving_Death
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CRobotDriving::Death expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 185 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
StopMoving  ();
#line 186 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
DeathSound  ();
#line 189 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetPhysicsFlags  (EPF_MODEL_CORPSE );
#line 190 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetCollisionFlags  (ECF_CORPSE );
#line 193 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
Return(STATE_CURRENT,EEnd  ());
#line 193 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CRobotDriving::
#line 201 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CRobotDriving_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CRobotDriving::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 203 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
InitAsModel  ();
#line 204 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 205 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetCollisionFlags  (ECF_MODEL );
#line 206 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 208 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetHealth  (20.0f);
#line 209 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fMaxHealth  = 20.0f;
#line 210 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fBlowUpAmount  = 0.0f;
#line 211 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fBodyParts  = 4;
#line 212 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_bRobotBlowup  = TRUE ;
#line 213 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fDamageWounded  = 100000.0f;
#line 215 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
en_fDensity  = 10000.0f;
#line 217 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
switch(m_rdcChar ){
#line 218 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
case RDC_R2D2 : {
#line 220 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fSize  = 1.0f;
#line 221 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetComponents  (this  , * GetModelObject  () , 
#line 222 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
MODEL_R2D2  , TEXTURE_R2D2  , 0 , 0 , 0);
#line 223 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
GetModelObject  () -> StretchModel  (FLOAT3D (1 , 1 , 1));
#line 224 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
ModelChangeNotify  ();
#line 227 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fWalkSpeed  = FRnd  () + 1.5f;
#line 228 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 229 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fAttackRunSpeed  = FRnd  () + 5.0f;
#line 230 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 231 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fCloseRunSpeed  = FRnd  () + 5.0f;
#line 232 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 234 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fAttackDistance  = 50.0f;
#line 235 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fCloseDistance  = 0.0f;
#line 236 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fStopDistance  = 8.0f;
#line 237 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fAttackFireTime  = 2.0f;
#line 238 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fCloseFireTime  = 1.0f;
#line 239 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fIgnoreRange  = 200.0f;
#line 241 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_iScore  = 100;
#line 242 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}break ;
#line 243 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
case RDC_SPIDER : {
#line 245 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fSize  = 1.0f;
#line 246 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
SetComponents  (this  , * GetModelObject  () , 
#line 247 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
MODEL_SPIDER  , TEXTURE_SPIDER  , 0 , 0 , 0);
#line 248 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
GetModelObject  () -> StretchModel  (FLOAT3D (1 , 1 , 1));
#line 249 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
ModelChangeNotify  ();
#line 252 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fWalkSpeed  = FRnd  () + 1.5f;
#line 253 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 254 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fAttackRunSpeed  = FRnd  () + 4.0f;
#line 255 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 256 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fCloseRunSpeed  = FRnd  () + 4.0f;
#line 257 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 259 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fAttackDistance  = 45.0f;
#line 260 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fCloseDistance  = 0.0f;
#line 261 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fStopDistance  = 20.0f;
#line 262 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fAttackFireTime  = 2.0f;
#line 263 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fCloseFireTime  = 1.5f;
#line 264 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_fIgnoreRange  = 150.0f;
#line 266 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_iScore  = 500;
#line 267 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}break ;
#line 268 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
default  : ASSERT  (FALSE );
#line 269 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
}
#line 270 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
StandingAnim  ();
#line 272 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_soFire0  . Set3DParameters  (160.0f , 5.0f , 1.0f , 1.0f);
#line 273 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
m_soFire1  . Set3DParameters  (160.0f , 5.0f , 1.0f , 1.0f);
#line 276 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/RobotDriving.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};