/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 20 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"

#include "Entities/StdH/StdH.h"

#include <Entities/SoundHolder.h>
#include <Entities/SoundHolder_tables.h>
void CSoundHolder::SetDefaultProperties(void) {
  m_fnSound = CTFILENAME("Sounds\\Default.wav");
  m_rFallOffRange = 100.0f;
  m_rHotSpotRange = 50.0f;
  m_fVolume = 1.0f;
  m_bLoop = TRUE ;
  m_bSurround = FALSE ;
  m_bVolumetric = TRUE ;
  m_strName = "";
  m_strDescription = "";
  m_bAutoStart = FALSE ;
  m_iPlayType = 0;
  m_soSound.SetOwner(this);
m_soSound.Stop_internal();
  m_bDestroyable = FALSE ;
  CRationalEntity::SetDefaultProperties();
}
  
#line 61 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
void CSoundHolder::Precache(void) 
#line 62 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
{
#line 63 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_aps  . Precache  (m_fnSound );
#line 64 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}
  
#line 67 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
void CSoundHolder::MirrorAndStretch(FLOAT fStretch,BOOL bMirrorX) 
#line 68 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
{
#line 70 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_rFallOffRange  *= fStretch ;
#line 71 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_rHotSpotRange  *= fStretch ;
#line 73 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}
BOOL CSoundHolder::
#line 78 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSoundHolder_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSoundHolder::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 81 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_rHotSpotRange  < 0.0f){m_rHotSpotRange  = 0.0f;}
#line 82 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_rFallOffRange  < m_rHotSpotRange ){m_rFallOffRange  = m_rHotSpotRange ;}
#line 84 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_fVolume  < FLOAT (SL_VOLUME_MIN )){m_fVolume  = FLOAT (SL_VOLUME_MIN );}
#line 85 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_fVolume  > FLOAT (SL_VOLUME_MAX )){m_fVolume  = FLOAT (SL_VOLUME_MAX );}
#line 88 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_iPlayType  = SOF_3D ;
#line 89 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_bLoop ){m_iPlayType  |= SOF_LOOP ;}
#line 90 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_bSurround ){m_iPlayType  |= SOF_SURROUND ;}
#line 91 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_bVolumetric ){m_iPlayType  |= SOF_VOLUMETRIC ;}
#line 94 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
InitAsEditorModel  ();
#line 95 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 96 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 99 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
const float  SOUND_MINSIZE  = 1.0f;
#line 100 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
FLOAT fFactor  = Log2  (m_rFallOffRange ) * SOUND_MINSIZE ;
#line 101 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(fFactor  < SOUND_MINSIZE ){
#line 102 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
fFactor  = SOUND_MINSIZE ;
#line 103 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}
#line 104 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (fFactor  , fFactor  , fFactor );
#line 107 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
SetModel  (MODEL_MARKER );
#line 108 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 110 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_strDescription  . PrintF  ("%s" , (const char  *) m_fnSound  . FileName  ());
#line 113 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
SetTimerAfter(0.5f);
Jump(STATE_CURRENT, 0x00cc0000, FALSE, EBegin());return TRUE;}BOOL CSoundHolder::H0x00cc0000_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00cc0000
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x00cc0001, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CSoundHolder::H0x00cc0001_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00cc0001
;
#line 115 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00cc0002, FALSE, EBegin());return TRUE;}BOOL CSoundHolder::H0x00cc0002_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00cc0002
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;

#line 118 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_bAutoStart ){
#line 119 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_soSound  . Set3DParameters  (FLOAT (m_rFallOffRange ) , FLOAT (m_rHotSpotRange ) , m_fVolume  , 1.0f);
#line 120 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
PlaySound  (m_soSound  , m_fnSound  , m_iPlayType );
#line 121 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}
#line 122 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
return TRUE;
#line 123 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 126 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_soSound  . Set3DParameters  (FLOAT (m_rFallOffRange ) , FLOAT (m_rHotSpotRange ) , m_fVolume  , 1.0f);
#line 127 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
PlaySound  (m_soSound  , m_fnSound  , m_iPlayType );
#line 128 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
return TRUE;
#line 129 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):{const EStop&e= (EStop&)__eeInput;

#line 132 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_soSound  . Stop  ();
#line 133 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
return TRUE;
#line 134 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_ERangeModelDestruction):{const ERangeModelDestruction&e= (ERangeModelDestruction&)__eeInput;

#line 138 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
if(m_bDestroyable ){
#line 140 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
m_soSound  . Stop  ();
#line 141 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}
#line 142 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
Return(STATE_CURRENT,TRUE );
#line 142 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
return TRUE;
#line 143 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}ASSERT(FALSE);break;case(EVENTCODE_EEnd):{const EEnd&e= (EEnd&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x00cc0003, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 145 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
}return TRUE;}BOOL CSoundHolder::H0x00cc0003_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00cc0003

#line 148 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
Destroy  ();
#line 149 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
Return(STATE_CURRENT,EVoid());
#line 149 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTFE/Sources/Entities/SoundHolder.es"
return TRUE; ASSERT(FALSE); return TRUE;};