/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 18 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"

#include "EntitiesMP/StdH/StdH.h"
#include "Models/Enemies/Beast/Beast.h"
#include "EntitiesMP/WorldSettingsController.h"
#include "EntitiesMP/BackgroundViewer.h"

#include <EntitiesMP/Beast.h>
#include <EntitiesMP/Beast_tables.h>
#line 34 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"

static int _tmLastStandingAnim = 0;
#define BEAST_STRETCH 2.0f
#define BIG_BEAST_STRETCH 12.0f
#define HUGE_BEAST_STRETCH 30.0f

// info structure
static EntityInfo eiBeastHuge = {
  EIBT_FLESH, 10000.0f,
  0.0f, 2.0f*HUGE_BEAST_STRETCH, 0.0f,     // source (eyes)
  0.0f, 1.5f*HUGE_BEAST_STRETCH, 0.0f,     // target (body)
};
static EntityInfo eiBeastNormal = {
  EIBT_FLESH, 1500.0f,
  0.0f, 2.0f*BEAST_STRETCH, 0.0f,     // source (eyes)
  0.0f, 1.5f*BEAST_STRETCH, 0.0f,     // target (body)
};
static EntityInfo eiBeastBig = {
  EIBT_FLESH, 5000.0f,
  0.0f, 2.0f*BIG_BEAST_STRETCH, 0.0f,     // source (eyes)
  0.0f, 1.5f*BIG_BEAST_STRETCH, 0.0f,     // target (body)
};

void CBeast::SetDefaultProperties(void) {
  m_bcType = BT_NORMAL ;
  m_iCounter = 0;
  m_bBeBoss = FALSE ;
  CEnemyBase::SetDefaultProperties();
}
  CTString CBeast::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 90 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 91 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
CTString str ;
#line 92 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
str  . PrintF  (TRANSV  ("A Reptiloid killed %s") , (const char  *) strPlayerName );
#line 93 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return str ;
#line 94 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  const CTFileName & CBeast::GetComputerMessageName(void)const {
#line 96 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
static DECLARE_CTFILENAME  (fnmNormal  , "Data\\Messages\\Enemies\\BeastNormal.txt");
#line 97 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
static DECLARE_CTFILENAME  (fnmBig  , "Data\\Messages\\Enemies\\BeastBig.txt");
#line 98 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
static DECLARE_CTFILENAME  (fnmHuge  , "DataMP\\Messages\\Enemies\\BeastBiggest.txt");
#line 99 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
switch(m_bcType ){
#line 100 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
default  : ASSERT  (FALSE );
#line 101 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
case BT_NORMAL : return fnmNormal ;
#line 102 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
case BT_BIG : return fnmBig ;
#line 103 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
case BT_HUGE : return fnmHuge ;
#line 104 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 105 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 106 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::Precache(void) {
#line 107 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
CEnemyBase  :: Precache  ();
#line 108 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_IDLE );
#line 109 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_SIGHT );
#line 110 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_WOUND );
#line 111 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_ANGER );
#line 112 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_FIRE );
#line 113 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_KICK );
#line 114 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheModel  (MODEL_BEAST );
#line 115 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheTexture  (TEXTURE_BEAST_NORMAL );
#line 116 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheTexture  (TEXTURE_BEAST_BIG );
#line 117 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 118 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_DEATH );
#line 119 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_BEAST_PROJECTILE );
#line 120 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 121 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheSound  (SOUND_DEATHBIG );
#line 122 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_BEAST_BIG_PROJECTILE );
#line 123 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 124 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 127 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void * CBeast::GetEntityInfo(void) {
#line 128 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 129 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return & eiBeastNormal ;
#line 130 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else if(m_bcType  == BT_HUGE ){
#line 131 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return & eiBeastHuge ;
#line 132 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 133 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return & eiBeastBig ;
#line 134 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 135 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 137 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::ShakeItBaby(FLOAT tmShaketime,FLOAT fPower) 
#line 138 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 139 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 140 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(pwsc  != NULL ){
#line 141 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeStarted  = tmShaketime ;
#line 142 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_vShakePos  = GetPlacement  () . pl_PositionVector ;
#line 143 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeFalloff  = 400.0f;
#line 144 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeFade  = 3.0f;
#line 146 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeIntensityZ  = 0.0f;
#line 147 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeFrequencyZ  = 5.0f;
#line 148 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeIntensityY  = 0.1f * fPower ;
#line 149 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeFrequencyY  = 5.0f;
#line 150 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_fShakeIntensityB  = 2.5f * fPower ;
#line 151 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_tmShakeFrequencyB  = 7.2f;
#line 153 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
pwsc  -> m_bShakeFadeIn  = FALSE ;
#line 154 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 155 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 157 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
FLOAT CBeast::GetCrushHealth(void) 
#line 158 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 159 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 160 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return 100.0f;
#line 161 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else if(m_bcType  == BT_HUGE ){
#line 162 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return 200.0f;
#line 163 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 164 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return 0.0f;
#line 165 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 167 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
BOOL CBeast::ForcesCannonballToExplode(void) 
#line 168 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 169 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return TRUE ;
#line 170 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 173 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 174 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 175 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 178 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(dmtType  == DMT_BULLET  && fDamageAmmount  > 100.0f)
#line 179 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 180 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
fDamageAmmount  *= 0.5f;
#line 181 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 184 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG  && dmtType  == DMT_CANNONBALL )
#line 185 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 186 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
fDamageAmmount  *= 0.3333f;
#line 187 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 190 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(! IsOfClass  (penInflictor  , "Beast")){
#line 191 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 192 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 193 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 197 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
INDEX CBeast::AnimForDamage(FLOAT fDamage) {
#line 198 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
INDEX iAnim ;
#line 199 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if((m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ) && GetHealth  () <= m_fMaxHealth  / 2){
#line 200 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_ANGER ;
#line 201 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 202 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_WOUND ;
#line 203 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 204 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (iAnim  , 0);
#line 205 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return iAnim ;
#line 206 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 209 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
INDEX CBeast::AnimForDeath(void) {
#line 210 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
INDEX iAnim ;
#line 211 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ){
#line 212 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_DEATHBIG ;
#line 213 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 214 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
iAnim  = BEAST_ANIM_DEATH ;
#line 215 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 217 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (iAnim  , 0);
#line 218 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return iAnim ;
#line 219 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 221 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
FLOAT CBeast::WaitForDust(FLOAT3D & vStretch) {
#line 222 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(GetModelObject  () -> GetAnim  () == BEAST_ANIM_DEATH )
#line 223 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 224 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
vStretch  = FLOAT3D (1 , 1 , 2) * 2.0f;
#line 225 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return 0.3f;
#line 226 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 227 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return - 1.0f;
#line 228 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 230 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::DeathNotify(void) {
#line 231 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ChangeCollisionBoxIndexWhenPossible  (BEAST_COLLISION_BOX_DEATH );
#line 232 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
en_fDensity  = 500.0f;
#line 233 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 236 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::StandingAnim(void) {
#line 237 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
_tmLastStandingAnim  = (int ) _pTimer  -> CurrentTick  ();
#line 238 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_IDLE  , AOF_LOOPING  | AOF_NORESTART );
#line 239 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 241 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::WalkingAnim(void) {
#line 242 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(_pTimer  -> CurrentTick  () >= _tmLastStandingAnim  - _pTimer  -> TickQuantum  && 
#line 243 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
_pTimer  -> CurrentTick  () <= _tmLastStandingAnim  + _pTimer  -> TickQuantum )
#line 244 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 246 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 248 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ){
#line 249 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_WALKBIG  , AOF_LOOPING  | AOF_NORESTART );
#line 250 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 251 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 252 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 253 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 255 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::RunningAnim(void) {
#line 256 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
WalkingAnim  ();
#line 257 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 258 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::RotatingAnim(void) {
#line 259 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
WalkingAnim  ();
#line 260 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 263 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::IdleSound(void) {
#line 264 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 265 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 266 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::SightSound(void) {
#line 267 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 268 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 269 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::WoundSound(void) {
#line 270 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if((m_bcType  == BT_BIG  || m_bcType  == BT_HUGE ) && GetHealth  () <= m_fMaxHealth  / 2){
#line 271 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_ANGER  , SOF_3D );
#line 272 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 273 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 274 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 275 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 276 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::DeathSound(void) {
#line 277 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 278 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 279 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 280 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_DEATHBIG  , SOF_3D );
#line 281 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 282 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
  
#line 286 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
void CBeast::EnemyPostInit(void) 
#line 287 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 288 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_soSound  . Set3DParameters  (160.0f , 50.0f , 2.0f , 1.0f);
#line 289 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
BOOL CBeast::
#line 295 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Death(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Death
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Death expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 296 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL ){
#line 297 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_Death, FALSE, EVoid());return TRUE;
#line 298 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 301 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StopMoving  ();
#line 302 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
DeathSound  ();
#line 303 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
LeaveStain  (TRUE );
#line 305 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetPhysicsFlags  (EPF_MODEL_CORPSE );
#line 306 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetCollisionFlags  (ECF_CORPSE );
#line 307 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetFlags  (GetFlags  () | ENF_SEETHROUGH );
#line 309 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
RemoveFromFuss  ();
#line 311 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
DeathNotify  ();
#line 313 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
AnimForDeath  ();
#line 314 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.9f);
Jump(STATE_CURRENT, 0x01500001, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500001_Death_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500002_Death_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500002
;
#line 315 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 316 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 2.0f);
#line 317 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 318 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 3.0f);
#line 319 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 320 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(2.3f - 0.9f);
Jump(STATE_CURRENT, 0x01500003, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500003_Death_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500004, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500004_Death_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500004
;
#line 321 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 322 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 5.0f);
#line 323 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 324 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShakeItBaby  (_pTimer  -> CurrentTick  () , 7.0f);
#line 325 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 328 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
CPlacement3D plFX  = GetPlacement  ();
#line 329 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ESpawnEffect  ese ;
#line 330 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 331 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ese  . vStretch  = FLOAT3D (1 , 1 , 2) * 15.0f;
#line 332 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ese  . vNormal  = FLOAT3D (0 , 1 , 0);
#line 333 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ese  . betType  = BET_DUST_FALL ;
#line 334 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
CPlacement3D plSmoke  = plFX ;
#line 335 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
plSmoke  . pl_PositionVector  += FLOAT3D (0 , 0.35f * ese  . vStretch  (2) , 0);
#line 336 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
CEntityPointer penFX  = CreateEntity  (plSmoke  , CLASS_BASIC_EFFECT );
#line 337 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
penFX  -> Initialize  (ese );
#line 339 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (BEAST_ANIM_DEATHBIG ) - 2.3f);
Jump(STATE_CURRENT, 0x01500005, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500005_Death_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500005
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500006, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500006_Death_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500006
;
#line 340 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Return(STATE_CURRENT,EEnd  ());
#line 340 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBeast::
#line 346 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 349 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_WALKTOIDLE  , AOF_SMOOTHCHANGE );
#line 350 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500008, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500008_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500009, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500009_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500009
const EReturn&__e= (EReturn&)__eeInput;
;
#line 352 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(m_bcType  == BT_NORMAL )){ Jump(STATE_CURRENT,0x01500010, FALSE, EInternal());return TRUE;}
#line 354 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACK  , AOF_SMOOTHCHANGE );
#line 355 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x0150000a, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150000a_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x0150000b, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150000b_Fire_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000b
const EReturn&__e= (EReturn&)__eeInput;
;
#line 356 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 357 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.51f);
Jump(STATE_CURRENT, 0x0150000c, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150000c_Fire_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000c
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150000d, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150000d_Fire_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000d
;
#line 359 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_PROJECTILE  , FLOAT3D (0.0f , 1.5f * BEAST_STRETCH  , 0.0f) , 
#line 360 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ANGLE3D (AngleDeg  ((FRnd  () - 0.5f) * 30.0f) , AngleDeg  (FRnd  () * 10.0f) , 0));
#line 361 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.3f);
Jump(STATE_CURRENT, 0x0150000e, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150000e_Fire_07(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000e
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150000f, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150000f_Fire_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150000f
;Jump(STATE_CURRENT,0x01500010, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500010_Fire_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500010

#line 364 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(m_bcType  == BT_BIG )){ Jump(STATE_CURRENT,0x0150001f, FALSE, EInternal());return TRUE;}
#line 366 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () <= m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x01500017, FALSE, EInternal());return TRUE;}
#line 368 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 369 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x01500015, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500015_Fire_14(const CEntityEvent &__eeInput)
#line 370 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500015
if(!(m_iCounter  < 6)){ Jump(STATE_CURRENT,0x01500016, FALSE, EInternal());return TRUE;}
#line 371 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACKFAST  , AOF_SMOOTHCHANGE );
#line 372 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500011, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500011_Fire_10(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500011
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500012, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500012_Fire_11(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500012
const EReturn&__e= (EReturn&)__eeInput;
;
#line 374 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 375 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.34f);
Jump(STATE_CURRENT, 0x01500013, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500013_Fire_12(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500013
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500014, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500014_Fire_13(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500014
;
#line 376 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * BIG_BEAST_STRETCH  , 0.0f) , 
#line 377 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 380 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x01500015, FALSE, EInternal());return TRUE;
#line 381 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x01500016_Fire_15(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500016

#line 382 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 7.0f;Jump(STATE_CURRENT,0x01500017, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500017_Fire_16(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500017

#line 385 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () > m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x0150001e, FALSE, EInternal());return TRUE;}
#line 387 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 388 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x0150001c, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150001c_Fire_21(const CEntityEvent &__eeInput)
#line 389 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001c
if(!(m_iCounter  < 3)){ Jump(STATE_CURRENT,0x0150001d, FALSE, EInternal());return TRUE;}
#line 390 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACK  , AOF_SMOOTHCHANGE );
#line 391 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500018, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500018_Fire_17(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500018
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500019, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500019_Fire_18(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500019
const EReturn&__e= (EReturn&)__eeInput;
;
#line 393 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 394 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.5f);
Jump(STATE_CURRENT, 0x0150001a, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150001a_Fire_19(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150001b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150001b_Fire_20(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001b
;
#line 395 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * BIG_BEAST_STRETCH  , 0.0f) , 
#line 396 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 400 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x0150001c, FALSE, EInternal());return TRUE;
#line 401 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x0150001d_Fire_22(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001d
Jump(STATE_CURRENT,0x0150001e, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150001e_Fire_23(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001e
Jump(STATE_CURRENT,0x0150001f, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150001f_Fire_24(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150001f

#line 405 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(m_bcType  == BT_HUGE )){ Jump(STATE_CURRENT,0x0150002e, FALSE, EInternal());return TRUE;}
#line 407 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () <= m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x01500026, FALSE, EInternal());return TRUE;}
#line 409 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 410 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x01500024, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500024_Fire_29(const CEntityEvent &__eeInput)
#line 411 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500024
if(!(m_iCounter  < 6)){ Jump(STATE_CURRENT,0x01500025, FALSE, EInternal());return TRUE;}
#line 412 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACKFAST  , AOF_SMOOTHCHANGE );
#line 413 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500020, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500020_Fire_25(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500020
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500021, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500021_Fire_26(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500021
const EReturn&__e= (EReturn&)__eeInput;
;
#line 415 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 416 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.34f);
Jump(STATE_CURRENT, 0x01500022, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500022_Fire_27(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500022
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500023, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500023_Fire_28(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500023
;
#line 417 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * HUGE_BEAST_STRETCH  , 0.0f) , 
#line 418 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 421 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x01500024, FALSE, EInternal());return TRUE;
#line 422 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x01500025_Fire_30(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500025

#line 423 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 7.0f;Jump(STATE_CURRENT,0x01500026, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500026_Fire_31(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500026

#line 426 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(GetHealth  () > m_fMaxHealth  / 2)){ Jump(STATE_CURRENT,0x0150002d, FALSE, EInternal());return TRUE;}
#line 428 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  = 0;
#line 429 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT,0x0150002b, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150002b_Fire_36(const CEntityEvent &__eeInput)
#line 430 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002b
if(!(m_iCounter  < 3)){ Jump(STATE_CURRENT,0x0150002c, FALSE, EInternal());return TRUE;}
#line 431 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_ATTACK  , AOF_SMOOTHCHANGE );
#line 432 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500027, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500027_Fire_32(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500027
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500028, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500028_Fire_33(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500028
const EReturn&__e= (EReturn&)__eeInput;
;
#line 434 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_FIRE  , SOF_3D );
#line 435 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.5f);
Jump(STATE_CURRENT, 0x01500029, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500029_Fire_34(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500029
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150002a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150002a_Fire_35(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002a
;
#line 436 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ShootProjectile  (PRT_BEAST_BIG_PROJECTILE  , FLOAT3D (0.0f , 1.5f * HUGE_BEAST_STRETCH  , 0.0f) , 
#line 437 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ANGLE3D (0.0f , 0.0f , 0.0f));
#line 441 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iCounter  ++;Jump(STATE_CURRENT,0x0150002b, FALSE, EInternal());return TRUE;
#line 442 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}BOOL CBeast::H0x0150002c_Fire_37(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002c
Jump(STATE_CURRENT,0x0150002d, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150002d_Fire_38(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002d
Jump(STATE_CURRENT,0x0150002e, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x0150002e_Fire_39(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002e

#line 446 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
MaybeSwitchToAnotherPlayer  ();
#line 448 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(FRnd  () / 2 + _pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x0150002f, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150002f_Fire_40(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150002f
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500030, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500030_Fire_41(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500030
;
#line 450 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(m_penEnemy  != NULL )){ Jump(STATE_CURRENT,0x01500036, FALSE, EInternal());return TRUE;}
#line 452 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
FLOAT fEnemyDistance  = CalcDist  (m_penEnemy );
#line 453 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(!(fEnemyDistance  > m_fCloseDistance  * 1.25f)){ Jump(STATE_CURRENT,0x01500035, FALSE, EInternal());return TRUE;}
#line 455 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_IDLETOWALK  , AOF_SMOOTHCHANGE );
#line 456 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE;
Jump(STATE_CURRENT, 0x01500031, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500031_Fire_42(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500031
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CMovableModelEntity_WaitUntilScheduledAnimStarts, FALSE, EVoid());return TRUE;case EVENTCODE_EReturn: Jump(STATE_CURRENT,0x01500032, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500032_Fire_43(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500032
const EReturn&__e= (EReturn&)__eeInput;
;
#line 457 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (BEAST_ANIM_IDLETOWALK ) / 2.0f - _pTimer  -> TickQuantum );
Jump(STATE_CURRENT, 0x01500033, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500033_Fire_44(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500033
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500034, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500034_Fire_45(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500034
;Jump(STATE_CURRENT,0x01500035, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500035_Fire_46(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500035
Jump(STATE_CURRENT,0x01500036, FALSE, EInternal());return TRUE;}BOOL CBeast::H0x01500036_Fire_47(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500036

#line 462 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Return(STATE_CURRENT,EReturn  ());
#line 462 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBeast::
#line 466 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Hit(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Hit
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Hit expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 468 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StartModelAnim  (BEAST_ANIM_KICK  , 0);
#line 469 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.45f);
Jump(STATE_CURRENT, 0x01500038, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x01500038_Hit_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500038
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01500039, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x01500039_Hit_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01500039
;
#line 474 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
PlaySound  (m_soSound  , SOUND_KICK  , SOF_3D );
#line 475 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(CalcDist  (m_penEnemy ) < m_fCloseDistance ){
#line 476 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
FLOAT3D vDirection  = m_penEnemy  -> GetPlacement  () . pl_PositionVector  - GetPlacement  () . pl_PositionVector ;
#line 477 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
vDirection  . Normalize  ();
#line 478 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_BIG ){
#line 479 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 80.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 480 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else if(m_bcType  == BT_HUGE ){
#line 481 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 120.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 482 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}else {
#line 483 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
InflictDirectDamage  (m_penEnemy  , this  , DMT_CLOSERANGE  , 40.0f , FLOAT3D (0 , 0 , 0) , vDirection );
#line 484 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 485 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 491 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetTimerAfter(0.45f);
Jump(STATE_CURRENT, 0x0150003a, FALSE, EBegin());return TRUE;}BOOL CBeast::H0x0150003a_Hit_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150003a
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0150003b, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CBeast::H0x0150003b_Hit_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0150003b
;
#line 492 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
MaybeSwitchToAnotherPlayer  ();
#line 493 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Return(STATE_CURRENT,EReturn  ());
#line 493 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CBeast::
#line 499 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CBeast_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CBeast::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 501 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
InitAsModel  ();
#line 502 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetPhysicsFlags  (EPF_MODEL_WALKING );
#line 503 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetCollisionFlags  (ECF_MODEL );
#line 504 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 506 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
en_fDensity  = 1100.0f;
#line 508 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetModel  (MODEL_BEAST );
#line 509 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
StandingAnim  ();
#line 511 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fWalkSpeed  = FRnd  () * 2 + 5.0f;
#line 512 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 20.0f + 50.0f);
#line 513 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fCloseRunSpeed  = FRnd  () + 10.0f;
#line 514 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 100 + 900.0f);
#line 516 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackDistance  = 500.0f;
#line 517 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 0.0f;
#line 518 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 0.0f;
#line 519 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fCloseFireTime  = 1.0f;
#line 520 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fIgnoreRange  = 750.0f;
#line 521 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_bBoss  = m_bBeBoss ;
#line 522 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 5.0f;
#line 523 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 7.0f;
#line 524 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_tmGiveUp  = Max  (m_tmGiveUp  , 10.0f);
#line 527 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
if(m_bcType  == BT_NORMAL )
#line 528 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 529 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackRunSpeed  = 6.0f;
#line 530 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_aAttackRotateSpeed  = AngleDeg  (3600.0f);
#line 531 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetHealth  (400.0f);
#line 532 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetModelMainTexture  (TEXTURE_BEAST_NORMAL );
#line 533 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fBlowUpAmount  = 10000.0f;
#line 534 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fBodyParts  = 4;
#line 535 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fDamageWounded  = 250.0f;
#line 536 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iScore  = 5000;
#line 538 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
GetModelObject  () -> StretchModel  (FLOAT3D (BEAST_STRETCH  , BEAST_STRETCH  , BEAST_STRETCH ));
#line 539 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ModelChangeNotify  ();
#line 540 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_sptType  = SPT_SLIME ;
#line 541 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 3.0f;
#line 542 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 543 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
else if(m_bcType  == BT_BIG )
#line 544 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 545 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackRunSpeed  = 25.0f;
#line 546 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_aAttackRotateSpeed  = AngleDeg  (600.0f);
#line 547 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetHealth  (3000.0f);
#line 548 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetModelMainTexture  (TEXTURE_BEAST_BIG );
#line 549 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fBlowUpAmount  = 10000.0f;
#line 550 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fBodyParts  = 6;
#line 551 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fDamageWounded  = 650.0f;
#line 552 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iScore  = 25000;
#line 553 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 15;
#line 554 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 20;
#line 556 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
GetModelObject  () -> StretchModel  (FLOAT3D (BIG_BEAST_STRETCH  , BIG_BEAST_STRETCH  , BIG_BEAST_STRETCH ));
#line 557 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ModelChangeNotify  ();
#line 558 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_sptType  = SPT_BLOOD ;
#line 559 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 5.0f;
#line 560 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 561 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
else 
#line 562 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
{
#line 563 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackRunSpeed  = 35.0f;
#line 564 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_aAttackRotateSpeed  = AngleDeg  (600.0f);
#line 565 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetHealth  (6000.0f);
#line 566 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
SetModelMainTexture  (TEXTURE_BEAST_HUGE );
#line 567 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fBlowUpAmount  = 100000.0f;
#line 568 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fBodyParts  = 6;
#line 569 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fDamageWounded  = 1650.0f;
#line 570 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_iScore  = 40000;
#line 571 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fStopDistance  = 75;
#line 572 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fCloseDistance  = 80;
#line 573 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackDistance  = 1000.0f;
#line 574 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fIgnoreRange  = 1200.0f;
#line 576 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
GetModelObject  () -> StretchModel  (FLOAT3D (HUGE_BEAST_STRETCH  , HUGE_BEAST_STRETCH  , HUGE_BEAST_STRETCH ));
#line 577 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
ModelChangeNotify  ();
#line 578 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_sptType  = SPT_BLOOD ;
#line 579 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fAttackFireTime  = 5.0f;
#line 580 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
}
#line 582 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
m_fMaxHealth  = GetHealth  ();
#line 585 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Beast.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};