/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_DestroyableArchitecture_INCLUDED
#define _EntitiesMP_DestroyableArchitecture_INCLUDED 1
#include <EntitiesMP/Devil.h>
#include <EntitiesMP/Debris.h>
#include <EntitiesMP/GradientMarker.h>
#include <EntitiesMP/Effector.h>
extern "C" DECL_DLL CDLLEntityClass CDestroyableArchitecture_DLLClass;
class CDestroyableArchitecture : public CMovableBrushEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual BOOL IsTargetable(void) const { return TRUE; };
  DECL_DLL virtual void SetDefaultProperties(void);
  CTString m_strName;
  FLOAT m_fHealth;
  enum EffectorEffectType m_etType;
  FLOAT3D m_vDamageDir;
  FLOAT m_fStretch;
  CEntityPointer m_penGradient;
  COLOR m_colDebrises;
  INDEX m_ctDebrises;
  FLOAT m_fCandyEffect;
  FLOAT m_fCubeFactor;
  BOOL m_bBlowupByDamager;
  FLOAT m_fDustStretch;
   
#line 119 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
void Precache(void);
   
#line 156 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
BOOL IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget);
   
#line 172 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
const CTString & GetGradientName(INDEX iGradient);
   
#line 188 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
void UncacheShadowsForGradient(class CGradientMarker * penDiscard);
   
#line 198 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
BOOL GetGradient(INDEX iGradient,class CGradientParameters & fpGradient);
   
#line 211 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 212 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 239 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
void DestroyObelisk();
   
#line 306 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
void DestroyPylon();
   
#line 371 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
SLONG GetUsedMemory(void);
#define  STATE_CDestroyableArchitecture_Main 1
  BOOL 
#line 385 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/DestroyableArchitecture.es"
Main(const CEntityEvent &__eeInput);
  BOOL H0x006b0000_Main_01(const CEntityEvent &__eeInput);
  BOOL H0x006b0001_Main_02(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_DestroyableArchitecture_INCLUDED
