/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_EnemyFly_INCLUDED
#define _EntitiesMP_EnemyFly_INCLUDED 1
#include <EntitiesMP/EnemyBase.h>
#include <EntitiesMP/Debris.h>
#include <EntitiesMP/EnemyMarker.h>
extern DECL_DLL CEntityPropertyEnumType EnemyFlyType_enum;
enum EnemyFlyType {
  EFT_GROUND_ONLY = 0,
  EFT_FLY_ONLY = 1,
  EFT_FLY_GROUND_GROUND = 2,
  EFT_FLY_GROUND_AIR = 3,
  EFT_FLY_AIR_GROUND = 4,
  EFT_FLY_AIR_AIR = 5,
};
DECL_DLL inline void ClearToDefault(EnemyFlyType &e) { e = (EnemyFlyType)0; } ;
extern "C" DECL_DLL CDLLEntityClass CEnemyFly_DLLClass;
class DECL_DLL  CEnemyFly : public CEnemyBase {
public:
   virtual void SetDefaultProperties(void);
  enum EnemyFlyType m_EeftType;
  BOOL m_bInAir;
  BOOL m_bAirAttack;
  BOOL m_bStartInAir;
  FLOAT m_fGroundToAirSpeed;
  FLOAT m_fAirToGroundSpeed;
  FLOAT m_fAirToGroundMin;
  FLOAT m_fAirToGroundMax;
  FLOAT m_fFlyHeight;
  FLOAT m_fFlyWalkSpeed;
  ANGLE m_aFlyWalkRotateSpeed;
  FLOAT m_fFlyAttackRunSpeed;
  ANGLE m_aFlyAttackRotateSpeed;
  FLOAT m_fFlyCloseRunSpeed;
  ANGLE m_aFlyCloseRotateSpeed;
  FLOAT m_fFlyAttackDistance;
  FLOAT m_fFlyCloseDistance;
  FLOAT m_fFlyAttackFireTime;
  FLOAT m_fFlyCloseFireTime;
  FLOAT m_fFlyStopDistance;
  FLOAT m_fFlyIgnoreRange;
  FLOAT m_fFlyLockOnEnemyTime;
  BOOL m_bFlyToMarker;
  
#line 76 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual FLOAT & GetProp(FLOAT & m_fBase);
  
#line 86 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual FLOAT3D PlayerDestinationPos(void);
   
#line 116 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
void StartPathFinding(void);
  
#line 126 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual void AdjustDifficulty(void);
  
#line 147 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual BOOL CanHitEnemy(CEntity * penTarget,FLOAT fCosAngle);
  
#line 159 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual ULONG SetDesiredMovement(void);
   
#line 190 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
void SetEntityPosition();
  
#line 233 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual FLOAT AirToGroundAnim(void);
  
#line 234 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual FLOAT GroundToAirAnim(void);
  
#line 235 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual void ChangeCollisionToAir(void);
  
#line 236 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
virtual void ChangeCollisionToGround(void);
#define  STATE_CEnemyFly_ReturnToStartPosition 0x01370000
  BOOL 
#line 282 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
ReturnToStartPosition(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_BeWounded 0x01370001
  BOOL 
#line 320 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
BeWounded(const CEntityEvent &__eeInput);
  BOOL H0x01370002_BeWounded_01(const CEntityEvent &__eeInput);
  BOOL H0x01370003_BeWounded_02(const CEntityEvent &__eeInput);
  BOOL H0x01370004_BeWounded_03(const CEntityEvent &__eeInput);
  BOOL H0x01370005_BeWounded_04(const CEntityEvent &__eeInput);
  BOOL H0x01370006_BeWounded_05(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_AirToGround 0x01370007
  BOOL 
#line 337 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
AirToGround(const CEntityEvent &__eeInput);
  BOOL H0x01370008_AirToGround_01(const CEntityEvent &__eeInput);
  BOOL H0x01370009_AirToGround_02(const CEntityEvent &__eeInput);
  BOOL H0x0137000a_AirToGround_03(const CEntityEvent &__eeInput);
  BOOL H0x0137000b_AirToGround_04(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_GroundToAir 0x0137000c
  BOOL 
#line 371 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
GroundToAir(const CEntityEvent &__eeInput);
  BOOL H0x0137000d_GroundToAir_01(const CEntityEvent &__eeInput);
  BOOL H0x0137000e_GroundToAir_02(const CEntityEvent &__eeInput);
  BOOL H0x0137000f_GroundToAir_03(const CEntityEvent &__eeInput);
  BOOL H0x01370010_GroundToAir_04(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_AttackEnemy 0x01370011
  BOOL 
#line 404 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
AttackEnemy(const CEntityEvent &__eeInput);
  BOOL H0x01370012_AttackEnemy_01(const CEntityEvent &__eeInput);
  BOOL H0x01370013_AttackEnemy_02(const CEntityEvent &__eeInput);
  BOOL H0x01370014_AttackEnemy_03(const CEntityEvent &__eeInput);
  BOOL H0x01370015_AttackEnemy_04(const CEntityEvent &__eeInput);
  BOOL H0x01370016_AttackEnemy_05(const CEntityEvent &__eeInput);
  BOOL H0x01370017_AttackEnemy_06(const CEntityEvent &__eeInput);
  BOOL H0x01370018_AttackEnemy_07(const CEntityEvent &__eeInput);
  BOOL H0x01370019_AttackEnemy_08(const CEntityEvent &__eeInput);
  BOOL H0x0137001a_AttackEnemy_09(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_Hit 0x0137001b
  BOOL 
#line 424 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Hit(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_Fire 0x0137001c
  BOOL 
#line 434 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Fire(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_Death 0x0137001d
  BOOL 
#line 446 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Death(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_MainLoop 0x0137001e
  BOOL 
#line 459 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
MainLoop(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_Main 1
  BOOL 
#line 465 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
Main(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_GroundHit 0x0137001f
  BOOL 
#line 473 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
GroundHit(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_GroundFire 0x01370020
  BOOL 
#line 478 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
GroundFire(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_FlyHit 0x01370021
  BOOL 
#line 484 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FlyHit(const CEntityEvent &__eeInput);
#define  STATE_CEnemyFly_FlyFire 0x01370022
  BOOL 
#line 490 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnemyFly.es"
FlyFire(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_EnemyFly_INCLUDED
