/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_EnvironmentMarker_INCLUDED
#define _EntitiesMP_EnvironmentMarker_INCLUDED 1
#include <EntitiesMP/Marker.h>
extern "C" DECL_DLL CDLLEntityClass CEnvironmentMarker_DLLClass;
class CEnvironmentMarker : public CMarker {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  FLOAT m_fWaitTime;
  FLOAT m_fRandomTime;
  RANGE m_fMarkerRange;
  BOOL m_bFixedAnimLength;
  BOOL m_bChangeDefaultAnim;
  FLOAT m_fMoveSpeed;
  FLOAT m_fRotateSpeed;
  CTFileName m_fnMdl;
  ANIMATION m_iAnim;
  CModelObject m_moAnimData;
   
#line 47 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnvironmentMarker.es"
BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   
#line 52 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnvironmentMarker.es"
BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
   
#line 58 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnvironmentMarker.es"
CAnimData * GetAnimData(SLONG slPropertyOffset);
   
#line 69 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnvironmentMarker.es"
void SetModelObject(void);
#define  STATE_CEnvironmentMarker_Main 1
  BOOL 
#line 92 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/EnvironmentMarker.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_EnvironmentMarker_INCLUDED
