/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 17 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"

#include "EntitiesMP/StdH/StdH.h"

#include <EntitiesMP/Light.h>
#include <EntitiesMP/Light_tables.h>
#line 48 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"


void CLight_OnInitClass(void)
{
  // init lens flares effects
  InitLensFlares();
}

void CLight_OnEndClass(void)
{
  // close lens flares effects
  CloseLensFlares();
}


void CLight::SetDefaultProperties(void) {
  m_colColor = C_GRAY ;
  m_colAmbient = C_BLACK ;
  m_rFallOffRange = 8.0f;
  m_rHotSpotRange = 0.0f;
  m_itIllumination = 0;
  m_ltType = LT_POINT ;
  m_strDescription = "";
  m_strName = "Light";
  m_bDarkLight = FALSE ;
  m_fNearClip = 0.1f;
  m_fFarClip = 0.01f;
  m_bSubstractSectorAmbient = FALSE ;
  m_bRenderAsSmallLight = FALSE ;
  m_lftLensFlare = LFT_NONE ;
  m_bBackground = FALSE ;
  m_bLensFlareOnly = FALSE ;
  m_fnmLightAnimation = CTString("");
  m_iLightAnimation = 0;
  m_tmOffsetPhase = 0.0f;
  m_aoLightAnimation.SetData(NULL);

  m_bTargetable = FALSE ;
  m_bDynamic = FALSE ;
  m_bDiffusion = TRUE ;
  m_fnmAmbientLightAnimation = CTString("");
  m_iAmbientLightAnimation = 0;
  m_aoAmbientLightAnimation.SetData(NULL);

  CEntity::SetDefaultProperties();
}
  
#line 109 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
CAnimData * CLight::GetAnimData(SLONG slPropertyOffset) 
#line 110 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 111 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(slPropertyOffset  == _offsetof  (CLight  , m_iLightAnimation ))
#line 112 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 113 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return m_aoLightAnimation  . GetData  ();
#line 114 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 115 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
else if(slPropertyOffset  == _offsetof  (CLight  , m_iAmbientLightAnimation ))
#line 116 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 117 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return m_aoAmbientLightAnimation  . GetData  ();
#line 118 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 119 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
else 
#line 120 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 121 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return CEntity  :: GetAnimData  (slPropertyOffset );
#line 122 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 123 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
  
#line 125 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
BOOL CLight::IsTargetable(void)const 
#line 126 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 127 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return m_bTargetable ;
#line 128 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
  
#line 130 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
BOOL CLight::IsImportant(void)const 
#line 131 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 132 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return (m_ltType  == LT_DIRECTIONAL );
#line 133 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
  
#line 136 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
BOOL CLight::HandleEvent(const CEntityEvent & ee) 
#line 137 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 139 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(ee  . ee_slEvent  == EVENTCODE_ERangeModelDestruction )
#line 140 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 142 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_colColor  = C_BLACK ;
#line 143 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_colAmbient  = C_BLACK ;
#line 144 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 145 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 146 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 147 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return TRUE ;
#line 149 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 150 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
else if(ee  . ee_slEvent  == EVENTCODE_EChangeAnim )
#line 151 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 152 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
EChangeAnim  & eChange  = (EChangeAnim  &) ee ;
#line 155 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_iLightAnimation  = eChange  . iLightAnim ;
#line 156 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL )
#line 157 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 158 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , eChange  . bLightLoop  ? AOF_LOOPING  : 0);
#line 159 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 162 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_iAmbientLightAnimation  = eChange  . iAmbientLightAnim ;
#line 163 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL )
#line 164 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 165 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . PlayAnim  (m_iAmbientLightAnimation  , eChange  . bAmbientLightLoop  ? AOF_LOOPING  : 0);
#line 166 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 169 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if((m_aoLightAnimation  . GetData  () == NULL ) && (m_aoAmbientLightAnimation  . GetData  () == NULL ))
#line 170 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 171 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_colColor  = eChange  . colDiffuse ;
#line 172 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_colAmbient  = eChange  . colAmbient ;
#line 173 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 174 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 175 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 176 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return TRUE ;
#line 177 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 178 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 179 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return FALSE ;
#line 180 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
  
#line 183 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
void CLight::MirrorAndStretch(FLOAT fStretch,BOOL bMirrorX) 
#line 184 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 186 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_rFallOffRange  *= fStretch ;
#line 187 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_rHotSpotRange  *= fStretch ;
#line 188 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_fNearClip  *= fStretch ;
#line 189 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_fFarClip  *= fStretch ;
#line 191 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
  
#line 194 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
CLightSource * CLight::GetLightSource(void) 
#line 195 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 197 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(! m_bdfInitialized  . bdf_bValue ){
#line 199 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 200 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 201 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSourceWithNoDiscarding  (lsNew );
#line 202 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = TRUE ;
#line 203 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 204 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(! IsPredictor  ()){
#line 205 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return & m_lsLightSource ;
#line 206 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}else {
#line 207 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return NULL ;
#line 208 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 209 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
  
#line 212 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
void CLight::SetupLightSource(CLightSource & lsNew) 
#line 213 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 214 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
switch(m_ltType ){
#line 215 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LT_POINT : 
#line 216 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LT_STRONG_POINT : 
#line 217 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = LSF_CASTSHADOWS ;
#line 218 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 219 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LT_DIRECTIONAL : 
#line 220 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = LSF_DIRECTIONAL  | LSF_CASTSHADOWS ;
#line 221 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 222 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LT_STRONG_AMBIENT : 
#line 223 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LT_AMBIENT : 
#line 224 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  = 0;
#line 225 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 226 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 227 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bSubstractSectorAmbient ){lsNew  . ls_ulFlags  |= LSF_SUBSTRACTSECTORAMBIENT ;}
#line 228 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bLensFlareOnly ){lsNew  . ls_ulFlags  |= LSF_LENSFLAREONLY ;}
#line 229 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bDynamic ){lsNew  . ls_ulFlags  |= LSF_DYNAMIC ;}
#line 231 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bDarkLight ){
#line 232 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_ltType  == LT_DIRECTIONAL ){
#line 233 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  &= ~ LSF_DARKLIGHT ;
#line 234 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_bDarkLight  = FALSE ;
#line 235 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}else {
#line 236 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  |= LSF_DARKLIGHT ;
#line 237 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 238 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 240 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bDiffusion ){
#line 241 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bDynamic  || m_ltType  == LT_AMBIENT  || m_ltType  == LT_STRONG_AMBIENT ){
#line 242 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  &= ~ LSF_DIFFUSION ;
#line 243 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_bDiffusion  = FALSE ;
#line 244 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}else {
#line 245 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ulFlags  |= LSF_DIFFUSION ;
#line 246 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 247 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 249 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_rHotSpot  = m_rHotSpotRange ;
#line 250 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_rFallOff  = m_rFallOffRange ;
#line 251 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_fNearClipDistance  = m_fNearClip ;
#line 252 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_fFarClipDistance  = m_fFarClip ;
#line 254 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_ltType  == LT_STRONG_AMBIENT  || m_ltType  == LT_STRONG_POINT ){
#line 255 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_rHotSpot  = lsNew  . ls_rFallOff  * 0.9f;
#line 256 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 258 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_colColor  = m_colColor ;
#line 259 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_colAmbient  = C_BLACK ;
#line 260 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(lsNew  . ls_ulFlags  & LSF_DIRECTIONAL ){lsNew  . ls_colAmbient  = m_colAmbient ;}
#line 261 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_ubPolygonalMask  = (UBYTE ) m_itIllumination ;
#line 263 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
switch(m_lftLensFlare )
#line 264 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 265 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_NONE : 
#line 266 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = NULL ;
#line 267 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 268 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_STANDARD : 
#line 269 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftStandard ;
#line 270 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 271 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_STANDARD_REFLECTIONS : 
#line 272 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftStandardReflections ;
#line 273 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 274 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_YELLOW_STAR_RED_RING : 
#line 275 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRing ;
#line 276 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 277 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_RED_RING : 
#line 278 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarRedRing ;
#line 279 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 280 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR : 
#line 281 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStar ;
#line 282 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 283 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_WHITE_STAR_RED_RING_STREAKS : 
#line 284 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedRingStreaks ;
#line 285 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 286 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_WHITE_STAR_RED_REFLECTIONS : 
#line 287 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedReflections ;
#line 288 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 289 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_BLUE_STAR_BLUE_REFLECTIONS : 
#line 290 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftBlueStarBlueReflections ;
#line 291 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 292 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_PV_SPACE_SHIP_WINDOW_FLARE : 
#line 293 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftPVSpaceShipWindowFlare ;
#line 294 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 295 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_RED_RING_FAR : 
#line 296 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRingFar ;
#line 297 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 298 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_FAR : 
#line 299 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowFar ;
#line 300 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 301 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
case LFT_WHITE_GLOW_STAR_NG : 
#line 302 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarNG ;
#line 303 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
break ;
#line 304 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 308 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_paoLightAnimation  = NULL ;
#line 309 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 310 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_paoLightAnimation  = & m_aoLightAnimation ;
#line 311 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 314 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_paoAmbientLightAnimation  = NULL ;
#line 315 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL ){
#line 316 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
lsNew  . ls_paoAmbientLightAnimation  = & m_aoAmbientLightAnimation ;
#line 317 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 318 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
  
#line 322 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SLONG CLight::GetUsedMemory(void) 
#line 323 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 325 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SLONG  slUsedMemory  = sizeof  (CLight ) - sizeof  (CEntity ) + CEntity  :: GetUsedMemory  ();
#line 327 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
slUsedMemory  += m_strDescription  . Length  ();
#line 328 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
slUsedMemory  += m_strName  . Length  ();
#line 329 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
slUsedMemory  += m_fnmLightAnimation  . Length  ();
#line 330 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
slUsedMemory  += m_fnmAmbientLightAnimation  . Length  ();
#line 331 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
slUsedMemory  += 2 * sizeof  (CAnimObject);
#line 332 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return slUsedMemory ;
#line 333 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
BOOL CLight::
#line 337 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CLight_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CLight::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 340 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_rFallOffRange  < 0){
#line 341 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_rFallOffRange  = 0.0f;
#line 342 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 343 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_rHotSpotRange  < 0){
#line 344 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_rHotSpotRange  = 0.0f;
#line 345 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 347 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_rHotSpotRange  > m_rFallOffRange ){
#line 348 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_rHotSpotRange  = m_rFallOffRange ;
#line 349 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 358 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_fNearClip  <= 0.01f){
#line 359 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_fNearClip  = 0.01f;
#line 360 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 362 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_fFarClip  <= 0){
#line 363 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_fFarClip  = 0.0f;
#line 364 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 367 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_ltType  != LT_DIRECTIONAL ){
#line 368 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_colAmbient  = C_BLACK ;
#line 369 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 371 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
InitAsEditorModel  ();
#line 372 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 373 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 376 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bRenderAsSmallLight )
#line 377 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 378 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (0.25f , 0.25f , 0.25f);
#line 379 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 380 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
else 
#line 381 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 383 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_ltType  != LT_DIRECTIONAL ){
#line 384 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
const float  LIGHT_MINSIZE  = 0.5f;
#line 385 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
FLOAT fFactor  = Log2  (m_rFallOffRange ) * LIGHT_MINSIZE ;
#line 386 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(fFactor  < LIGHT_MINSIZE ){
#line 387 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
fFactor  = LIGHT_MINSIZE ;
#line 388 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 389 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (fFactor  , fFactor  , fFactor );
#line 390 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 391 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 393 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
CTString strType ;
#line 394 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_ltType  == LT_POINT  || m_ltType  == LT_STRONG_POINT )
#line 395 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 396 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
strType  = "point";
#line 398 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 400 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_POINT_LIGHT );
#line 401 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 403 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
else if(m_ltType  == LT_AMBIENT )
#line 404 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 405 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
strType  = "ambient";
#line 407 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 409 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_AMBIENT_LIGHT );
#line 410 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 412 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
else if(m_ltType  == LT_STRONG_AMBIENT )
#line 413 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 414 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
strType  = "ambient";
#line 416 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModel  (MODEL_LIGHT_SOURCE );
#line 418 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_REAL_AMBIENT_LIGHT );
#line 419 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 421 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
else if(m_ltType  == LT_DIRECTIONAL )
#line 422 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 423 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
strType  = "directional";
#line 425 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModel  (MODEL_SPOT_LIGHT );
#line 427 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetModelMainTexture  (TEXTURE_SPOT_LIGHT );
#line 428 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 430 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bDarkLight )
#line 431 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
{
#line 432 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
strType  = strType  + ", dark";
#line 433 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 436 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
try {
#line 437 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoLightAnimation  . SetData_t  (m_fnmLightAnimation );
#line 438 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}catch  (const char  * strError ){
#line 439 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
WarningMessage  (TRANS  ("Cannot load '%s': %s") , (const char  *) (CTString &) m_fnmLightAnimation  , strError );
#line 440 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_fnmLightAnimation  = "";
#line 441 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 442 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 443 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , AOF_LOOPING );
#line 444 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoLightAnimation  . OffsetPhase  (m_tmOffsetPhase  * m_aoLightAnimation  . GetCurrentAnimLength  ());
#line 445 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 448 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
try {
#line 449 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . SetData_t  (m_fnmAmbientLightAnimation );
#line 450 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}catch  (const char  * strError ){
#line 451 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
WarningMessage  (TRANS  ("Cannot load '%s': %s") , (const char  *) (CTString &) m_fnmAmbientLightAnimation  , strError );
#line 452 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_fnmAmbientLightAnimation  = "";
#line 453 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 454 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_aoAmbientLightAnimation  . GetData  () != NULL ){
#line 455 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . PlayAnim  (m_iAmbientLightAnimation  , AOF_LOOPING );
#line 456 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_aoAmbientLightAnimation  . OffsetPhase  (m_tmOffsetPhase  * m_aoAmbientLightAnimation  . GetCurrentAnimLength  ());
#line 457 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 460 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
CLightSource  lsNew ;
#line 461 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetupLightSource  (lsNew );
#line 464 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(m_bBackground ){
#line 465 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetFlags  (GetFlags  () | ENF_BACKGROUND );
#line 466 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}else {
#line 467 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
SetFlags  (GetFlags  () & ~ ENF_BACKGROUND );
#line 468 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 471 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_lsLightSource  . ls_penEntity  = this ;
#line 472 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
if(! m_bdfInitialized  . bdf_bValue ){
#line 473 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSourceWithNoDiscarding  (lsNew );
#line 474 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_bdfInitialized  . bdf_bValue  = TRUE ;
#line 475 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}else {
#line 476 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 477 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
}
#line 479 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
m_strDescription  . PrintF  ("%s:%g-%g" , 
#line 480 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
(const char  *) strType  , m_rHotSpotRange  , m_rFallOffRange );
#line 482 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
Return(STATE_CURRENT,EVoid());
#line 482 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Light.es"
return TRUE; ASSERT(FALSE); return TRUE;};