/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#define ENTITYCLASS CPyramidSpaceShipMarker

CEntityProperty CPyramidSpaceShipMarker_properties[] = {
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x00000262<<8)+1, _offsetof(CPyramidSpaceShipMarker, m_fDeltaTime), "Delta time", 'D', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x00000262<<8)+2, _offsetof(CPyramidSpaceShipMarker, m_fBias), "Bias", 'B', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x00000262<<8)+3, _offsetof(CPyramidSpaceShipMarker, m_fTension), "Tension", 'E', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x00000262<<8)+4, _offsetof(CPyramidSpaceShipMarker, m_fContinuity), "Continuity", 'C', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x00000262<<8)+5, _offsetof(CPyramidSpaceShipMarker, m_bStopMoving), "Stop moving", 'O', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x00000262<<8)+6, _offsetof(CPyramidSpaceShipMarker, m_penTrigger), "Trigger", 'G', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT, NULL, (0x00000262<<8)+7, _offsetof(CPyramidSpaceShipMarker, m_fRotSpeed), "Rotation speed", 'R', 0x7F0000FFUL, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x00000262<<8)+8, _offsetof(CPyramidSpaceShipMarker, m_penSpaceShip), "Space ship", 'S', 0x7F0000FFUL, 0),
};
#define CPyramidSpaceShipMarker_propertiesct ARRAYCOUNT(CPyramidSpaceShipMarker_properties)

CEntityComponent CPyramidSpaceShipMarker_components[] = {
#define MODEL_MARKER ((0x00000262<<8)+1)
 CEntityComponent(ECT_MODEL, MODEL_MARKER, "EFNM" "Models\\Editor\\Axis.mdl"),
#define TEXTURE_MARKER ((0x00000262<<8)+2)
 CEntityComponent(ECT_TEXTURE, TEXTURE_MARKER, "EFNM" "Models\\Editor\\Vector.tex"),
};
#define CPyramidSpaceShipMarker_componentsct ARRAYCOUNT(CPyramidSpaceShipMarker_components)

CEventHandlerEntry CPyramidSpaceShipMarker_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CPyramidSpaceShipMarker::
#line 87 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/PyramidSpaceShipMarker.es"
Main),DEBUGSTRING("CPyramidSpaceShipMarker::Main")},
};
#define CPyramidSpaceShipMarker_handlersct ARRAYCOUNT(CPyramidSpaceShipMarker_handlers)

CEntity *CPyramidSpaceShipMarker_New(void) { return new CPyramidSpaceShipMarker; };
void CPyramidSpaceShipMarker_OnInitClass(void) {};
void CPyramidSpaceShipMarker_OnEndClass(void) {};
void CPyramidSpaceShipMarker_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) {};
void CPyramidSpaceShipMarker_OnWorldEnd(CWorld *pwo) {};
void CPyramidSpaceShipMarker_OnWorldInit(CWorld *pwo) {};
void CPyramidSpaceShipMarker_OnWorldTick(CWorld *pwo) {};
void CPyramidSpaceShipMarker_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CPyramidSpaceShipMarker, CMarker, "Pyramid Space Ship Marker", "Thumbnails\\PyramidSpaceShipMarker.tbn", 0x00000262);
DECLARE_CTFILENAME(_fnmCPyramidSpaceShipMarker_tbn, "Thumbnails\\PyramidSpaceShipMarker.tbn");
