/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _EntitiesMP_Santa_INCLUDED
#define _EntitiesMP_Santa_INCLUDED 1
#include <EntitiesMP/EnemyBase.h>
extern "C" DECL_DLL CDLLEntityClass CSanta_DLLClass;
class CSanta : public CEnemyBase {
public:
  DECL_DLL virtual void SetDefaultProperties(void);
  FLOAT m_tmLastSpawnTime;
  FLOAT m_tmMinSpawnInterval;
  FLOAT m_fSantaHealth;
  CSoundObject m_soRunning;
  BOOL m_bRunSoundPlaying;
  CEntityPointer m_penTemplate0;
  CEntityPointer m_penTemplate1;
  CEntityPointer m_penTemplate2;
  CEntityPointer m_penTemplate3;
  CEntityPointer m_penTemplate4;
   
#line 62 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void Precache(void);
  
#line 69 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
virtual const CTFileName & GetComputerMessageName(void)const;
   
#line 76 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void * GetEntityInfo(void);
   
#line 81 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void ActivateRunningSound(void);
   
#line 88 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void DeactivateRunningSound(void);
   
#line 95 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
BOOL HandleEvent(const CEntityEvent & ee);
   
#line 106 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 107 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection);
   
#line 151 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void LeaveStain(BOOL bGrow);
   
#line 156 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
INDEX AnimForDamage(FLOAT fDamage);
   
#line 162 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
INDEX AnimForDeath(void);
   
#line 167 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void DeathNotify(void);
   
#line 174 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
CModelObject * GetBody(void);
   
#line 180 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void StandingAnim(void);
   
#line 184 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void WalkingAnim(void);
   
#line 189 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void RunningAnim(void);
   
#line 194 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void RotatingAnim(void);
   
#line 201 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void IdleSound(void);
   
#line 204 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void SightSound(void);
   
#line 207 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void WoundSound(void);
   
#line 210 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void DeathSound(void);
   
#line 216 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
void EnemyPostInit(void);
#define  STATE_CSanta_Fire 0x01630000
  BOOL 
#line 227 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
Fire(const CEntityEvent &__eeInput);
#define  STATE_CSanta_Hit 0x01630001
  BOOL 
#line 232 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
Hit(const CEntityEvent &__eeInput);
#define  STATE_CSanta_Main 1
  BOOL 
#line 239 "/data/data/com.termux/files/home/doom3/SeriousSamClassic-1.10.7/SamTSE/Sources/EntitiesMP/Santa.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _EntitiesMP_Santa_INCLUDED
