// Copyright (C) 2007 Id Software, Inc.
//


#ifndef __GAME_INTERFACES_RESUPPLYINTERFACE_H__
#define __GAME_INTERFACES_RESUPPLYINTERFACE_H__

#endif // __GAME_INTERFACES_RESUPPLYINTERFACE_H__

