//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dhewm3.rc
//
#define _USE_DECLSPECS_FOR_SAL          0
#define _USE_ATTRIBUTES_FOR_SAL         0
#define __drv_typeConst                 0
#define PASSIVE_LEVEL                   0
#define PRAGMA_DEPRECATED_DDK           0
#define ERROR_SEVERITY_SUCCESS          0x00000000
#define EXCEPTION_CONTINUE_SEARCH       0
#define PRODUCT_UNDEFINED               0x00000000
#define LANG_NEUTRAL                    0x00
#define SUBLANG_NEUTRAL                 0x00
#define SORT_DEFAULT                    0x0
#define SORT_JAPANESE_XJIS              0x0
#define SORT_CHINESE_BIG5               0x0
#define SORT_CHINESE_PRCP               0x0
#define SORT_KOREAN_KSC                 0x0
#define SORT_HUNGARIAN_DEFAULT          0x0
#define SORT_GEORGIAN_TRADITIONAL       0x0
#define ACCESS_OBJECT_GUID              0
#define TOKEN_MANDATORY_POLICY_OFF      0x0
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_INVALID 0x00
#define JOB_OBJECT_TERMINATE_AT_END_OF_JOB 0
#define JOB_OBJECT_UILIMIT_NONE         0x00000000
#define TIME_ZONE_ID_UNKNOWN            0
#define PROCESSOR_ARCHITECTURE_INTEL    0
#define PF_FLOATING_POINT_PRECISION_ERRATA 0
#define POWERBUTTON_ACTION_INDEX_NOTHING 0
#define POWERBUTTON_ACTION_VALUE_NOTHING 0
#define PERFSTATE_POLICY_CHANGE_IDEAL   0
#define PROCESSOR_PERF_BOOST_POLICY_DISABLED 0
#define PROCESSOR_PERF_BOOST_MODE_DISABLED 0
#define CORE_PARKING_POLICY_CHANGE_IDEAL 0
#define POWER_DEVICE_IDLE_POLICY_PERFORMANCE 0
#define DIAGNOSTIC_REASON_VERSION       0
#define PPM_PERFORMANCE_IMPLEMENTATION_NONE 0x00000000
#define PPM_IDLE_IMPLEMENTATION_NONE    0x00000000
#define DISCHARGE_POLICY_CRITICAL       0
#define PO_THROTTLE_NONE                0
#define IMAGE_FILE_MACHINE_UNKNOWN      0
#define IMAGE_SUBSYSTEM_UNKNOWN         0
#define IMAGE_DIRECTORY_ENTRY_EXPORT    0
#define IMAGE_SYM_TYPE_NULL             0x0000
#define IMAGE_SYM_DTYPE_NULL            0
#define IMAGE_SYM_CLASS_NULL            0x0000
#define IMAGE_REL_I386_ABSOLUTE         0x0000
#define IMAGE_REL_MIPS_ABSOLUTE         0x0000
#define IMAGE_REL_ALPHA_ABSOLUTE        0x0000
#define IMAGE_REL_PPC_ABSOLUTE          0x0000
#define IMAGE_REL_SH3_ABSOLUTE          0x0000
#define IMAGE_REL_ARM_ABSOLUTE          0x0000
#define IMAGE_REL_AM_ABSOLUTE           0x0000
#define IMAGE_REL_AMD64_ABSOLUTE        0x0000
#define IMAGE_REL_IA64_ABSOLUTE         0x0000
#define IMAGE_REL_CEF_ABSOLUTE          0x0000
#define IMAGE_REL_CEE_ABSOLUTE          0x0000
#define IMAGE_REL_M32R_ABSOLUTE         0x0000
#define IMAGE_REL_EBC_ABSOLUTE          0x0000
#define EMARCH_ENC_I17_IMM7B_VAL_POS_X  0
#define EMARCH_ENC_I17_IMM41c_INST_WORD_POS_X 0
#define X3_OPCODE_SIGN_VAL_POS_X        0
#define X3_D_WH_SIGN_VAL_POS_X          0
#define X3_IMM20_SIGN_VAL_POS_X         0
#define X3_IMM39_1_INST_WORD_POS_X      0
#define X3_P_INST_WORD_POS_X            0
#define X3_P_SIGN_VAL_POS_X             0
#define X3_TMPLT_INST_WORD_X            0
#define X3_TMPLT_INST_WORD_POS_X        0
#define X3_TMPLT_SIGN_VAL_POS_X         0
#define X3_BTYPE_QP_INST_VAL_POS_X      0
#define X3_EMPTY_INST_VAL_POS_X         0
#define IMAGE_REL_BASED_ABSOLUTE        0
#define IMAGE_DEBUG_TYPE_UNKNOWN        0
#define FRAME_FPO                       0
#define FAST_FAIL_LEGACY_GS_VIOLATION   0
#define VER_PLATFORM_WIN32s             0
#define RTL_CRITSECT_TYPE               0
#define WT_EXECUTEDEFAULT               0x00000000
#define DLL_PROCESS_DETACH              0
#define EVENTLOG_SUCCESS                0x0000
#define SERVICE_BOOT_START              0x00000000
#define SERVICE_ERROR_IGNORE            0x00000000
#define TRANSACTION_MANAGER_COMMIT_DEFAULT 0x00000000
#define FALSE                           0
#define LMEM_FIXED                      0x0000
#define SB_HORZ                         0
#define SB_LINEUP                       0
#define SB_LINELEFT                     0
#define SW_HIDE                         0
#define HIDE_WINDOW                     0
#define WH_JOURNALRECORD                0
#define HC_ACTION                       0
#define HCBT_MOVESIZE                   0
#define MSGF_DIALOGBOX                  0
#define FAPPCOMMAND_KEY                 0
#define HKL_PREV                        0
#define WM_NULL                         0x0000
#define WA_INACTIVE                     0
#define PBT_APMQUERYSUSPEND             0x0000
#define HTNOWHERE                       0
#define SMTO_NORMAL                     0x0000
#define ICON_SMALL                      0
#define SIZE_RESTORED                   0
#define DFCS_CAPTIONCLOSE               0x0000
#define DFCS_MENUARROW                  0x0000
#define DFCS_SCROLLUP                   0x0000
#define DFCS_BUTTONCHECK                0x0000
#define PM_NOREMOVE                     0x0000
#define EWX_LOGOFF                      0x00000000
#define BSM_ALLCOMPONENTS               0x00000000
#define DEVICE_NOTIFY_WINDOW_HANDLE     0x00000000
#define ISMEX_NOSEND                    0x00000000
#define FLASHW_STOP                     0
#define WDA_NONE                        0x00000000
#define INPUT_MOUSE                     0
#define POINTER_FLAG_NONE               0x00000000
#define TOUCH_FLAG_NONE                 0x00000000
#define TOUCH_MASK_NONE                 0x00000000
#define PEN_FLAG_NONE                   0x00000000
#define PEN_MASK_NONE                   0x00000000
#define TOUCH_HIT_TESTING_DEFAULT       0x0
#define TOUCH_HIT_TESTING_PROXIMITY_CLOSEST 0x0
#define TIMERV_DEFAULT_COALESCING       0
#define SM_CXSCREEN                     0
#define MNC_IGNORE                      0
#define MND_CONTINUE                    0
#define MNGO_NOINTERFACE                0x00000000
#define DT_TOP                          0x00000000
#define DT_LEFT                         0x00000000
#define DST_COMPLEX                     0x0000
#define DSS_NORMAL                      0x0000
#define ESB_ENABLE_BOTH                 0x0000
#define CWP_ALL                         0x0000
#define CTLCOLOR_MSGBOX                 0
#define COLOR_SCROLLBAR                 0
#define GW_HWNDFIRST                    0
#define IMAGE_BITMAP                    0
#define LR_DEFAULTCOLOR                 0x00000000
#define WB_LEFT                         0
#define BN_CLICKED                      0
#define BST_UNCHECKED                   0x0000
#define STN_CLICKED                     0
#define DWL_MSGRESULT                   0
#define DWLP_MSGRESULT                  0
#define DDL_READWRITE                   0x0000
#define LB_OKAY                         0
#define CB_OKAY                         0
#define MDITILE_VERTICAL                0x0000
#define GR_GDIOBJECTS                   0
#define FE_FONTSMOOTHINGORIENTATIONBGR  0x0000
#define CONTACTVISUALIZATION_OFF        0x0000
#define GESTUREVISUALIZATION_OFF        0x0000
#define MOUSEWHEEL_ROUTING_FOCUS        0
#define DISP_CHANGE_SUCCESSFUL          0
#define SSGF_NONE                       0
#define SSTF_NONE                       0
#define SSWF_NONE                       0
#define MONITOR_DEFAULTTONULL           0x00000000
#define WINEVENT_OUTOFCONTEXT           0x0000
#define CHILDID_SELF                    0
#define INDEXID_OBJECT                  0
#define INDEXID_CONTAINER               0
#define RIM_INPUT                       0
#define RIM_TYPEMOUSE                   0
#define MOUSE_MOVE_RELATIVE             0
#define RI_KEY_MAKE                     0
#define MSGFLTINFO_NONE                 0
#define MSGFLT_RESET                    0
#define _HAS_EXCEPTIONS                 1
#define _CRT_BUILD_DESKTOP_APP          1
#define __STDC_WANT_SECURE_LIB__        1
#define _UPPER                          0x01
#define ANYSIZE_ARRAY                   1
#define __drv_typeCond                  1
#define APC_LEVEL                       1
#define EPERM                           1
#define EXCEPTION_EXECUTE_HANDLER       1
#define VER_SUITE_SMALLBUSINESS         0x00000001
#define PRODUCT_ULTIMATE                0x00000001
#define LANG_ENGLISH                     0x09
#define LANG_ARABIC                     0x01
#define SUBLANG_DEFAULT                 0x01
#define SUBLANG_AFRIKAANS_SOUTH_AFRICA  0x01
#define SUBLANG_ALBANIAN_ALBANIA        0x01
#define SUBLANG_ALSATIAN_FRANCE         0x01
#define SUBLANG_AMHARIC_ETHIOPIA        0x01
#define SUBLANG_ARABIC_SAUDI_ARABIA     0x01
#define SUBLANG_ARMENIAN_ARMENIA        0x01
#define SUBLANG_ASSAMESE_INDIA          0x01
#define SUBLANG_AZERI_LATIN             0x01
#define SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN 0x01
#define SUBLANG_BANGLA_INDIA            0x01
#define SUBLANG_BASHKIR_RUSSIA          0x01
#define SUBLANG_BASQUE_BASQUE           0x01
#define SUBLANG_BELARUSIAN_BELARUS      0x01
#define SUBLANG_BENGALI_INDIA           0x01
#define SUBLANG_BRETON_FRANCE           0x01
#define SUBLANG_BULGARIAN_BULGARIA      0x01
#define SUBLANG_CATALAN_CATALAN         0x01
#define SUBLANG_CENTRAL_KURDISH_IRAQ    0x01
#define SUBLANG_CHEROKEE_CHEROKEE       0x01
#define SUBLANG_CHINESE_TRADITIONAL     0x01
#define SUBLANG_CORSICAN_FRANCE         0x01
#define SUBLANG_CZECH_CZECH_REPUBLIC    0x01
#define SUBLANG_CROATIAN_CROATIA        0x01
#define SUBLANG_DANISH_DENMARK          0x01
#define SUBLANG_DARI_AFGHANISTAN        0x01
#define SUBLANG_DIVEHI_MALDIVES         0x01
#define SUBLANG_DUTCH                   0x01
#define SUBLANG_ENGLISH_US              0x01
#define SUBLANG_ESTONIAN_ESTONIA        0x01
#define SUBLANG_FAEROESE_FAROE_ISLANDS  0x01
#define SUBLANG_FILIPINO_PHILIPPINES    0x01
#define SUBLANG_FINNISH_FINLAND         0x01
#define SUBLANG_FRENCH                  0x01
#define SUBLANG_FRISIAN_NETHERLANDS     0x01
#define SUBLANG_GALICIAN_GALICIAN       0x01
#define SUBLANG_GEORGIAN_GEORGIA        0x01
#define SUBLANG_GERMAN                  0x01
#define SUBLANG_GREEK_GREECE            0x01
#define SUBLANG_GREENLANDIC_GREENLAND   0x01
#define SUBLANG_GUJARATI_INDIA          0x01
#define SUBLANG_HAUSA_NIGERIA_LATIN     0x01
#define SUBLANG_HAWAIIAN_US             0x01
#define SUBLANG_HEBREW_ISRAEL           0x01
#define SUBLANG_HINDI_INDIA             0x01
#define SUBLANG_HUNGARIAN_HUNGARY       0x01
#define SUBLANG_ICELANDIC_ICELAND       0x01
#define SUBLANG_IGBO_NIGERIA            0x01
#define SUBLANG_INDONESIAN_INDONESIA    0x01
#define SUBLANG_INUKTITUT_CANADA        0x01
#define SUBLANG_ITALIAN                 0x01
#define SUBLANG_JAPANESE_JAPAN          0x01
#define SUBLANG_KANNADA_INDIA           0x01
#define SUBLANG_KAZAK_KAZAKHSTAN        0x01
#define SUBLANG_KHMER_CAMBODIA          0x01
#define SUBLANG_KICHE_GUATEMALA         0x01
#define SUBLANG_KINYARWANDA_RWANDA      0x01
#define SUBLANG_KONKANI_INDIA           0x01
#define SUBLANG_KOREAN                  0x01
#define SUBLANG_KYRGYZ_KYRGYZSTAN       0x01
#define SUBLANG_LAO_LAO                 0x01
#define SUBLANG_LATVIAN_LATVIA          0x01
#define SUBLANG_LITHUANIAN              0x01
#define SUBLANG_LUXEMBOURGISH_LUXEMBOURG 0x01
#define SUBLANG_MACEDONIAN_MACEDONIA    0x01
#define SUBLANG_MALAY_MALAYSIA          0x01
#define SUBLANG_MALAYALAM_INDIA         0x01
#define SUBLANG_MALTESE_MALTA           0x01
#define SUBLANG_MAORI_NEW_ZEALAND       0x01
#define SUBLANG_MAPUDUNGUN_CHILE        0x01
#define SUBLANG_MARATHI_INDIA           0x01
#define SUBLANG_MOHAWK_MOHAWK           0x01
#define SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA 0x01
#define SUBLANG_NEPALI_NEPAL            0x01
#define SUBLANG_NORWEGIAN_BOKMAL        0x01
#define SUBLANG_OCCITAN_FRANCE          0x01
#define SUBLANG_ODIA_INDIA              0x01
#define SUBLANG_ORIYA_INDIA             0x01
#define SUBLANG_PASHTO_AFGHANISTAN      0x01
#define SUBLANG_PERSIAN_IRAN            0x01
#define SUBLANG_POLISH_POLAND           0x01
#define SUBLANG_PORTUGUESE_BRAZILIAN    0x01
#define SUBLANG_PUNJABI_INDIA           0x01
#define SUBLANG_QUECHUA_BOLIVIA         0x01
#define SUBLANG_ROMANIAN_ROMANIA        0x01
#define SUBLANG_ROMANSH_SWITZERLAND     0x01
#define SUBLANG_RUSSIAN_RUSSIA          0x01
#define SUBLANG_SAKHA_RUSSIA            0x01
#define SUBLANG_SAMI_NORTHERN_NORWAY    0x01
#define SUBLANG_SANSKRIT_INDIA          0x01
#define SUBLANG_SCOTTISH_GAELIC         0x01
#define SUBLANG_SERBIAN_CROATIA         0x01
#define SUBLANG_SINDHI_INDIA            0x01
#define SUBLANG_SINHALESE_SRI_LANKA     0x01
#define SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA 0x01
#define SUBLANG_SLOVAK_SLOVAKIA         0x01
#define SUBLANG_SLOVENIAN_SLOVENIA      0x01
#define SUBLANG_SPANISH                 0x01
#define SUBLANG_SWAHILI_KENYA           0x01
#define SUBLANG_SWEDISH                 0x01
#define SUBLANG_SYRIAC_SYRIA            0x01
#define SUBLANG_TAJIK_TAJIKISTAN        0x01
#define SUBLANG_TAMIL_INDIA             0x01
#define SUBLANG_TATAR_RUSSIA            0x01
#define SUBLANG_TELUGU_INDIA            0x01
#define SUBLANG_THAI_THAILAND           0x01
#define SUBLANG_TIBETAN_PRC             0x01
#define SUBLANG_TIGRINYA_ETHIOPIA       0x01
#define SUBLANG_TSWANA_SOUTH_AFRICA     0x01
#define SUBLANG_TURKISH_TURKEY          0x01
#define SUBLANG_TURKMEN_TURKMENISTAN    0x01
#define SUBLANG_UIGHUR_PRC              0x01
#define SUBLANG_UKRAINIAN_UKRAINE       0x01
#define SUBLANG_UPPER_SORBIAN_GERMANY   0x01
#define SUBLANG_URDU_PAKISTAN           0x01
#define SUBLANG_UZBEK_LATIN             0x01
#define SUBLANG_VIETNAMESE_VIETNAM      0x01
#define SUBLANG_WELSH_UNITED_KINGDOM    0x01
#define SUBLANG_WOLOF_SENEGAL           0x01
#define SUBLANG_XHOSA_SOUTH_AFRICA      0x01
#define SUBLANG_YAKUT_RUSSIA            0x01
#define SUBLANG_YI_PRC                  0x01
#define SUBLANG_YORUBA_NIGERIA          0x01
#define SUBLANG_ZULU_SOUTH_AFRICA       0x01
#define SORT_INVARIANT_MATH             0x1
#define SORT_JAPANESE_UNICODE           0x1
#define SORT_CHINESE_UNICODE            0x1
#define SORT_KOREAN_UNICODE             0x1
#define SORT_GERMAN_PHONE_BOOK          0x1
#define SORT_HUNGARIAN_TECHNICAL        0x1
#define SORT_GEORGIAN_MODERN            0x1
#define EXCEPTION_NONCONTINUABLE        0x1
#define SYSTEM_MANDATORY_LABEL_NO_WRITE_UP 0x1
#define ACE_OBJECT_TYPE_PRESENT         0x1
#define ACCESS_PROPERTY_SET_GUID        1
#define AUDIT_ALLOW_NO_PRIVILEGE        0x1
#define SE_SECURITY_DESCRIPTOR_FLAG_NO_OWNER_ACE 0x00000001
#define TOKEN_MANDATORY_POLICY_NO_WRITE_UP 0x1
#define CLAIM_SECURITY_ATTRIBUTE_TYPE_INT64 0x01
#define CLAIM_SECURITY_ATTRIBUTE_NON_INHERITABLE 0x0001
#define CLAIM_SECURITY_ATTRIBUTES_INFORMATION_VERSION_V1 1
#define DISABLE_MAX_PRIVILEGE           0x1
#define SE_LEARNING_MODE_FLAG_PERMISSIVE 0x00000001
#define QUOTA_LIMITS_HARDWS_MIN_ENABLE  0x00000001
#define THREAD_PROFILING_FLAG_DISPATCH  0x00000001
#define JOB_OBJECT_POST_AT_END_OF_JOB   1
#define JOB_OBJECT_MSG_END_OF_JOB_TIME  1
#define JOB_OBJECT_MSG_MINIMUM          1
#define JOB_OBJECT_LIMIT_WORKINGSET     0x00000001
#define JOB_OBJECT_UILIMIT_HANDLES      0x00000001
#define JOB_OBJECT_SECURITY_NO_ADMIN    0x00000001
#define JOB_OBJECT_CPU_RATE_CONTROL_ENABLE 0x1
#define MUTANT_QUERY_STATE              0x0001
#define TIMER_QUERY_STATE               0x0001
#define TIME_ZONE_ID_STANDARD           1
#define LTP_PC_SMT                      0x1
#define PROCESSOR_ARCHITECTURE_MIPS     1
#define PF_FLOATING_POINT_EMULATED      1
#define SECTION_QUERY                   0x0001
#define SESSION_QUERY_ACCESS            0x0001
#define PAGE_NOACCESS                   0x01
#define WRITE_WATCH_FLAG_RESET          0x01
#define DS_ABSALIGN         0x01L
#define DS_SYSMODAL         0x02L
#define DS_LOCALEDIT        0x20L   /* Edit items get Local storage. */
#define DS_SETFONT          0x40L   /* User specified font for Dlg controls */
#define DS_MODALFRAME       0x80L   /* Can be combined with WS_CAPTION  */
#define DS_NOIDLEMSG        0x100L  /* WM_ENTERIDLE message will not be sent */
#define DS_SETFOREGROUND    0x200L  /* not in win3.1 */
#define DS_3DLOOK           0x0004L
#define DS_FIXEDSYS         0x0008L
#define DS_NOFAILCREATE     0x0010L
#define DS_CONTROL          0x0400L
#define DS_CENTER           0x0800L
#define DS_CENTERMOUSE      0x1000L
#define DS_CONTEXTHELP      0x2000L
#define WS_OVERLAPPED       0x00000000L
#define WS_POPUP            0x80000000L
#define WS_CHILD            0x40000000L
#define WS_MINIMIZE         0x20000000L
#define WS_VISIBLE          0x10000000L
#define WS_DISABLED         0x08000000L
#define WS_CLIPSIBLINGS     0x04000000L
#define WS_CLIPCHILDREN     0x02000000L
#define WS_MAXIMIZE         0x01000000L
#define WS_CAPTION          0x00C00000L     /* WS_BORDER | WS_DLGFRAME  */
#define WS_BORDER           0x00800000L
#define WS_DLGFRAME         0x00400000L
#define WS_VSCROLL          0x00200000L
#define WS_HSCROLL          0x00100000L
#define WS_SYSMENU          0x00080000L
#define WS_THICKFRAME       0x00040000L
#define WS_GROUP            0x00020000L
#define WS_TABSTOP          0x00010000L

#define WS_MINIMIZEBOX      0x00020000L
#define WS_MAXIMIZEBOX      0x00010000L


#define WS_TILED            WS_OVERLAPPED
#define WS_ICONIC           WS_MINIMIZE
#define WS_SIZEBOX          WS_THICKFRAME
#define WS_TILEDWINDOW      WS_OVERLAPPEDWINDOW

/*
* Common Window Styles
*/
#define WS_OVERLAPPEDWINDOW (WS_OVERLAPPED     | \
                             WS_CAPTION        | \
                             WS_SYSMENU        | \
                             WS_THICKFRAME     | \
                             WS_MINIMIZEBOX    | \
                             WS_MAXIMIZEBOX)

#define WS_POPUPWINDOW      (WS_POPUP          | \
                             WS_BORDER         | \
                             WS_SYSMENU)

#define WS_CHILDWINDOW      (WS_CHILD)
#define ES_LEFT             0x0000L
#define ES_CENTER           0x0001L
#define ES_RIGHT            0x0002L
#define ES_MULTILINE        0x0004L
#define ES_UPPERCASE        0x0008L
#define ES_LOWERCASE        0x0010L
#define ES_PASSWORD         0x0020L
#define ES_AUTOVSCROLL      0x0040L
#define ES_AUTOHSCROLL      0x0080L
#define ES_NOHIDESEL        0x0100L
#define ES_OEMCONVERT       0x0400L
#define ES_READONLY         0x0800L
#define ES_WANTRETURN       0x1000L
#if(WINVER >= 0x0400)
#define ES_NUMBER           0x2000L
#endif /* WINVER >= 0x0400 */
#define IDOK                1
#define IDCANCEL            2
#define IDABORT             3
#define IDRETRY             4
#define IDIGNORE            5
#define IDYES               6
#define IDNO                7
#define IDC_STATIC						-1
#define IDD_CRASHHANDLER                101
#define IDC_COPY                        1000
#define IDC_EDIT1                       1001
#define IDC_STACK                       1001
#define IDC_ERRORICON                   1002
#define IDC_BREAK						1003
#define IDC_DUMP						1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
