// This file has been autogenerated by the Type Info Generator

#pragma warning(disable : 4189)
#pragma warning(disable : 4505)
#include "../../idlib/precompiled.h"
#include "../Gamelib/Game_local.h"
void idForce::Save(idSaveGame* savefile) const {
	idClass::Save(savefile);
}

void idForce::Restore(idRestoreGame* savefile) {
	idClass::Restore(savefile);
}

void idForce_Constant::Save(idSaveGame* savefile) const {
	idForce::Save(savefile);
}

void idForce_Constant::Restore(idRestoreGame* savefile) {
	idForce::Restore(savefile);
}

void idForce_Drag::Save(idSaveGame* savefile) const {
	idForce::Save(savefile);
}

void idForce_Drag::Restore(idRestoreGame* savefile) {
	idForce::Restore(savefile);
}

void idForce_Grab::Save(idSaveGame* savefile) const {
	idForce::Save(savefile);
}

void idForce_Grab::Restore(idRestoreGame* savefile) {
	idForce::Restore(savefile);
}

void idForce_Field::Save(idSaveGame* savefile) const {
	idForce::Save(savefile);
}

void idForce_Field::Restore(idRestoreGame* savefile) {
	idForce::Restore(savefile);
}

void idForce_Spring::Save(idSaveGame* savefile) const {
	idForce::Save(savefile);
}

void idForce_Spring::Restore(idRestoreGame* savefile) {
	idForce::Restore(savefile);
}

void idPhysics_Static::Save(idSaveGame* savefile) const {
	idPhysics::Save(savefile);
}

void idPhysics_Static::Restore(idRestoreGame* savefile) {
	idPhysics::Restore(savefile);
}

void idPhysics_StaticMulti::Save(idSaveGame* savefile) const {
	idPhysics::Save(savefile);
}

void idPhysics_StaticMulti::Restore(idRestoreGame* savefile) {
	idPhysics::Restore(savefile);
}

void idPhysics_Base::Save(idSaveGame* savefile) const {
	idPhysics::Save(savefile);
}

void idPhysics_Base::Restore(idRestoreGame* savefile) {
	idPhysics::Restore(savefile);
}

void idPhysics_Actor::Save(idSaveGame* savefile) const {
	idPhysics_Base::Save(savefile);
}

void idPhysics_Actor::Restore(idRestoreGame* savefile) {
	idPhysics_Base::Restore(savefile);
}

void idPhysics_Monster::Save(idSaveGame* savefile) const {
	idPhysics_Actor::Save(savefile);
}

void idPhysics_Monster::Restore(idRestoreGame* savefile) {
	idPhysics_Actor::Restore(savefile);
}

void idPhysics_Player::Save(idSaveGame* savefile) const {
	idPhysics_Actor::Save(savefile);
}

void idPhysics_Player::Restore(idRestoreGame* savefile) {
	idPhysics_Actor::Restore(savefile);
}

void idPhysics_Parametric::Save(idSaveGame* savefile) const {
	idPhysics_Base::Save(savefile);
}

void idPhysics_Parametric::Restore(idRestoreGame* savefile) {
	idPhysics_Base::Restore(savefile);
}

void idPhysics_RigidBody::Save(idSaveGame* savefile) const {
	idPhysics_Base::Save(savefile);
}

void idPhysics_RigidBody::Restore(idRestoreGame* savefile) {
	idPhysics_Base::Restore(savefile);
}

void idPhysics_AF::Save(idSaveGame* savefile) const {
	idPhysics_Base::Save(savefile);
}

void idPhysics_AF::Restore(idRestoreGame* savefile) {
	idPhysics_Base::Restore(savefile);
}

void idAnimatedEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idAnimatedEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idCursor3D::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idCursor3D::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idMultiModelAF::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idMultiModelAF::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idChain::Save(idSaveGame* savefile) const {
	idMultiModelAF::Save(savefile);
}

void idChain::Restore(idRestoreGame* savefile) {
	idMultiModelAF::Restore(savefile);
}

void idAFAttachment::Save(idSaveGame* savefile) const {
	idAnimatedEntity::Save(savefile);
}

void idAFAttachment::Restore(idRestoreGame* savefile) {
	idAnimatedEntity::Restore(savefile);
}

void idAFEntity_Base::Save(idSaveGame* savefile) const {
	idAnimatedEntity::Save(savefile);
}

void idAFEntity_Base::Restore(idRestoreGame* savefile) {
	idAnimatedEntity::Restore(savefile);
}

void idAFEntity_Gibbable::Save(idSaveGame* savefile) const {
	idAFEntity_Base::Save(savefile);
}

void idAFEntity_Gibbable::Restore(idRestoreGame* savefile) {
	idAFEntity_Base::Restore(savefile);
}

void idAFEntity_Generic::Save(idSaveGame* savefile) const {
	idAFEntity_Gibbable::Save(savefile);
}

void idAFEntity_Generic::Restore(idRestoreGame* savefile) {
	idAFEntity_Gibbable::Restore(savefile);
}

void idAFEntity_WithAttachedHead::Save(idSaveGame* savefile) const {
	idAFEntity_Gibbable::Save(savefile);
}

void idAFEntity_WithAttachedHead::Restore(idRestoreGame* savefile) {
	idAFEntity_Gibbable::Restore(savefile);
}

void idAFEntity_Vehicle::Save(idSaveGame* savefile) const {
	idAFEntity_Base::Save(savefile);
}

void idAFEntity_Vehicle::Restore(idRestoreGame* savefile) {
	idAFEntity_Base::Restore(savefile);
}

void idAFEntity_VehicleSimple::Save(idSaveGame* savefile) const {
	idAFEntity_Vehicle::Save(savefile);
}

void idAFEntity_VehicleSimple::Restore(idRestoreGame* savefile) {
	idAFEntity_Vehicle::Restore(savefile);
}

void idAFEntity_VehicleFourWheels::Save(idSaveGame* savefile) const {
	idAFEntity_Vehicle::Save(savefile);
}

void idAFEntity_VehicleFourWheels::Restore(idRestoreGame* savefile) {
	idAFEntity_Vehicle::Restore(savefile);
}

void idAFEntity_VehicleSixWheels::Save(idSaveGame* savefile) const {
	idAFEntity_Vehicle::Save(savefile);
}

void idAFEntity_VehicleSixWheels::Restore(idRestoreGame* savefile) {
	idAFEntity_Vehicle::Restore(savefile);
}

void idAFEntity_VehicleAutomated::Save(idSaveGame* savefile) const {
	idAFEntity_VehicleSixWheels::Save(savefile);
}

void idAFEntity_VehicleAutomated::Restore(idRestoreGame* savefile) {
	idAFEntity_VehicleSixWheels::Restore(savefile);
}

void idAFEntity_SteamPipe::Save(idSaveGame* savefile) const {
	idAFEntity_Base::Save(savefile);
}

void idAFEntity_SteamPipe::Restore(idRestoreGame* savefile) {
	idAFEntity_Base::Restore(savefile);
}

void idAFEntity_ClawFourFingers::Save(idSaveGame* savefile) const {
	idAFEntity_Base::Save(savefile);
}

void idAFEntity_ClawFourFingers::Restore(idRestoreGame* savefile) {
	idAFEntity_Base::Restore(savefile);
}

void idHarvestable::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idHarvestable::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idAFEntity_Harvest::Save(idSaveGame* savefile) const {
	idAFEntity_WithAttachedHead::Save(savefile);
}

void idAFEntity_Harvest::Restore(idRestoreGame* savefile) {
	idAFEntity_WithAttachedHead::Restore(savefile);
}

void idSpawnableEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idSpawnableEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idPlayerStart::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idPlayerStart::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idActivator::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idActivator::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idPathCorner::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idPathCorner::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idDamagable::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idDamagable::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idExplodable::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idExplodable::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idSpring::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idSpring::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idForceField::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idForceField::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idAnimated::Save(idSaveGame* savefile) const {
	idAFEntity_Gibbable::Save(savefile);
}

void idAnimated::Restore(idRestoreGame* savefile) {
	idAFEntity_Gibbable::Restore(savefile);
}

void idStaticEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idStaticEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idFuncEmitter::Save(idSaveGame* savefile) const {
	idStaticEntity::Save(savefile);
}

void idFuncEmitter::Restore(idRestoreGame* savefile) {
	idStaticEntity::Restore(savefile);
}

void idFuncSmoke::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idFuncSmoke::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idFuncSplat::Save(idSaveGame* savefile) const {
	idFuncEmitter::Save(savefile);
}

void idFuncSplat::Restore(idRestoreGame* savefile) {
	idFuncEmitter::Restore(savefile);
}

void idTextEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idTextEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idLocationEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idLocationEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idLocationSeparatorEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idLocationSeparatorEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idVacuumSeparatorEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idVacuumSeparatorEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idVacuumEntity::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idVacuumEntity::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idBeam::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idBeam::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idLiquid::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idLiquid::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idShaking::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idShaking::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idEarthQuake::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idEarthQuake::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idFuncPortal::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idFuncPortal::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idFuncRadioChatter::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idFuncRadioChatter::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idShockwave::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idShockwave::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idFuncMountedObject::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idFuncMountedObject::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idFuncMountedWeapon::Save(idSaveGame* savefile) const {
	idFuncMountedObject::Save(savefile);
}

void idFuncMountedWeapon::Restore(idRestoreGame* savefile) {
	idFuncMountedObject::Restore(savefile);
}

void idPortalSky::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idPortalSky::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idActor::Save(idSaveGame* savefile) const {
	idAFEntity_Gibbable::Save(savefile);
}

void idActor::Restore(idRestoreGame* savefile) {
	idAFEntity_Gibbable::Restore(savefile);
}

void idProjectile::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idProjectile::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idGuidedProjectile::Save(idSaveGame* savefile) const {
	idProjectile::Save(savefile);
}

void idGuidedProjectile::Restore(idRestoreGame* savefile) {
	idProjectile::Restore(savefile);
}

void idSoulCubeMissile::Save(idSaveGame* savefile) const {
	idGuidedProjectile::Save(savefile);
}

void idSoulCubeMissile::Restore(idRestoreGame* savefile) {
	idGuidedProjectile::Restore(savefile);
}

void idBFGProjectile::Save(idSaveGame* savefile) const {
	idProjectile::Save(savefile);
}

void idBFGProjectile::Restore(idRestoreGame* savefile) {
	idProjectile::Restore(savefile);
}

void idHomingProjectile::Save(idSaveGame* savefile) const {
	idProjectile::Save(savefile);
}

void idHomingProjectile::Restore(idRestoreGame* savefile) {
	idProjectile::Restore(savefile);
}

void idDebris::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idDebris::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void rvmWeaponObject::Save(idSaveGame* savefile) const {
	idClass::Save(savefile);
}

void rvmWeaponObject::Restore(idRestoreGame* savefile) {
	idClass::Restore(savefile);
}

void idWeapon::Save(idSaveGame* savefile) const {
	idAnimatedEntity::Save(savefile);
}

void idWeapon::Restore(idRestoreGame* savefile) {
	idAnimatedEntity::Restore(savefile);
}

void idLight::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idLight::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idWorldspawn::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idWorldspawn::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idItem::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idItem::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idItemPowerup::Save(idSaveGame* savefile) const {
	idItem::Save(savefile);
}

void idItemPowerup::Restore(idRestoreGame* savefile) {
	idItem::Restore(savefile);
}

void idObjective::Save(idSaveGame* savefile) const {
	idItem::Save(savefile);
}

void idObjective::Restore(idRestoreGame* savefile) {
	idItem::Restore(savefile);
}

void idVideoCDItem::Save(idSaveGame* savefile) const {
	idItem::Save(savefile);
}

void idVideoCDItem::Restore(idRestoreGame* savefile) {
	idItem::Restore(savefile);
}

void idPDAItem::Save(idSaveGame* savefile) const {
	idItem::Save(savefile);
}

void idPDAItem::Restore(idRestoreGame* savefile) {
	idItem::Restore(savefile);
}

void idMoveableItem::Save(idSaveGame* savefile) const {
	idItem::Save(savefile);
}

void idMoveableItem::Restore(idRestoreGame* savefile) {
	idItem::Restore(savefile);
}

void idItemTeam::Save(idSaveGame* savefile) const {
	idMoveableItem::Save(savefile);
}

void idItemTeam::Restore(idRestoreGame* savefile) {
	idMoveableItem::Restore(savefile);
}

void idMoveablePDAItem::Save(idSaveGame* savefile) const {
	idMoveableItem::Save(savefile);
}

void idMoveablePDAItem::Restore(idRestoreGame* savefile) {
	idMoveableItem::Restore(savefile);
}

void idItemRemover::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idItemRemover::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idObjectiveComplete::Save(idSaveGame* savefile) const {
	idItemRemover::Save(savefile);
}

void idObjectiveComplete::Restore(idRestoreGame* savefile) {
	idItemRemover::Restore(savefile);
}

void idPlayer::Save(idSaveGame* savefile) const {
	idActor::Save(savefile);
}

void idPlayer::Restore(idRestoreGame* savefile) {
	idActor::Restore(savefile);
}

void idMover::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idMover::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idSplinePath::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idSplinePath::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idElevator::Save(idSaveGame* savefile) const {
	idMover::Save(savefile);
}

void idElevator::Restore(idRestoreGame* savefile) {
	idMover::Restore(savefile);
}

void idMover_Binary::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idMover_Binary::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idDoor::Save(idSaveGame* savefile) const {
	idMover_Binary::Save(savefile);
}

void idDoor::Restore(idRestoreGame* savefile) {
	idMover_Binary::Restore(savefile);
}

void idPlat::Save(idSaveGame* savefile) const {
	idMover_Binary::Save(savefile);
}

void idPlat::Restore(idRestoreGame* savefile) {
	idMover_Binary::Restore(savefile);
}

void idMover_Periodic::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idMover_Periodic::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idRotater::Save(idSaveGame* savefile) const {
	idMover_Periodic::Save(savefile);
}

void idRotater::Restore(idRestoreGame* savefile) {
	idMover_Periodic::Restore(savefile);
}

void idBobber::Save(idSaveGame* savefile) const {
	idMover_Periodic::Save(savefile);
}

void idBobber::Restore(idRestoreGame* savefile) {
	idMover_Periodic::Restore(savefile);
}

void idPendulum::Save(idSaveGame* savefile) const {
	idMover_Periodic::Save(savefile);
}

void idPendulum::Restore(idRestoreGame* savefile) {
	idMover_Periodic::Restore(savefile);
}

void idRiser::Save(idSaveGame* savefile) const {
	idMover_Periodic::Save(savefile);
}

void idRiser::Restore(idRestoreGame* savefile) {
	idMover_Periodic::Restore(savefile);
}

void idCameraView::Save(idSaveGame* savefile) const {
	idCamera::Save(savefile);
}

void idCameraView::Restore(idRestoreGame* savefile) {
	idCamera::Restore(savefile);
}

void idCameraAnim::Save(idSaveGame* savefile) const {
	idCamera::Save(savefile);
}

void idCameraAnim::Restore(idRestoreGame* savefile) {
	idCamera::Restore(savefile);
}

void idMoveable::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idMoveable::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idBarrel::Save(idSaveGame* savefile) const {
	idMoveable::Save(savefile);
}

void idBarrel::Restore(idRestoreGame* savefile) {
	idMoveable::Restore(savefile);
}

void idExplodingBarrel::Save(idSaveGame* savefile) const {
	idBarrel::Save(savefile);
}

void idExplodingBarrel::Restore(idRestoreGame* savefile) {
	idBarrel::Restore(savefile);
}

void idTarget::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idTarget::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idTarget_Remove::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_Remove::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_Show::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_Show::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_Damage::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_Damage::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SessionCommand::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SessionCommand::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_EndLevel::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_EndLevel::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_WaitForButton::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_WaitForButton::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetGlobalShaderTime::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetGlobalShaderTime::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetShaderParm::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetShaderParm::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetShaderTime::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetShaderTime::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_FadeEntity::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_FadeEntity::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_LightFadeIn::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_LightFadeIn::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_LightFadeOut::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_LightFadeOut::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_Give::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_Give::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_GiveEmail::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_GiveEmail::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetModel::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetModel::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetInfluence::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetInfluence::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetKeyVal::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetKeyVal::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetFov::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetFov::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_SetPrimaryObjective::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_SetPrimaryObjective::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_LockDoor::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_LockDoor::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_CallObjectFunction::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_CallObjectFunction::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_EnableLevelWeapons::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_EnableLevelWeapons::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_Tip::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_Tip::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_GiveSecurity::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_GiveSecurity::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_RemoveWeapons::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_RemoveWeapons::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_LevelTrigger::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_LevelTrigger::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_EnableStamina::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_EnableStamina::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTarget_FadeSoundClass::Save(idSaveGame* savefile) const {
	idTarget::Save(savefile);
}

void idTarget_FadeSoundClass::Restore(idRestoreGame* savefile) {
	idTarget::Restore(savefile);
}

void idTrigger::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idTrigger::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idTrigger_Multi::Save(idSaveGame* savefile) const {
	idTrigger::Save(savefile);
}

void idTrigger_Multi::Restore(idRestoreGame* savefile) {
	idTrigger::Restore(savefile);
}

void idTrigger_EntityName::Save(idSaveGame* savefile) const {
	idTrigger::Save(savefile);
}

void idTrigger_EntityName::Restore(idRestoreGame* savefile) {
	idTrigger::Restore(savefile);
}

void idTrigger_Timer::Save(idSaveGame* savefile) const {
	idTrigger::Save(savefile);
}

void idTrigger_Timer::Restore(idRestoreGame* savefile) {
	idTrigger::Restore(savefile);
}

void idTrigger_Count::Save(idSaveGame* savefile) const {
	idTrigger::Save(savefile);
}

void idTrigger_Count::Restore(idRestoreGame* savefile) {
	idTrigger::Restore(savefile);
}

void idTrigger_Hurt::Save(idSaveGame* savefile) const {
	idTrigger::Save(savefile);
}

void idTrigger_Hurt::Restore(idRestoreGame* savefile) {
	idTrigger::Restore(savefile);
}

void idTrigger_Fade::Save(idSaveGame* savefile) const {
	idTrigger::Save(savefile);
}

void idTrigger_Fade::Restore(idRestoreGame* savefile) {
	idTrigger::Restore(savefile);
}

void idTrigger_Touch::Save(idSaveGame* savefile) const {
	idTrigger::Save(savefile);
}

void idTrigger_Touch::Restore(idRestoreGame* savefile) {
	idTrigger::Restore(savefile);
}

void idTrigger_Flag::Save(idSaveGame* savefile) const {
	idTrigger_Multi::Save(savefile);
}

void idTrigger_Flag::Restore(idRestoreGame* savefile) {
	idTrigger_Multi::Restore(savefile);
}

void idSound::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idSound::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idEntityFx::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idEntityFx::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idTeleporter::Save(idSaveGame* savefile) const {
	idEntityFx::Save(savefile);
}

void idTeleporter::Restore(idRestoreGame* savefile) {
	idEntityFx::Restore(savefile);
}

void idSecurityCamera::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idSecurityCamera::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void idBrittleFracture::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void idBrittleFracture::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void dnWeaponMightyFoot::Save(idSaveGame* savefile) const {
	rvmWeaponObject::Save(savefile);
}

void dnWeaponMightyFoot::Restore(idRestoreGame* savefile) {
	rvmWeaponObject::Restore(savefile);
}

void dnWeaponPistol::Save(idSaveGame* savefile) const {
	rvmWeaponObject::Save(savefile);
}

void dnWeaponPistol::Restore(idRestoreGame* savefile) {
	rvmWeaponObject::Restore(savefile);
}

void dnWeaponShotgun::Save(idSaveGame* savefile) const {
	rvmWeaponObject::Save(savefile);
}

void dnWeaponShotgun::Restore(idRestoreGame* savefile) {
	rvmWeaponObject::Restore(savefile);
}

void dnWeaponM16::Save(idSaveGame* savefile) const {
	rvmWeaponObject::Save(savefile);
}

void dnWeaponM16::Restore(idRestoreGame* savefile) {
	rvmWeaponObject::Restore(savefile);
}

void DnItem::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void DnItem::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void DnItemShotgun::Save(idSaveGame* savefile) const {
	DnItem::Save(savefile);
}

void DnItemShotgun::Restore(idRestoreGame* savefile) {
	DnItem::Restore(savefile);
}

void idTestModel::Save(idSaveGame* savefile) const {
	idAnimatedEntity::Save(savefile);
}

void idTestModel::Restore(idRestoreGame* savefile) {
	idAnimatedEntity::Restore(savefile);
}

void DnAI::Save(idSaveGame* savefile) const {
	idActor::Save(savefile);
}

void DnAI::Restore(idRestoreGame* savefile) {
	idActor::Restore(savefile);
}

void DnPigcop::Save(idSaveGame* savefile) const {
	DnAI::Save(savefile);
}

void DnPigcop::Restore(idRestoreGame* savefile) {
	DnAI::Restore(savefile);
}

void DnLiztroop::Save(idSaveGame* savefile) const {
	DnAI::Save(savefile);
}

void DnLiztroop::Restore(idRestoreGame* savefile) {
	DnAI::Restore(savefile);
}

void DnCivilian::Save(idSaveGame* savefile) const {
	DnAI::Save(savefile);
}

void DnCivilian::Restore(idRestoreGame* savefile) {
	DnAI::Restore(savefile);
}

void DukePlayer::Save(idSaveGame* savefile) const {
	idPlayer::Save(savefile);
}

void DukePlayer::Restore(idRestoreGame* savefile) {
	idPlayer::Restore(savefile);
}

void dnDecoration::Save(idSaveGame* savefile) const {
	idMover::Save(savefile);
}

void dnDecoration::Restore(idRestoreGame* savefile) {
	idMover::Restore(savefile);
}

void rvClientPhysics::Save(idSaveGame* savefile) const {
	idEntity::Save(savefile);
}

void rvClientPhysics::Restore(idRestoreGame* savefile) {
	idEntity::Restore(savefile);
}

void rvClientModel::Save(idSaveGame* savefile) const {
	rvClientEntity::Save(savefile);
}

void rvClientModel::Restore(idRestoreGame* savefile) {
	rvClientEntity::Restore(savefile);
}

void rvAnimatedClientEntity::Save(idSaveGame* savefile) const {
	rvClientModel::Save(savefile);
}

void rvAnimatedClientEntity::Restore(idRestoreGame* savefile) {
	rvClientModel::Restore(savefile);
}

void rvClientMoveable::Save(idSaveGame* savefile) const {
	rvClientEntity::Save(savefile);
}

void rvClientMoveable::Restore(idRestoreGame* savefile) {
	rvClientEntity::Restore(savefile);
}

void rvClientAFEntity::Save(idSaveGame* savefile) const {
	rvAnimatedClientEntity::Save(savefile);
}

void rvClientAFEntity::Restore(idRestoreGame* savefile) {
	rvAnimatedClientEntity::Restore(savefile);
}

void rvClientAFAttachment::Save(idSaveGame* savefile) const {
	rvClientAFEntity::Save(savefile);
}

void rvClientAFAttachment::Restore(idRestoreGame* savefile) {
	rvClientAFEntity::Restore(savefile);
}

