
call gradlew assembleRelease -Dorg.gradle.java.home=E:\devinst\java11 -Pabifilters=arm64-v8a -Pcmake_options=-DGAME_DOOM3=ON,-DGAME_RTCW=OFF,-DGAME_QUAKE3=OFF,-DGAME_QUAKE2=OFF,-DGAME_QUAKE1=OFF,-DGAME_TDM=OFF,-DGAME_DOOM3BFG=OFF,-DGAME_DOOM=OFF,-DGAME_ETW=OFF,-DGAME_REALRTCW=OFF,-DGAME_FTEQW=OFF,-DGAME_JK=OFF,-DGAME_SERIOUSSAM=OFF,-DGAME_REALRTCW=OFF,-DGAME_SOURCE=OFF,-DGAME_XASH3D=OFF,-DBUILD_D3_MOD=OFF,-DBUILD_Q4=OFF,-DBUILD_PREY=OFF,-DBUILD_Q4_MOD=OFF

pause;
