
// liquid
GLSL_SHADER const char ES3_LIQUID_FRAG[] =
"#version 300 es\n"
"\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"// per-pixel reflection-refraction liquid\n"
"in vec4 var_TexCoord0; // texCoord[0] is the normal map texcoord\n"
"in highp vec4 var_TexCoord1; // texCoord[1] is the vector to the eye in global space //karin: must high precison on GLSL\n"
"in vec4 var_TexCoord2; // texCoord[2] is the surface tangent to global coordiantes\n"
"in vec4 var_TexCoord3; // texCoord[3] is the surface bitangent to global coordiantes\n"
"in vec4 var_TexCoord4; // texCoord[4] is the surface normal to global coordiantes\n"
"in vec4 var_TexCoord6; // texCoord[6] is the copied deform magnitude\n"
"//in vec4 var_TexCoord7; // texCoord[7] is the copied scroll\n"
"\n"
"uniform highp vec4 u_nonPowerOfTwo; // env[0] is the 1.0 to _currentRender conversion\n"
"uniform highp vec4 u_windowCoords; // env[1] is the fragment.position to 0.0 - 1.0 conversion\n"
"uniform vec4 u_fragmentParm0; // scroll\n"
"uniform vec4 u_fragmentParm1; // deform magnitude (1.0 is reasonable, 2.0 is twice as wavy, 0.5 is half as wavy, etc)\n"
"uniform vec4 u_fragmentParm2; // refract color\n"
"uniform vec4 u_fragmentParm3; // reflect color\n"
"\n"
"uniform samplerCube u_fragmentCubeMap0; // texture 0 is the environment cube map\n"
"uniform sampler2D u_fragmentMap1; // texture 1 is the normal map\n"
"uniform sampler2D u_fragmentMap2; // texture 2 is _currentRender\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec4 scroll = u_fragmentParm3;\n"
"\n"
"    const float scaleTwo = 2.0;\n"
"\n"
"    // load the filtered normal map, then normalize to full scale,\n"
"    vec4 R0 = 0.02 * scroll + var_TexCoord0;\n"
"    R0 = 0.9 * R0;\n"
"    vec4 localNormal = texture(u_fragmentMap1, R0.st);\n"
"\n"
"    R0 = 0.1 * scroll.zyxy + var_TexCoord0;\n"
"    R0 = 0.125 * R0;\n"
"    R0 = texture(u_fragmentMap1, R0.st);\n"
"    localNormal = R0 + localNormal;\n"
"\n"
"    R0 = -0.17 * scroll.wxxy + var_TexCoord0;\n"
"    R0 = 0.5 * R0;\n"
"    R0 = texture(u_fragmentMap1, R0.st);\n"
"    localNormal = R0 + localNormal;\n"
"\n"
"    R0 = 0.2 * scroll.wwxy + var_TexCoord0;\n"
"    R0 = 0.25 * R0;\n"
"    R0 = texture(u_fragmentMap1, R0.st);\n"
"    localNormal = R0 + localNormal;\n"
"\n"
"    localNormal = localNormal.agbr * scaleTwo - 4.0;\n"
"    localNormal.xy = localNormal.xy * 1.5;\n"
"\n"
"    // transform the surface normal by the local tangent space\n"
"    vec4 globalNormal;\n"
"    globalNormal.x = dot(localNormal.xyz, var_TexCoord2.xyz);\n"
"    globalNormal.y = dot(localNormal.xyz, var_TexCoord3.xyz);\n"
"    globalNormal.z = dot(localNormal.xyz, var_TexCoord4.xyz);\n"
"    globalNormal.w = 1.0;\n"
"\n"
"    // normalize\n"
"    vec4 R1;\n"
"    R1.x = dot(globalNormal.xyz, globalNormal.xyz);\n"
"    R1.x = 1.0 / sqrt(R1.x);\n"
"    globalNormal.xyz = (globalNormal * R1.x).xyz;\n"
"\n"
"    // normalize vector to eye\n"
"    highp float R0_x = dot(var_TexCoord1.xyz, var_TexCoord1.xyz); //karin: must high precison on GLSL\n"
"    R0_x = 1.0 / sqrt(R0_x);\n"
"    vec4 globalEye = var_TexCoord1 * R0_x;\n"
"\n"
"    // calculate reflection vector\n"
"    R1 = vec4(dot(globalEye.xyz, globalNormal.xyz));\n"
"    R0 = R1 * globalNormal;\n"
"    R0 = R0 * scaleTwo - globalEye;\n"
"\n"
"    // read the environment map with the reflection vector\n"
"    R0 = texture(u_fragmentCubeMap0, R0.xyz);\n"
"\n"
"    // calculate fresnel\n"
"    vec4 fresnel = vec4(1.0 - R1); // 1 - V dot N\n"
"    fresnel = vec4(pow(fresnel.x, u_fragmentParm0.x)); // assume index is 1\n"
"    fresnel = fresnel * u_fragmentParm0.y + u_fragmentParm0.z;\n"
"\n"
"    // calculate the screen texcoord in the 0.0 to 1.0 range\n"
"    R1 = gl_FragCoord * u_windowCoords;\n"
"\n"
"    // offset by the scaled globalNormal and clamp it to 0.0 - 1.0\n"
"    R1 = clamp(globalNormal * var_TexCoord6 + R1, 0.0, 1.0);\n"
"\n"
"    // scale by the screen non-power-of-two-adjust\n"
"    R1 = R1 * u_nonPowerOfTwo;\n"
"\n"
"    // load the screen render\n"
"    R1 = texture(u_fragmentMap2, R1.st);\n"
"\n"
"    R1 = R1 * u_fragmentParm1;\n"
"    R0 = R0 * u_fragmentParm2;\n"
"\n"
"    vec3 color = mix(R1, R0, fresnel).xyz; // lerp refract and reflect\n"
"\n"
"    _gl_FragColor = vec4(color, 1.0);\n"
"}\n"
;
