
// membrane
GLSL_SHADER const char ES3_MEMBRANE_FRAG[] =
"#version 300 es\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform highp vec4 u_nonPowerOfTwo; // env[0] is the 1.0 to _currentRender conversion\n"
"uniform highp vec4 u_windowCoords; // env[1] is the fragment.position to 0.0 - 1.0 conversion\n"
"\n"
"uniform vec4 u_fragmentParm0;\n"
"uniform vec4 u_fragmentParm1;\n"
"uniform vec4 u_fragmentParm2;\n"
"\n"
"uniform sampler2D u_fragmentMap1; // texture 1 is the normal map\n"
"uniform sampler2D u_fragmentMap2; // texture 2 is _currentRender\n"
"uniform sampler2D u_fragmentMap3;\n"
"uniform sampler2D u_fragmentMap4;\n"
"\n"
"in vec4 var_TexCoord0; // texCoord[0] is the normal map texcoord\n"
"in highp vec4 var_TexCoord1; // texCoord[1] is the vector to the eye in global space //karin: must high precison on GLSL\n"
"in vec4 var_TexCoord2; // texCoord[2] is the surface tangent to global coordiantes\n"
"in vec4 var_TexCoord3; // texCoord[3] is the surface bitangent to global coordiantes\n"
"in vec4 var_TexCoord4; // texCoord[4] is the surface normal to global coordiantes\n"
"in vec4 var_TexCoord6; // texCoord[6] is the copied deform magnitude\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    const float subOne = -1.0;\n"
"    const float scaleTwo = 2.0;\n"
"    // load the filtered normal map, then normalize to full scale,\n"
"    vec4 localNormal = texture(u_fragmentMap1, var_TexCoord0.st);\n"
"    localNormal = localNormal.wyzx * scaleTwo + subOne;\n"
"    // transform the surface normal by the local tangent space\n"
"    vec4 globalNormal;\n"
"    globalNormal.x = dot(localNormal, var_TexCoord2);\n"
"    globalNormal.y = dot(localNormal, var_TexCoord3);\n"
"    globalNormal.z = dot(localNormal, var_TexCoord4);\n"
"    // normalize\n"
"    vec4 R1;\n"
"    R1.x = dot(globalNormal, globalNormal);\n"
"    R1.x = 1.0 / sqrt(R1.x);\n"
"    globalNormal.xyz = (globalNormal * R1.x).xyz;\n"
"    // normalize vector to eye\n"
"    highp float R0_x = dot(var_TexCoord1.xyz, var_TexCoord1.xyz); //karin: must high precison on GLSL\n"
"    R0_x = 1.0 / sqrt(R0_x);\n"
"    vec4 globalEye = var_TexCoord1 * R0_x;\n"
"    // calculate fresnel\n"
"    R1 = vec4(dot(globalEye, globalNormal));\n"
"    globalEye = 1.0 - R1;\n"
"    // 1 - V dot N\n"
"    globalEye = vec4(pow(globalEye.x, u_fragmentParm2.x));\n"
"    // assume index is 1\n"
"    // calculate the screen texcoord in the 0.0 to 1.0 range\n"
"    R1 = gl_FragCoord * u_windowCoords;\n"
"    // offset by the scaled globalNormal and clamp it to 0.0 - 1.0\n"
"    R1 = clamp(globalNormal * var_TexCoord6 + R1, 0.0, 1.0);\n"
"    // scale by the screen non-power-of-two-adjust\n"
"    R1 = R1 * u_nonPowerOfTwo;\n"
"    // load the screen render\n"
"    vec4 screen = texture(u_fragmentMap2, R1.st);\n"
"    vec4 R0 = texture(u_fragmentMap3, var_TexCoord0.st);\n"
"    R0 = R0 * u_fragmentParm0;\n"
"    R1 = texture(u_fragmentMap4, var_TexCoord0.st);\n"
"    R1 = R1 * u_fragmentParm1;\n"
"    R0 = mix(R0, R1, globalEye);\n"
"    // lerp refract and reflect\n"
"    _gl_FragColor = mix(screen, R0, vec4(R0.w));\n"
"}\n"
;
