
// radialblur
GLSL_SHADER const char ES3_RADIALBLUR_VERT[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"in highp vec4 attr_Vertex;\n"
"in highp vec4 attr_TexCoord;\n"
"in highp vec4 attr_Color;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"\n"
"out highp vec4 var_TexCoord;\n"
"out lowp vec4 var_Color;\n"
"\n"
"// # texture 0 takes the texture coordinates unmodified\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"\n"
"    var_TexCoord = attr_TexCoord;\n"
"    var_Color = attr_Color / 255.0;\n"
"}\n"
;
