
// screenprocess
GLSL_SHADER const char ES3_SCREENPROCESS_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_fragmentParm0;\n"
"uniform highp vec4 u_fragmentParm1;\n"
"uniform highp vec4 u_fragmentParm2;\n"
"uniform highp vec4 u_fragmentParm3;\n"
"\n"
"in highp vec4 var_TexCoord;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"// # texture 0 is _currentRender\n"
"// # texture 1 is a normal map that we will use to deform texture 0\n"
"\n"
"// # env[0] is the 1.0 to _currentRender conversion\n"
"// # env[1] is the fragment.position to 0.0 - 1.0 conversion\n"
"\n"
"void main(void)\n"
"{\n"
"// # scale by the screen non-power-of-two-adjust\n"
"    vec3 color = texture( u_fragmentMap0, var_TexCoord.st * u_nonPowerOfTwo.xy ).rgb;\n"
"    float R0 = dot( color, vec3( 0.3, 0.5, 0.1 ) );\n"
"    color = mix( vec3( R0 ), color, u_fragmentParm0.xyz );\n"
"    color = mix( vec3( u_fragmentParm1.y ), color, u_fragmentParm1.x );\n"
"    color = color * u_fragmentParm2.xyz + u_fragmentParm3.xyz;\n"
"    _gl_FragColor = vec4( color, 0.2 );\n"
"}\n"
;
