
// c64 retro postprocess
GLSL_SHADER const char RETRO_C64_FRAG[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"#define RESOLUTION_DIVISOR 4.0\n"
"#define NUM_COLORS 16\n"
"\n"
"uniform sampler2D u_fragmentMap0; // currentRender\n"
"\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_uniformParm0; // rpJitterTexScale\n"
"\n"
"varying vec2 var_TexCoord;\n"
"varying lowp vec4 var_Color;\n"
"\n"
"vec3 Average( vec3 pal[NUM_COLORS] )\n"
"{\n"
"    vec3 sum = vec3( 0.0 );\n"
"\n"
"    for( int i = 0; i < NUM_COLORS; i++ )\n"
"    {\n"
"        sum += pal[i];\n"
"    }\n"
"\n"
"    return sum / float( NUM_COLORS );\n"
"}\n"
"\n"
"vec3 Deviation( vec3 pal[NUM_COLORS] )\n"
"{\n"
"    vec3 sum = vec3( 0.0 );\n"
"    vec3 avg = Average( pal );\n"
"\n"
"    for( int i = 0; i < NUM_COLORS; i++ )\n"
"    {\n"
"        sum += abs( pal[i] - avg );\n"
"    }\n"
"\n"
"    return sum / float( NUM_COLORS );\n"
"}\n"
"\n"
"// squared distance to avoid the sqrt of distance function\n"
"float ColorCompare( vec3 a, vec3 b )\n"
"{\n"
"    vec3 diff = b - a;\n"
"    return dot( diff, diff );\n"
"}\n"
"\n"
"// find nearest palette color using Euclidean distance\n"
"vec3 LinearSearch( vec3 c, vec3 pal[NUM_COLORS] )\n"
"{\n"
"    int index = 0;\n"
"    float minDist = ColorCompare( c, pal[0] );\n"
"\n"
"    for( int i = 1; i < NUM_COLORS; i++ )\n"
"    {\n"
"        float dist = ColorCompare( c, pal[i] );\n"
"\n"
"        if( dist < minDist )\n"
"        {\n"
"            minDist = dist;\n"
"            index = i;\n"
"        }\n"
"    }\n"
"\n"
"    return pal[index];\n"
"}\n"
"\n"
_RETRO_POSTPROCESS_GENERAL_FUNCTION
"\n"
"void main(void)\n"
"{\n"
_RETRO_POSTPROCESS_GENERAL_ARRAY
"\n"
"    // gamma corrected version\n"
"    vec3 palette[NUM_COLORS];\n"
"    palette[0] = RGB( 0, 0, 0 ); // black\n"
"    palette[1] = RGB( 255, 255, 255 ); // white\n"
"    palette[2] = RGB( 104, 55,  43 ); // red\n"
"    palette[3] = RGB( 112, 164, 178 ); // cyan\n"
"    palette[4] = RGB( 111, 61,  134 ); // purple\n"
"    palette[5] = RGB( 88,  141, 67 ); // green\n"
"    palette[6] = RGB( 53,  40,  121 ); // blue\n"
"    palette[7] = RGB( 184, 199, 111 ); // yellow\n"
"    palette[8] = RGB( 111, 79,  37 ); // orange\n"
"    palette[9] = RGB( 67,  57,  0 ); // brown\n"
"    palette[10] = RGB( 154, 103, 89 ); // light red\n"
"    palette[11] = RGB( 68,  68,  68 ); // dark grey\n"
"    palette[12] = RGB( 108, 108, 108 ); // grey\n"
"    palette[13] = RGB( 154, 210, 132 ); // light green\n"
"    palette[14] = RGB( 108, 94,  181 ); // light blue\n"
"    palette[15] = RGB( 149, 149, 149 ); // light grey;\n"
"    vec2 uv = ( var_TexCoord );\n"
"    vec2 uvPixelated = floor( gl_FragCoord.xy / RESOLUTION_DIVISOR ) * RESOLUTION_DIVISOR;\n"
"\n"
"    vec3 quantizationPeriod = vec3( 1.0 / float(NUM_COLORS) );\n"
"    vec3 quantDeviation = Deviation( palette );\n"
"\n"
"    // get pixellated base color\n"
"    vec3 color = texture2D( u_fragmentMap0, uvPixelated * u_windowCoords.xy * u_nonPowerOfTwo.xy ).rgb;\n"
"\n"
"    vec2 uvDither = uvPixelated;\n"
"    //if( u_uniformParm0.x > 1.0 )\n"
"    {\n"
"        uvDither = gl_FragCoord.xy / ( RESOLUTION_DIVISOR / u_uniformParm0.x );\n"
"    }\n"
"    float dither = DitherArray8x8( uvDither ) - 0.5;\n"
"\n"
"    //color.rgb += vec3( dither, dither, dither ) * quantizationPeriod;\n"
"    color.rgb += vec3( dither, dither, dither ) * quantDeviation * u_uniformParm0.y;\n"
"\n"
"    // find closest color match from C64 color palette\n"
"    color = LinearSearch( color.rgb, palette );\n"
"\n"
"    //color = texture2D( u_fragmentMap0, uv ).rgb;\n"
"    gl_FragColor = vec4( color, 1.0 );\n"
"}\n"
;
