
// ps1 retro postprocess
GLSL_SHADER const char RETRO_PS1_FRAG[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"#define RESOLUTION_DIVISOR                4.0\n"
"#define Dithering_QuantizationSteps        32.0 // 8.0 = 2 ^ 3 quantization bits\n"
"\n"
"uniform sampler2D u_fragmentMap0; // currentRender\n"
"\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"\n"
"varying vec2 var_TexCoord;\n"
"varying lowp vec4 var_Color;\n"
"\n"
"vec3 Quantize( vec3 color, vec3 period )\n"
"{\n"
"    return floor( color * Dithering_QuantizationSteps ) * ( 1.0 / ( Dithering_QuantizationSteps - 1.0 ) );\n"
"}\n"
"\n"
_RETRO_POSTPROCESS_GENERAL_FUNCTION
"\n"
"void main(void)\n"
"{\n"
_RETRO_POSTPROCESS_GENERAL_ARRAY
"\n"
"    vec2 uv = ( var_TexCoord );\n"
"    vec2 uvPixelated = floor( gl_FragCoord.xy / RESOLUTION_DIVISOR ) * RESOLUTION_DIVISOR;\n"
"\n"
"    // most Sony Playstation 1 titles used 5 bit per RGB channel\n"
"    // 2^5 = 32\n"
"    // 32 * 32 * 32 = 32768 colors\n"
"\n"
"    const float quantizationSteps = Dithering_QuantizationSteps;\n"
"    vec3 quantizationPeriod = vec3( 1.0 / ( quantizationSteps - 1.0 ) );\n"
"\n"
"    // get pixellated base color\n"
"    vec3 color = texture2D( u_fragmentMap0, uvPixelated * u_windowCoords.xy * u_nonPowerOfTwo.xy ).rgb;\n"
"\n"
"    // add Bayer 8x8 dithering\n"
"    vec2 uvDither = gl_FragCoord.xy / RESOLUTION_DIVISOR;\n"
"\n"
"    float dither = DitherArray8x8( uvDither ) - 0.5;\n"
"\n"
"    color.rgb += vec3( dither, dither, dither ) * quantizationPeriod;\n"
"\n"
"    // PSX color quantization with 15-bit\n"
"    color = Quantize( color, quantizationPeriod );\n"
"\n"
"    //color = texture2D( u_fragmentMap0, uv ).rgb;\n"
"    gl_FragColor = vec4( color, 1.0 );\n"
"}\n"
;
