.\" Manpage for serioussam-texconv
.\" Contact  -- Alexander Pavlov <t.x00100x.t@yandex.ru> to correct errors or typos.
.TH man 6 "02  2024" "1.0" "serioussam-texconv man page"
.SH NAME
serioussam-texconv \- Texture converter for the game Serious Sam Classic TFE
.PP
.SH DESCRIPTION
.PP
.BR serioussam-texconv
is utility for converting textures for the game Serious Sam Classic TFE. With this utility you can convert
game textures to TGA format. The placement of the input files must be in the game data directory.
.PP
.SH SYNOPSIS
USAGE: serioussam-texconv <texture_file> [<tga_output_file>] 
.PP
texture_file: path to texture file
.PP
tga_output_file: path to create tga file
.PP
NOTES: - out file will have the name as texture file, but ".tga" extension
The texture file must be in the game directory. In the root or any subdirectory
.PP
.SH AUTHOR
 Alexander Pavlov <t.x00100x.t@yandex.ru>
