.\" Manpage for serioussamse-ded
.\" Contact  -- Alexander Pavlov <t.x00100x.t@yandex.ru> to correct errors or typos.
.TH man 6 "02  2024" "1.0" "serioussamse-ded man page"
.SH NAME
serioussamse-ded \- Dedicated server for Serious Sam Classic TSE
.PP
.SH DESCRIPTION
.PP
.BR serioussamse-ded
is dedicated server for the game Serious Sam Classic TSE. The server starts with settings from the 
Scripts/Dedicated/<Server Folder> directory. Where <Server Folder> is a directory containing scripts with server settings.
Learn more about server variable settings in Help/ShellSymbols.txt
.PP
.SH SYNOPSIS
Open terminal and put command:
.TP
\fBserioussam-ded DefaultCoop\fR
\-\ For start Serious Sam Classic The First Encounter coop dedicated server.
.TP
\fBserioussamse-ded DefaultCoop\fR
\-\ For start Serious Sam Classic The Second Encounter coop dedicated server.
.TP
.SS COMMAND LINE OPTIONS
.nf
\fBserioussam(se)-ded\fR <Server Folder> [+game modname]
.fi
.SH BUGS
There is no multiplayer compatibility between Windows and *nix systems.
.SH AUTHOR
 Alexander Pavlov <t.x00100x.t@yandex.ru>
