
// blend light
GLSL_SHADER const char BLENDLIGHT_VERT[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"attribute highp vec4 attr_Vertex;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform mat4 u_fogMatrix;\n"
"\n"
"varying vec2 var_TexFog;\n"
"varying vec2 var_TexFogEnter;\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"\n"
"    // What will be computed:\n"
"    //\n"
"    // vec4 tc;\n"
"    // tc.x = dot( u_fogMatrix[0], attr_Vertex );\n"
"    // tc.y = dot( u_fogMatrix[1], attr_Vertex );\n"
"    // tc.z = 0.0;\n"
"    // tc.w = dot( u_fogMatrix[2], attr_Vertex );\n"
"    // var_TexFog.xy = tc.xy / tc.w;\n"
"    //\n"
"    // var_TexFogEnter.x = dot( u_fogMatrix[3], attr_Vertex );\n"
"    // var_TexFogEnter.y = 0.5;\n"
"\n"
"    // Optimized version:\n"
"    //\n"
"    var_TexFog = vec2(dot( u_fogMatrix[0], attr_Vertex ), dot( u_fogMatrix[1], attr_Vertex )) / dot( u_fogMatrix[2], attr_Vertex );\n"
"    var_TexFogEnter = vec2( dot( u_fogMatrix[3], attr_Vertex ), 0.5 );\n"
"}\n"
;
