
// reflection cubemap(environment)
GLSL_SHADER const char ENVIRONMENT_VERT[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"attribute highp vec4 attr_Vertex;\n"
"attribute lowp vec4 attr_Color;\n"
"attribute vec3 attr_TexCoord;\n"
"attribute vec3 attr_Normal;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform mat4 u_modelViewMatrix;\n"
"uniform mat4 u_textureMatrix;\n"
"uniform lowp float u_colorModulate; // 0 or 1/255\n"
"uniform lowp float u_colorAdd; // 0 or 1\n"
"uniform vec4 u_viewOrigin;\n"
"\n"
"varying vec3 var_TexCoord;\n"
"varying lowp vec4 var_Color;\n"
"varying vec3 var_normalLocal;\n"
"varying vec3 var_toEyeLocal;\n"
"\n"
"void main(void)\n"
"{\n"
"#if 1\n"
"    var_normalLocal = attr_Normal;\n"
"    var_toEyeLocal = vec3(u_viewOrigin - attr_Vertex);\n"
"#else // d3asm\n"
"    var_TexCoord = (u_textureMatrix * reflect( normalize( u_modelViewMatrix * attr_Vertex ),\n"
"    // This suppose the modelView matrix is orthogonal\n"
"    // Otherwise, we should use the inverse transpose\n"
"        u_modelViewMatrix * vec4(attr_TexCoord,0.0) )).xyz ;\n"
"#endif\n"
"\n"
"    var_Color = " BYTE_COLOR(attr_Color) " * u_colorModulate + u_colorAdd;\n"
"\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
