
// fog
GLSL_SHADER const char FOG_VERT[] = 
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"attribute highp vec4 attr_Vertex;      // input Vertex Coordinates\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform mat4 u_fogMatrix;        // fogPlanes 0, 1, 3 (CATION: not 2!), 2\n"
"\n"
"varying vec2 var_TexFog;         // output Fog TexCoord\n"
"varying vec2 var_TexFogEnter;    // output FogEnter TexCoord\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"\n"
"    // What will be computed:\n"
"    //\n"
"    // var_TexFog.x      = dot(u_fogMatrix[0], attr_Vertex);\n"
"    // var_TexFog.y      = dot(u_fogMatrix[1], attr_Vertex);\n"
"    // var_TexFogEnter.x = dot(u_fogMatrix[2], attr_Vertex);\n"
"    // var_TexFogEnter.y = dot(u_fogMatrix[3], attr_Vertex);\n"
"\n"
"    // Optimized version:\n"
"    var_TexFog      = vec2(dot(u_fogMatrix[0], attr_Vertex),dot(u_fogMatrix[1], attr_Vertex));\n"
"    var_TexFogEnter = vec2(dot(u_fogMatrix[2], attr_Vertex),dot(u_fogMatrix[3], attr_Vertex));\n"
"}\n"
;
