
GLSL_SHADER const char GLOBAL_ILLUMINATION_VERT[] =
"#version 100\n"
"\n"
"//#pragma optimize(off)\n"
"\n"
"//#define _BFG\n"
"//#define BLINN_PHONG\n"
"//#define HALF_LAMBERT\n"
"\n"
"precision highp float;\n"
"\n"
"attribute vec4 attr_TexCoord;\n"
"attribute vec3 attr_Tangent;\n"
"attribute vec3 attr_Bitangent;\n"
"attribute vec3 attr_Normal;\n"
"attribute highp vec4 attr_Vertex;\n"
"attribute lowp vec4 attr_Color;\n"
"\n"
"uniform lowp float u_colorModulate; // 0 or 1/255\n"
"uniform lowp float u_colorAdd; // 0 or 1\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform vec4 u_viewOrigin;\n"
"\n"
"uniform vec4 u_bumpMatrixS;\n"
"uniform vec4 u_bumpMatrixT;\n"
"uniform vec4 u_diffuseMatrixS;\n"
"uniform vec4 u_diffuseMatrixT;\n"
"uniform vec4 u_specularMatrixS;\n"
"uniform vec4 u_specularMatrixT;\n"
"\n"
"varying vec2 var_TexDiffuse;\n"
"varying vec2 var_TexNormal;\n"
"varying vec2 var_TexSpecular;\n"
"varying lowp vec4 var_Color;\n"
"varying vec3 var_L;\n"
"varying vec3 var_H;\n"
"#if !defined(_BFG) && !defined(BLINN_PHONG)\n"
"varying vec3 var_V;\n"
"#endif\n"
"\n"
"void main(void)\n"
"{\n"
"    mat3 M = mat3(attr_Tangent, attr_Bitangent, attr_Normal);\n"
"\n"
"    var_TexNormal.x = dot(u_bumpMatrixS, attr_TexCoord);\n"
"    var_TexNormal.y = dot(u_bumpMatrixT, attr_TexCoord);\n"
"\n"
"    var_TexDiffuse.x = dot(u_diffuseMatrixS, attr_TexCoord);\n"
"    var_TexDiffuse.y = dot(u_diffuseMatrixT, attr_TexCoord);\n"
"\n"
"    var_TexSpecular.x = dot(u_specularMatrixS, attr_TexCoord);\n"
"    var_TexSpecular.y = dot(u_specularMatrixT, attr_TexCoord);\n"
"\n"
"    vec3 L = normalize(vec3(0.0, 0.5, 1.0));\n"
"    vec3 V = u_viewOrigin.xyz - attr_Vertex.xyz;\n"
"    vec3 H = normalize(L) + normalize(V);\n"
"\n"
"    var_L = L * M;\n"
"    var_H = H * M;\n"
"#if !defined(_BFG) && !defined(BLINN_PHONG)\n"
"    var_V = V * M;\n"
"#endif\n"
"\n"
"    var_Color = attr_Color * u_colorModulate + u_colorAdd;\n"
"\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
