
GLSL_SHADER const char HEATHAZEWITHMASK_VERT[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"attribute vec4 attr_TexCoord;\n"
"attribute highp vec4 attr_Vertex;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform highp mat4 u_modelViewMatrix;\n"
"uniform highp mat4 u_projectionMatrix;\n"
"\n"
"uniform highp vec4 u_vertexParm0; // texture scrolling\n"
"uniform highp vec4 u_vertexParm1; // magnitude of the distortion\n"
"\n"
"varying highp vec4 var_TexCoord0;\n"
"varying highp vec4 var_TexCoord1;\n"
"varying highp vec4 var_TexCoord2;\n"
"\n"
"// # input:\n"
"// #\n"
"// # texcoord[0] TEX0 texcoords\n"
"// #\n"
"// # local[0] scroll\n"
"// # local[1] deform magnitude (1.0 is reasonable, 2.0 is twice as wavy, 0.5 is half as wavy, etc)\n"
"// #\n"
"// # output:\n"
"// #\n"
"// # texture 0 is _currentRender\n"
"// # texture 1 is a normal map that we will use to deform texture 0\n"
"// # texture 2 is a mask texture\n"
"// #\n"
"// # texCoord[0] is the model surface texture coords unmodified for the mask\n"
"// # texCoord[1] is the model surface texture coords with a scroll\n"
"// # texCoord[2] is the copied deform magnitude\n"
"void main(void)\n"
"{\n"
#if HEATHAZE_BFG // BFG
"    // texture 0 takes the texture coordinates unmodified\n"
"    var_TexCoord0 = vec4( attr_TexCoord.xy, 0.0, 0.0 );\n"
"    // texture 1 takes the texture coordinates and adds a scroll\n"
"    vec4 textureScroll = u_vertexParm0;\n"
"    var_TexCoord1 = vec4( attr_TexCoord.xy, 0.0, 0.0 ) + textureScroll;\n"
"    // texture 2 takes the deform magnitude and scales it by the projection distance\n"
"    vec4 vec = vec4( 0.0, 1.0, 0.0, 1.0 );\n"
"    vec.z  = dot( attr_Vertex, u_modelViewMatrix[2] );\n"
"    // magicProjectionAdjust is a magic scalar that scales the projection since we changed from \n"
"    // using the X axis to the Y axis to calculate R1.  It is an approximation to closely match \n"
"    // what the original game did\n"
"    const float magicProjectionAdjust = 0.43;\n"
"    float x = dot ( vec, u_projectionMatrix[1] ) * magicProjectionAdjust;\n"
"    float w = dot ( vec, u_projectionMatrix[3] );\n"
"    // don't let the recip get near zero for polygons that cross the view plane\n"
"    w = max( w, 1.0 );\n"
"    x /= w;\n"
"    // clamp the distance so the the deformations don't get too wacky near the view\n"
"    x = min( x, 0.02 );\n"
"    vec4 deformMagnitude = u_vertexParm1;\n"
"    var_TexCoord2 = vec4(x) * deformMagnitude;\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"

#else // 2004

"    vec4 R0, R1, R2; // TEMP R0, R1, R2;\n"
"\n"
"    // # texture 0 takes the texture coordinates unmodified\n"
"    var_TexCoord0 = attr_TexCoord; // MOV  result.texcoord[0], vertex.texcoord[0];\n"
"\n"
"    // # texture 1 takes the texture coordinates and adds a scroll\n"
"    var_TexCoord1 = (attr_TexCoord) + (u_vertexParm0); // ADD  result.texcoord[1], vertex.texcoord[0], program.local[0];\n"
"\n"
"    // # texture 2 takes the deform magnitude and scales it by the projection distance\n"
"    vec4 vec = vec4(1.0, 0.0, 0.0, 1.0); // PARAM vec = { 1, 0, 0, 1 };\n"
"\n"
"    R0 = vec; // MOV  R0, vec;\n"
"    R0.z = dot(attr_Vertex, (u_modelViewMatrix)[2]); // DP4  R0.z, vertex.position, state.matrix.modelview.row[2];\n"
"\n"
"    R1 = vec4(dot(R0, (u_projectionMatrix)[0])); // DP4  R1, R0, state.matrix.projection.row[0];\n"
"    R2 = vec4(dot(R0, (u_projectionMatrix)[3])); // DP4  R2, R0, state.matrix.projection.row[3];\n"
"\n"
"    // # don't let the recip get near zero for polygons that cross the view plane\n"
"    R2 = max(R2, vec4(1.0)); // MAX  R2, R2, 1;\n"
"\n"
"    R2 = vec4(1.0 / R2.w); // RCP  R2, R2.w;\n"
"    R1 = (R1) * (R2); // MUL  R1, R1, R2;\n"
"\n"
"    // # clamp the distance so the the deformations don't get too wacky near the view\n"
"    R1 = min(R1, vec4(0.02)); // MIN  R1, R1, 0.02;\n"
"\n"
"    var_TexCoord2 = (R1) * (u_vertexParm1); // MUL  result.texcoord[2], R1, program.local[1];\n"
"\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
#endif
"}\n"
;
