
// interaction(shadow mapping)
GLSL_SHADER const char INTERACTION_SHADOW_MAPPING_FRAG[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision highp float;\n"
"\n"
"//#define BLINN_PHONG\n"
"//#define _PBR\n"
"//#define _AMBIENT\n"
"//#define _POINT_LIGHT\n"
"//#define _SPOT_LIGHT\n"
"//#define _PARALLEL_LIGHT\n"
"\n"
"//#define HALF_LAMBERT\n"
"\n"
"varying vec2 var_TexDiffuse;\n"
"varying vec2 var_TexNormal;\n"
"varying vec2 var_TexSpecular;\n"
"varying vec4 var_TexLight;\n"
"varying lowp vec4 var_Color;\n"
"varying vec3 var_L;\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"varying vec3 var_H;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"varying vec3 var_V;\n"
"#endif\n"
"#if defined(_PBR)\n"
"varying vec3 var_Normal;\n"
"#endif\n"
"\n"
"uniform vec4 u_diffuseColor;\n"
"uniform vec4 u_specularColor;\n"
"#if defined(_PBR)\n"
"uniform vec4 u_specularExponent;\n"
"#else\n"
"uniform float u_specularExponent;\n"
"#endif\n"
"\n"
"uniform sampler2D u_fragmentMap0;    /* u_bumpTexture */\n"
"uniform sampler2D u_fragmentMap1;    /* u_lightFalloffTexture */\n"
"uniform sampler2D u_fragmentMap2;    /* u_lightProjectionTexture */\n"
"uniform sampler2D u_fragmentMap3;    /* u_diffuseTexture */\n"
"#if defined(_AMBIENT)\n"
"uniform samplerCube u_fragmentCubeMap4;\n"
"varying mat3 var_TangentToWorldMatrix;\n"
"#else\n"
"uniform sampler2D u_fragmentMap4;    /* u_specularTexture */\n"
"uniform sampler2D u_fragmentMap5;    /* u_specularFalloffTexture */\n"
"#endif\n"
"#ifdef _POINT_LIGHT\n"
"uniform highp samplerCube u_fragmentCubeMap6;    /* u_shadowMapCubeTexture */\n"
"#else\n"
"uniform highp sampler2D u_fragmentMap6;    /* u_shadowMapTexture */\n"
"#endif\n"
"uniform sampler2D u_fragmentMap7;    /* u_jitterMapTexture */\n"
"\n"
"uniform highp vec4 globalLightOrigin;\n"
"uniform mediump float u_uniformParm0; // shadow alpha\n"
"uniform highp vec4 u_uniformParm1; // (shadow map texture size, 1.0 / shadow map texture size, sampler factor, 0)\n"
"uniform highp vec4 u_uniformParm2; // (1.0 / screen width, 1.0 / screen height, jitter texture size, 1.0 / jitter texture size)\n"
"uniform highp float u_uniformParm4; // shadow bias for test\n"
"#define SHADOW_ALPHA u_uniformParm0\n"
"#define SHADOW_MAP_SIZE u_uniformParm1.x\n"
"#define SHADOW_MAP_SIZE_MULTIPLICATOR u_uniformParm1.y\n"
"#define JITTER_SCALE u_uniformParm1.z\n"
"#define SCREEN_SIZE_MULTIPLICATOR u_uniformParm2.xy\n"
"#ifdef _POINT_LIGHT\n"
"    varying highp vec3 var_LightToVertex;\n"
"    varying highp vec4 var_VertexPosition;\n"
"    uniform highp mat4 shadowMVPMatrix[6];\n"
"bool plane_ray_intersect(highp vec3 plane_point, highp vec3 plane_normal, highp vec3 dir, out highp vec3 ret) {\n"
"	highp float dotProduct = dot(dir, plane_normal);\n"
"	highp float dotProductFactor = 1.0 / dotProduct;\n"
"	// if(dotProduct == 0.0) return false;\n"
"	highp float l2 = dot(plane_normal, plane_point) * dotProductFactor;\n"
"	// if (l2 < 0.0) return false;\n"
"	highp float distance = dot(plane_normal, plane_point);\n"
"	highp float t = - (dot(plane_normal, dir) - distance) * dotProductFactor;\n"
"	ret = dir * t;\n"
"	return true;\n"
"}\n"
"#else\n"
"    varying highp vec4 var_ShadowCoord;\n"
"#endif\n"
"\n"
"#if !defined(_USING_DEPTH_TEXTURE) && defined(_PACK_FLOAT)\n"
UNPACK_FLOAT_FUNC()
"#define DC(x) (unpack(x))\n"
"#else\n"
"#define DC(x) ((x).r)\n"
"#endif\n"
"\n"
"#ifdef _DYNAMIC_BIAS\n"
"   #ifdef _PARALLEL_LIGHT\n"
"       #define BIAS_SCALE 0.999991\n"
"   #else\n"
"       #define BIAS_SCALE 0.999\n"
"   #endif\n"
"   #define BIAS(x) ((x) * BIAS_SCALE)\n"
"#elif defined(_FIXED_BIAS)\n"
"    #define BIAS_OFFSET 0.001\n"
"   #define BIAS(x) ((x) - BIAS_OFFSET)\n"
"#else\n"
"   #define BIAS(x) (x)\n"
"#endif\n"
"\n"
"#if defined(_PBR)\n"
_PBR_GENERAL_FUNCTION
"#endif\n"
"\n"
"void main(void)\n"
"{\n"
"    //float u_specularExponent = 4.0;\n"
"\n"
"    vec3 L = normalize(var_L);\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"    vec3 H = normalize(var_H);\n"
"#endif\n"
"#if defined(BLINN_PHONG) || defined(_AMBIENT)\n"
"    vec3 N = 2.0 * texture2D(u_fragmentMap0, var_TexNormal.st).agb - 1.0;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"    vec3 V = normalize(var_V);\n"
"    vec3 N = normalize(2.0 * texture2D(u_fragmentMap0, var_TexNormal.st).agb - 1.0);\n"
"#endif\n"
"\n"
"#if defined(_AMBIENT)\n"
"    vec3 globalNormal = var_TangentToWorldMatrix * N; // transform into ambient map space\n"
"    vec3 ambientValue = textureCube(u_fragmentCubeMap4, globalNormal).rgb; // load the ambient value\n"
"#endif\n"
"\n"
"    float NdotL = clamp(dot(N, L), 0.0, 1.0);\n"
"#if defined(HALF_LAMBERT)\n"
"    NdotL *= 0.5;\n"
"    NdotL += 0.5;\n"
"    NdotL = NdotL * NdotL;\n"
"#endif\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"    float NdotH = clamp(dot(N, H), 0.0, 1.0);\n"
"#endif\n"
"\n"
"    vec3 lightProjection = texture2DProj(u_fragmentMap2, var_TexLight.xyw).rgb;\n"
"    vec3 lightFalloff = texture2D(u_fragmentMap1, vec2(var_TexLight.z, 0.5)).rgb;\n"
"    vec3 diffuseColor = texture2D(u_fragmentMap3, var_TexDiffuse).rgb * u_diffuseColor.rgb;\n"
"#if defined(_PBR)\n"
"    vec3 AN = normalize(mix(normalize(var_Normal), N, u_specularExponent.y));\n"
"    vec4 Cd = vec4(diffuseColor.rgb, 1.0);\n"
"    vec4 specTex = texture2D(u_fragmentMap4, var_TexSpecular);\n"
"#ifdef _PBR_RMAO_ONLY\n"
"    vec4 roughness = vec4(specTex.r, specTex.r, specTex.r, specTex.r);\n"
"    vec4 metallic = vec4(specTex.g, specTex.g, specTex.g, specTex.g);\n"
"#else // compat RMAO if u_specularExponent.z == 0 and u_specularExponent.w == 0\n"
"    vec4 roughness = vec4(clamp(specTex.r * (sign(1.0 - abs(sign(u_specularExponent.z))) * 2.0 - 1.0) /* if max == 0, result = 1; else result = -1 */ + u_specularExponent.z, 0.0, 1.0) * max(sign(specTex.r), 0.0) /* if specularTex.r == 0, result = 0, else result = 1 */); // roughness = max - specularTex.r, but if specularTex.r == 0, roughness = 0\n"
"    vec4 metallic = vec4(clamp(specTex.g + u_specularExponent.w, 0.0, 1.0) * max(sign(specTex.g), 0.0) /* if specularTex.g == 0, result = 0, else result = 1 */); // metallic = specularTex.r, but if specularTex.r == 0, metallic = 0\n"
"#endif\n"
"\n"
"    vec4 Cl = vec4(lightProjection * lightFalloff, 1.0);\n"
"    vec3 F0 = vec3(0.04); \n"
"    F0 = mix(F0, Cd.xyz, metallic.xyz);\n"
"\n"
"    // cook-torrance brdf\n"
"    float NDF = DistributionGGX(AN, H, roughness.x);        \n"
"    float G   = GeometrySmith(AN, V, L, roughness.x);      \n"
"    vec3 F    = fresnelSchlick(clamp(dot(H, V), 0.0, 1.0), F0); //max       \n"
"\n"
"    vec3 kS = F;\n"
"    vec3 kD = vec3(1.0) - kS;\n"
"    kD *= 1.0 - metallic.r;\n"
"\n"
"    vec3 numerator    = NDF * G * F;\n"
"    float denominator = 4.0 * max(dot(AN, V), 0.0) * max(dot(AN, L), 0.0);\n"
"    vec3 pbr     = numerator / max(denominator, 0.001);  \n"
"\n"
"#if 1\n"
"    vec4 color = (Cd/* * vec4(kD, 1.0)*/ + (u_specularExponent.x * vec4(pbr.rgb, 0.0) * u_specularColor)) * NdotL * Cl;\n"
"    color = vec4(color.rgb, 1.0) * var_Color;\n"
"#else\n"
"    vec4 color = var_Color * Cl * NdotL * Cd + (u_specularExponent.x * vec4(pbr.rgb, 0.0) * (u_specularColor/* * Cl*/));\n"
"#endif\n"
"#elif defined(_AMBIENT)\n"
"    vec3 color = u_specularExponent * /*ambientValue * */diffuseColor * lightProjection * lightFalloff;\n"
"#else\n"
"    vec3 specularColor = 2.0 * texture2D(u_fragmentMap4, var_TexSpecular).rgb * u_specularColor.rgb;\n"
"\n"
"#if defined(BLINN_PHONG)\n"
"    float specularFalloff = pow(NdotH, u_specularExponent);\n"
"#else\n"
"    vec3 R = -reflect(L, N);\n"
"    float RdotV = clamp(dot(R, V), 0.0, 1.0);\n"
"    float specularFalloff = pow(RdotV, u_specularExponent);\n"
"#endif\n"
"#endif\n"
"\n"
"    highp float shadow = 0.0;\n"
"\n"
"#ifdef _POINT_LIGHT\n"
SHADOW_MAPPING_SAMPLE_CUBE_POISSON_DISK
"    highp vec3 toLightGlobal = normalize( -var_LightToVertex );\n"
"    int shadowIndex = 0;"
"    highp float axis[6];\n"
"    axis[0] = -toLightGlobal.x;\n"
"    axis[1] =  toLightGlobal.x;\n"
"    axis[2] = -toLightGlobal.y;\n"
"    axis[3] =  toLightGlobal.y;\n"
"    axis[4] = -toLightGlobal.z;\n"
"    axis[5] =  toLightGlobal.z;\n"
"    for( int i = 0; i < 6; ++i ) {\n"
"        //if( axis[i] > axis[shadowIndex] ) {        shadowIndex = i;    }\n"
"        shadowIndex = axis[i] > axis[shadowIndex] ? i : shadowIndex;\n"
"    }\n"
"    highp vec3 plane_normal;\n"
"    highp vec3 plane_point;\n"
"    highp float radius = SHADOW_MAP_SIZE * 0.5;\n"
"    if(shadowIndex == 0) { // +X \n"
"        plane_point = vec3(radius, 0.0, 0.0);\n"
"        plane_normal = vec3(-1.0, 0.0, 0.0);\n"
"    } else if(shadowIndex == 1) { // -X \n"
"        plane_point = vec3(-radius, 0.0, 0.0);\n"
"        plane_normal = vec3(1.0, 0.0, 0.0);\n"
"    } else if(shadowIndex == 2) { // +Y \n"
"        plane_point = vec3(0.0, radius, 0.0);\n"
"        plane_normal = vec3(0.0, -1.0, 0.0);\n"
"    } else if(shadowIndex == 3) { // -Y \n"
"        plane_point = vec3(0.0, -radius, 0.0);\n"
"        plane_normal = vec3(0.0, 1.0, 0.0);\n"
"    } else if(shadowIndex == 4) { // +Z \n"
"        plane_point = vec3(0.0, 0.0, radius);\n"
"        plane_normal = vec3(0.0, 0.0, -1.0);\n"
"    } else { // -Z \n"
"        plane_point = vec3(0.0, 0.0, -radius);\n"
"        plane_normal = vec3(0.0, 0.0, 1.0);\n"
"    }\n"
"    highp vec3 texcoordCube;\n"
"    plane_ray_intersect(plane_point, plane_normal, normalize(var_LightToVertex), texcoordCube);\n"
"    highp vec4 shadowPosition = var_VertexPosition * shadowMVPMatrix[shadowIndex];\n"
"    shadowPosition.xyz /= shadowPosition.w;\n"
"    highp float currentDepth = BIAS(shadowPosition.z);\n"
"    highp float distance = JITTER_SCALE * 0.5;\n"
"    for (int i = 0; i < SAMPLES; ++i) {\n"
"        highp vec3 jitter = sampleOffsetTable[i];\n"
"        highp float shadowDepth = DC(textureCube(u_fragmentCubeMap6, normalize(texcoordCube + jitter * distance)));\n"
"        highp float visibility = currentDepth - shadowDepth;\n"
"        shadow += 1.0 - step(0.0, visibility) * SHADOW_ALPHA;\n"
"        //shadow += visibility < 0.0 ? 1.0 : SHADOW_ALPHA;\n"
"    }\n"
"#else // end point light\n"
SHADOW_MAPPING_SAMPLE_POISSON_DISK
"    // highp float random = (gl_FragCoord.z + shadowPosition.z) * 0.5;\n"
"    highp float random = texture2D( u_fragmentMap7, gl_FragCoord.xy * SCREEN_SIZE_MULTIPLICATOR ).r;\n"
"    random *= 3.141592653589793;\n"
"    highp vec2 rot;\n"
"    rot.x = cos( random );\n"
"    rot.y = sin( random );\n"
"    highp float distance = JITTER_SCALE * SHADOW_MAP_SIZE_MULTIPLICATOR;\n"
"    highp vec3 shadowCoord = var_ShadowCoord.xyz / var_ShadowCoord.w;\n"
"    highp float currentDepth = BIAS(shadowCoord.z);\n"
"    for (int i = 0; i < SAMPLES; ++i) {\n"
"        highp vec2 jitter = sampleOffsetTable[i];\n"
"        highp vec2 jitterRotated;\n"
"        jitterRotated.x = jitter.x * rot.x - jitter.y * rot.y;\n"
"        jitterRotated.y = jitter.x * rot.y + jitter.y * rot.x;\n"
"        highp float shadowDepth = DC(texture2D(u_fragmentMap6, shadowCoord.st + jitterRotated * distance));\n"
"        highp float visibility = currentDepth - shadowDepth;\n"
"        shadow += 1.0 - step(0.0, visibility) * SHADOW_ALPHA;\n"
"        //shadow += visibility < 0.0 ? 1.0 : SHADOW_ALPHA;\n"
"    }\n"
"#endif\n"
"    const highp float sampleAvg = SAMPLE_MULTIPLICATOR;\n"
"    shadow *= sampleAvg;\n"
"\n"
"#if defined(_PBR)\n"
"    gl_FragColor = vec4(color.rgb * shadow, color.a);\n"
"#elif defined(_AMBIENT)\n"
"    color *= shadow;\n"
"    gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"#else\n"
"    vec3 color;\n"
"    color = diffuseColor;\n"
"    color += specularFalloff * specularColor;\n"
"    color *= NdotL * lightProjection;\n"
"    color *= lightFalloff;\n"
"    color *= shadow;\n"
"\n"
"    gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"#endif\n"
"}\n"
;
