enum playerframe
{
//
//, running
//
	axrun1, axrun2, axrun3, axrun4, axrun5, axrun6,
	rockrun1, rockrun2, rockrun3, rockrun4, rockrun5, rockrun6,

//
//, standing
//
	stand1, stand2, stand3, stand4, stand5,
	axstnd1, axstnd2, axstnd3, axstnd4, axstnd5, axstnd6, axstnd7, axstnd8, axstnd9, axstnd10, axstnd11, axstnd12,


//
//, pain
//
	axpain1, axpain2, axpain3, axpain4, axpain5, axpain6,
	pain1, pain2, pain3, pain4, pain5, pain6,


//
//, death
//

	axdeth1, axdeth2, axdeth3, axdeth4, axdeth5, axdeth6, axdeth7, axdeth8, axdeth9,
	deatha1, deatha2, deatha3, deatha4, deatha5, deatha6, deatha7, deatha8,	deatha9, deatha10, deatha11,
	deathb1, deathb2, deathb3, deathb4, deathb5, deathb6, deathb7, deathb8,	deathb9,
	deathc1, deathc2, deathc3, deathc4, deathc5, deathc6, deathc7, deathc8,	deathc9, deathc10, deathc11, deathc12, deathc13, deathc14, deathc15,
	deathd1, deathd2, deathd3, deathd4, deathd5, deathd6, deathd7, deathd8, deathd9,
	deathe1, deathe2, deathe3, deathe4, deathe5, deathe6, deathe7, deathe8, deathe9,

//
//, attacks
//
	nailatt1, nailatt2,
	light1, light2,
	rockatt1, rockatt2, rockatt3, rockatt4, rockatt5, rockatt6,
	shotatt1, shotatt2, shotatt3, shotatt4, shotatt5, shotatt6,
	axatt1, axatt2, axatt3, axatt4, axatt5, axatt6,
	axattb1, axattb2, axattb3, axattb4, axattb5, axattb6,
	axattc1, axattc2, axattc3, axattc4, axattc5, axattc6,
	axattd1, axattd2, axattd3, axattd4, axattd5, axattd6,
};
