#ifndef QGLPROC
#error "you must define QGLPROC before including this file"
#endif

// OpenGL ES 1.1 API
QGLPROC(glAlphaFunc, void, (GLenum func, GLfloat ref));
QGLPROC(glClearColor, void, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
QGLPROC(glClearDepthf, void, (GLfloat d));
QGLPROC(glClipPlanef, void, (GLenum p, const GLfloat *eqn));
QGLPROC(glColor4f, void, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
QGLPROC(glDepthRangef, void, (GLfloat n, GLfloat f));
QGLPROC(glFogf, void, (GLenum pname, GLfloat param));
QGLPROC(glFogfv, void, (GLenum pname, const GLfloat *params));
QGLPROC(glFrustumf, void, (GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f));
QGLPROC(glGetClipPlanef, void, (GLenum plane, GLfloat *equation));
QGLPROC(glGetFloatv, void, (GLenum pname, GLfloat *data));
QGLPROC(glGetLightfv, void, (GLenum light, GLenum pname, GLfloat *params));
QGLPROC(glGetMaterialfv, void, (GLenum face, GLenum pname, GLfloat *params));
QGLPROC(glGetTexEnvfv, void, (GLenum target, GLenum pname, GLfloat *params));
QGLPROC(glGetTexParameterfv, void, (GLenum target, GLenum pname, GLfloat *params));
QGLPROC(glLightModelf, void, (GLenum pname, GLfloat param));
QGLPROC(glLightModelfv, void, (GLenum pname, const GLfloat *params));
QGLPROC(glLightf, void, (GLenum light, GLenum pname, GLfloat param));
QGLPROC(glLightfv, void, (GLenum light, GLenum pname, const GLfloat *params));
QGLPROC(glLineWidth, void, (GLfloat width));
QGLPROC(glLoadMatrixf, void, (const GLfloat *m));
QGLPROC(glMaterialf, void, (GLenum face, GLenum pname, GLfloat param));
QGLPROC(glMaterialfv, void, (GLenum face, GLenum pname, const GLfloat *params));
QGLPROC(glMultMatrixf, void, (const GLfloat *m));
QGLPROC(glMultiTexCoord4f, void, (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q));
QGLPROC(glNormal3f, void, (GLfloat nx, GLfloat ny, GLfloat nz));
QGLPROC(glOrthof, void, (GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f));
QGLPROC(glPointParameterf, void, (GLenum pname, GLfloat param));
QGLPROC(glPointParameterfv, void, (GLenum pname, const GLfloat *params));
QGLPROC(glPointSize, void, (GLfloat size));
QGLPROC(glPolygonOffset, void, (GLfloat factor, GLfloat units));
QGLPROC(glRotatef, void, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
QGLPROC(glScalef, void, (GLfloat x, GLfloat y, GLfloat z));
QGLPROC(glTexEnvf, void, (GLenum target, GLenum pname, GLfloat param));
QGLPROC(glTexEnvfv, void, (GLenum target, GLenum pname, const GLfloat *params));
QGLPROC(glTexParameterf, void, (GLenum target, GLenum pname, GLfloat param));
QGLPROC(glTexParameterfv, void, (GLenum target, GLenum pname, const GLfloat *params));
QGLPROC(glTranslatef, void, (GLfloat x, GLfloat y, GLfloat z));
QGLPROC(glActiveTexture, void, (GLenum texture));
QGLPROC(glAlphaFuncx, void, (GLenum func, GLfixed ref));
QGLPROC(glBindBuffer, void, (GLenum target, GLuint buffer));
QGLPROC(glBindTexture, void, (GLenum target, GLuint texture));
QGLPROC(glBlendFunc, void, (GLenum sfactor, GLenum dfactor));
QGLPROC(glBufferData, void, (GLenum target, GLsizeiptr size, const void *data, GLenum usage));
QGLPROC(void glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const void *data));
QGLPROC(void glClear (GLbitfield mask));
QGLPROC(void glClearColorx (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha));
QGLPROC(void glClearDepthx (GLfixed depth));
QGLPROC(void glClearStencil (GLint s));
QGLPROC(void glClientActiveTexture (GLenum texture));
QGLPROC(void glClipPlanex (GLenum plane, const GLfixed *equation));
QGLPROC(void glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha));
QGLPROC(void glColor4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha));
QGLPROC(void glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
QGLPROC(void glColorPointer (GLint size, GLenum type, GLsizei stride, const void *pointer));
QGLPROC(void glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data));
QGLPROC(void glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data));
QGLPROC(glCopyTexImage2D, void, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
QGLPROC(glCopyTexSubImage2D, void, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
QGLPROC(glCullFace, void, (GLenum mode));
QGLPROC(glDeleteBuffers, void, (GLsizei n, const GLuint *buffers));
QGLPROC(glDeleteTextures, void, (GLsizei n, const GLuint *textures));
QGLPROC(glDepthFunc, void, (GLenum func));
QGLPROC(glDepthMask, void, (GLboolean flag));
QGLPROC(glDepthRangex, void, (GLfixed n, GLfixed f));
QGLPROC(glDisable, void, (GLenum cap));
QGLPROC(glDisableClientState, void, (GLenum array));
QGLPROC(glDrawArrays, void, (GLenum mode, GLint first, GLsizei count));
QGLPROC(glDrawElements, void, (GLenum mode, GLsizei count, GLenum type, const void *indices));
QGLPROC(glEnable, void, (GLenum cap));
QGLPROC(glEnableClientState, void, (GLenum array));
QGLPROC(glFinish, void, (void));
QGLPROC(glFlush, void, (void));
QGLPROC(glFogx, void, (GLenum pname, GLfixed param));
QGLPROC(glFogxv, void, (GLenum pname, const GLfixed *param));
QGLPROC(glFrontFace, void, (GLenum mode));
QGLPROC(glFrustumx, void, (GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f));
QGLPROC(glGetBooleanv, void, (GLenum pname, GLboolean *data));
QGLPROC(glGetBufferParameteriv, void, (GLenum target, GLenum pname, GLint *params));
QGLPROC(glGetClipPlanex, void, (GLenum plane, GLfixed *equation));
QGLPROC(glGenBuffers, void, (GLsizei n, GLuint *buffers));
QGLPROC(glGenTextures, void, (GLsizei n, GLuint *textures));
QGLPROC(glGetError, GLenum, (void));
QGLPROC(glGetFixedv, void, (GLenum pname, GLfixed *params));
QGLPROC(glGetIntegerv, void, (GLenum pname, GLint *data));
QGLPROC(glGetLightxv, void, (GLenum light, GLenum pname, GLfixed *params));
QGLPROC(glGetMaterialxv, void, (GLenum face, GLenum pname, GLfixed *params));
QGLPROC(glGetPointerv, void, (GLenum pname, void **params));
QGLPROC(glGetString, const GLubyte *, (GLenum name));
QGLPROC(glGetTexEnviv, void, (GLenum target, GLenum pname, GLint *params));
QGLPROC(glGetTexEnvxv, void, (GLenum target, GLenum pname, GLfixed *params));
QGLPROC(glGetTexParameteriv, void, (GLenum target, GLenum pname, GLint *params));
QGLPROC(glGetTexParameterxv, void, (GLenum target, GLenum pname, GLfixed *params));
QGLPROC(glHint, void, (GLenum target, GLenum mode));
QGLPROC(glIsBuffer, GLboolean, (GLuint buffer));
QGLPROC(glIsEnabled, GLboolean, (GLenum cap));
QGLPROC(glIsTexture, GLboolean, (GLuint texture));
QGLPROC(glLightModelx, void, (GLenum pname, GLfixed param));
QGLPROC(glLightModelxv, void, (GLenum pname, const GLfixed *param));
QGLPROC(glLightx, void, (GLenum light, GLenum pname, GLfixed param));
QGLPROC(glLightxv, void, (GLenum light, GLenum pname, const GLfixed *params));
QGLPROC(glLineWidthx, void, (GLfixed width));
QGLPROC(glLoadIdentity, void, (void));
QGLPROC(glLoadMatrixx, void, (const GLfixed *m));
QGLPROC(glLogicOp, void, (GLenum opcode));
QGLPROC(glMaterialx, void, (GLenum face, GLenum pname, GLfixed param));
QGLPROC(glMaterialxv, void, (GLenum face, GLenum pname, const GLfixed *param));
QGLPROC(glMatrixMode, void, (GLenum mode));
QGLPROC(glMultMatrixx, void, (const GLfixed *m));
QGLPROC(glMultiTexCoord4x, void, (GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q));
QGLPROC(glNormal3x, void, (GLfixed nx, GLfixed ny, GLfixed nz));
QGLPROC(glNormalPointer, void, (GLenum type, GLsizei stride, const void *pointer));
QGLPROC(glOrthox, void, (GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f));
QGLPROC(glPixelStorei, void, (GLenum pname, GLint param));
QGLPROC(glPointParameterx, void, (GLenum pname, GLfixed param));
QGLPROC(glPointParameterxv, void, (GLenum pname, const GLfixed *params));
QGLPROC(glPointSizex, void, (GLfixed size));
QGLPROC(glPolygonOffsetx, void, (GLfixed factor, GLfixed units));
QGLPROC(glPopMatrix, void, (void));
QGLPROC(glPushMatrix, void, (void));
QGLPROC(glReadPixels, void, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels));
QGLPROC(glRotatex, void, (GLfixed angle, GLfixed x, GLfixed y, GLfixed z));
QGLPROC(glSampleCoverage, void, (GLfloat value, GLboolean invert));
QGLPROC(glSampleCoveragex, void, (GLclampx value, GLboolean invert));
QGLPROC(glScalex, void, (GLfixed x, GLfixed y, GLfixed z));
QGLPROC(glScissor, void, (GLint x, GLint y, GLsizei width, GLsizei height));
QGLPROC(glShadeModel, void, (GLenum mode));
QGLPROC(glStencilFunc, void, (GLenum func, GLint ref, GLuint mask));
QGLPROC(glStencilMask, void, (GLuint mask));
QGLPROC(glStencilOp, void, (GLenum fail, GLenum zfail, GLenum zpass));
QGLPROC(glTexCoordPointer, void, (GLint size, GLenum type, GLsizei stride, const void *pointer));
QGLPROC(glTexEnvi, void, (GLenum target, GLenum pname, GLint param));
QGLPROC(glTexEnvx, void, (GLenum target, GLenum pname, GLfixed param));
QGLPROC(glTexEnviv, void, (GLenum target, GLenum pname, const GLint *params));
QGLPROC(glTexEnvxv, void, (GLenum target, GLenum pname, const GLfixed *params));
QGLPROC(glTexImage2D, void, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels));
QGLPROC(glTexParameteri, void, (GLenum target, GLenum pname, GLint param));
QGLPROC(glTexParameterx, void, (GLenum target, GLenum pname, GLfixed param));
QGLPROC(glTexParameteriv, void, (GLenum target, GLenum pname, const GLint *params));
QGLPROC(glTexParameterxv, void, (GLenum target, GLenum pname, const GLfixed *params));
QGLPROC(glTexSubImage2D, void, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels));
QGLPROC(glTranslatex, void, (GLfixed x, GLfixed y, GLfixed z));
QGLPROC(glVertexPointer, void, (GLint size, GLenum type, GLsizei stride, const void *pointer));
QGLPROC(glViewport, void, (GLint x, GLint y, GLsizei width, GLsizei height));

#ifndef GL_OES_point_size_array
QGLPROC(glPointSizePointerOES, void, (GLenum type, GLsizei stride, const void *pointer));
#endif /* GL_OES_point_size_array */

#undef QGLPROC
