
// liquid
GLSL_SHADER const char LIQUID_VERT[] =
"#version 100\n"
"\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"attribute vec4 attr_TexCoord;\n"
"attribute vec3 attr_Tangent;\n"
"attribute vec3 attr_Bitangent;\n"
"attribute vec3 attr_Normal;\n"
"attribute highp vec4 attr_Vertex;\n"
"\n"
"uniform vec4 u_viewOrigin;\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform highp mat4 u_modelMatrix;\n"
"uniform highp mat4 u_modelViewMatrix;\n"
"uniform highp mat4 u_projectionMatrix;\n"
"uniform vec4 u_vertexParm1; // deform magnitude (1.0 is reasonable, 2.0 is twice as wavy, 0.5 is half as wavy, etc)\n"
"\n"
"varying vec4 var_TexCoord0; // texCoord[0] is the normal map texcoord\n"
"varying highp vec4 var_TexCoord1; // texCoord[1] is the vector to the eye in global space //karin: must high precison on GLSL\n"
"varying vec4 var_TexCoord2; // texCoord[2] is the surface tangent to global coordiantes\n"
"varying vec4 var_TexCoord3; // texCoord[3] is the surface bitangent to global coordiantes\n"
"varying vec4 var_TexCoord4; // texCoord[4] is the surface normal to global coordiantes\n"
"varying vec4 var_TexCoord6; // texCoord[6] is the copied deform magnitude\n"
"//varying vec4 var_TexCoord7; // texCoord[7] is the copied scroll\n"
"\n"
"void main(void)\n"
"{\n"
"    vec4 scale = vec4( 2.0, 2.0, 2.0, 2.0 );\n"
"    vec4 R0 = u_viewOrigin - attr_Vertex;\n"
"\n"
"    // texture 1 is the vector to the eye in global coordinates\n"
"    var_TexCoord1.x = dot(R0.xyz, u_modelMatrix[0].xyz);\n"
"    var_TexCoord1.y = dot(R0.xyz, u_modelMatrix[1].xyz);\n"
"    var_TexCoord1.z = dot(R0.xyz, u_modelMatrix[2].xyz);\n"
"\n"
"    // texture 2 gets the transformed tangent\n"
"    var_TexCoord2.x = dot(attr_Tangent, u_modelMatrix[0].xyz);\n"
"    var_TexCoord3.x = dot(attr_Tangent, u_modelMatrix[1].xyz);\n"
"    var_TexCoord4.x = dot(attr_Tangent, u_modelMatrix[2].xyz);\n"
"\n"
"    // texture 3 gets the transformed bitangent\n"
"    var_TexCoord2.y = dot(attr_Bitangent, u_modelMatrix[0].xyz);\n"
"    var_TexCoord3.y = dot(attr_Bitangent, u_modelMatrix[1].xyz);\n"
"    var_TexCoord4.y = dot(attr_Bitangent, u_modelMatrix[2].xyz);\n"
"\n"
"    // texture 4 gets the transformed normal\n"
"    var_TexCoord2.z = dot(attr_Normal, u_modelMatrix[0].xyz);\n"
"    var_TexCoord3.z = dot(attr_Normal, u_modelMatrix[1].xyz);\n"
"    var_TexCoord4.z = dot(attr_Normal, u_modelMatrix[2].xyz);\n"
"\n"
"    // take the texture coordinates and add a scroll\n"
"    var_TexCoord0 = attr_TexCoord;\n"
"\n"
"    // texture 6 takes the deform magnitude and scales it by the projection distance\n"
"    R0 = vec4( 1.0, 0.0, 0.0, 1.0 );\n"
"    R0.z = dot(attr_Vertex, u_modelViewMatrix[2]);\n"
"\n"
"    float R1 = dot(R0, u_projectionMatrix[0]);\n"
"    float R2 = dot(R0, u_projectionMatrix[3]);\n"
"\n"
"    // don't let the recip get near zero for polygons that cross the view plane\n"
"    R2 = max(R2, 1.0);\n"
"\n"
"    R2 = 1.0 / R2;\n"
"    R1 = R1 * R2;\n"
"\n"
"    // clamp the distance so the the deformations don't get too wacky near the view\n"
"    R1 = min(R1, 0.02);\n"
"    var_TexCoord6 = R1 * u_vertexParm1;\n"
"\n"
"    //var_TexCoord7 = scroll;\n"
"\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
