
// radialblur
GLSL_SHADER const char RADIALBLUR_FRAG[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_fragmentParm0;\n"
"uniform highp vec4 u_fragmentParm1;\n"
"uniform highp vec4 u_fragmentParm2;\n"
"uniform highp vec4 u_fragmentParm3;\n"
"uniform highp vec4 u_fragmentParm4;\n"
"uniform highp vec4 u_fragmentParm5;\n"
"\n"
"varying highp vec4 var_TexCoord;\n"
"varying lowp vec4 var_Color;\n"
"\n"
"// # texture 0 is _currentRender\n"
"// # texture 1 is a normal map that we will use to deform texture 0\n"
"\n"
"// # env[0] is the 1.0 to _currentRender conversion\n"
"// # env[1] is the fragment.position to 0.0 - 1.0 conversion\n"
"\n"
"void main(void)\n"
"{\n"
"    vec2 size = u_fragmentParm0.xy;\n"
"    vec2 strength = u_fragmentParm0.xy;\n"
"\n"
"// # calculate the screen texcoord in the 0.0 to 1.0 range\n"
"// # scale by the screen non-power-of-two-adjust\n"
"    vec2 pos = var_TexCoord.st * u_nonPowerOfTwo.xy;\n"
"\n"
"    vec3 color = vec3( 0.0 );\n"
"\n"
"    vec2 halfTemp = u_nonPowerOfTwo.xy * 0.5;\n"
"    vec2 R1 = pos.xy - halfTemp;\n"
"\n"
"    float displace = 1.0;\n"
"    vec2 tc = R1 * displace + halfTemp;\n"
"    vec3 c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    displace = displace - size.x;\n"
"    tc = R1 * displace + halfTemp;\n"
"    c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    displace = displace - size.x;\n"
"    tc = R1 * displace + halfTemp;\n"
"    c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    displace = displace - size.x;\n"
"    tc = R1 * displace + halfTemp;\n"
"    c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    displace = displace - size.x;\n"
"    tc = R1 * displace + halfTemp;\n"
"    c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    displace = displace - size.x;\n"
"    tc = R1 * displace + halfTemp;\n"
"    c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    displace = displace - size.x;\n"
"    tc = R1 * displace + halfTemp;\n"
"    c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    displace = displace - size.x;\n"
"    tc = R1 * displace + halfTemp;\n"
"    c = texture2D( u_fragmentMap0, tc ).rgb;\n"
"    color = c * strength.y + color;\n"
"\n"
"    vec3 R0 = texture2D( u_fragmentMap0, pos ).rgb;\n"
"\n"
"    color = clamp( u_fragmentParm1.x * color + u_fragmentParm1.y, 0.0, 1.0 );\n"
"\n"
"    color = mix( color, R0, u_fragmentParm0.z );\n"
"\n"
"    float R1F = dot( color, vec3( 0.3, 0.5, 0.1 ) );\n"
"    color = mix( vec3( R1F ), color, u_fragmentParm2.x );\n"
"    color = mix( vec3( u_fragmentParm3.y ), color, u_fragmentParm3.x );\n"
"    R1F = R1F * u_fragmentParm4.a;\n"
"    color = mix( color, u_fragmentParm4.xyz, R1F );\n"
"    color = color * 0.95 + u_fragmentParm5.xyz;\n"
"\n"
"    gl_FragColor = vec4( color, 1.0 );\n"
"}\n"
;
