/* Copyright (c) 2002-2012 Croteam Ltd. 
This program is free software; you can redistribute it and/or modify
it under the terms of version 2 of the GNU General Public License as published by
the Free Software Foundation


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Modeler.rc
//
#define ID_EXPORT                       3
#define ID_CLEAR_SELECTION              3
#define ID_SELECT_ALL                   4
#define IDD_ABOUTBOX                    100
#define ID_MAGNIFY_MORE                 106
#define ID_MAGNIFY_LESS                 107
#define ID_TEST_MODE_WND                109
#define IDR_MAINFRAME                   128
#define IDR_MDLDOCTYPE                  129
#define IDR_ANIMCONTROL                 130
#define IDR_SCRIPTDOCTYPE               130
#define IDR_TEXTURECONTROL              131
#define IDR_SCRIPTCONTROL               132
#define IDD_CHOOSEANIMATION             134
#define IDD_INFO_GLOBAL                 140
#define IDB_COLORS_PALETTE              140
#define IDD_COLORS_PALETTE              143
#define IDI_PICK                        144
#define IDD_NEW_PROGRESS                145
#define IDD_INFO_NONE                   146
#define IDR_POPUP_MENU                  147
#define IDD_REMOVE_TEXTURE              147
#define IDD_CREATE_TEXTURE              148
#define IDR_VIEW_POPUP                  151
#define IDR_MODEL_VIEW_POPUP            151
#define IDR_MAPPING_VIEW_POPUP          152
#define IDD_PLEASE_WAIT                 154
#define IDR_MIPANDLIGHT                 155
#define IDD_INFO_ANIMATION              156
#define IDR_RENDERCONTROL               157
#define IDD_INFO_POSITION               157
#define IDR_STAINSCONTROL               158
#define IDD_INFO_SURF                   159
#define IDR_SHADINGANDSHADOWCONTROL     159
#define IDD_PREFERENCES                 160
#define IDD_TEST_MODE_DIALOG            163
#define IDC_NULLCURSOR                  164
#define IDD_REMOVE_WORKING_TEXTURE      164
#define IDD_CHOOSE_WORKING_TEXTURE      165
#define IDI_PATCH_ACTIVE                165
#define IDD_CHOOSE_FLOOR_TEXTURE        166
#define IDI_PATCH_INACTIVE              166
#define IDD_PATCH_PALETTE               167
#define IDI_PATCH_EXIST                 167
#define IDD_HELP_MOUSE                  170
#define IDD_SETAMBIENT                  171
#define IDR_ROTATE                      172
#define IDD_INFO_COLLISION              172
#define IDD_INFO_RENDERING              173
#define IDR_MAPPING                     173
#define IDD_CHOOSE_CURRENT_SURFACE      174
#define IDR_FX_CONTROL                  174
#define IDD_MULTIPLY_MAPPING            176
#define IDD_LINKED_SURFACES             177
#define IDD_INFO_COLORIZING_SURFACE     178
#define IDD_AUTO_MIP_MODELING           179
#define IDD_INFO_ATTACHING_PLACEMENT    180
#define IDD_INFO_ATTACHING_SOUND        181
#define IDD_NEW_TEXTURE_SIZE            182
#define IDD_CREATE_SPECULAR_TEXTURE     183
#define IDD_EXPORT_FOR_SKINNIG          189
#define IDR_COLOR_BUTTON                204
#define IDD_NUMERIC_ALPHA               205
#define IDD_INFO_MIP                    206
#define IDD_CREATE_REFLECTION_TEXTURE   207
#define IDC_TEX_SIZE                    444
#define IDC_LIST1                       1000
#define IDC_EDIT_H                      1010
#define IDC_EDIT_P                      1011
#define IDC_EDIT_B                      1012
#define IDC_NO_OF_VERTICES_T            1012
#define IDC_NO_OF_POLYGONS_T            1013
#define IDC_NO_OF_ANIMATIONS_T          1014
#define IDC_NO_OF_FRAMES_T              1015
#define IDC_TRANSPARENT_T               1016
#define IDC_NO_OF_TRIANGLES_T           1016
#define IDC_FLAT_T                      1017
#define IDC_ALPHA_GOURAUD_T             1018
#define IDC_CURRENT_MIP_T               1018
#define IDC_HIGH_QUALITY_T              1018
#define IDC_CURRENT_FACTOR_T            1018
#define IDC_TEX_SIZE_T                  1019
#define IDC_CURRENT_MIP_FACTOR_T        1020
#define IDC_MODEL_DISTANCE_T            1020
#define IDC_MAX_SHADOW_T                1020
#define IDC_DOUBBLE_SIDED_T             1021
#define IDC_NO_OF_MIP_MODELS_T          1021
#define IDC_WND_SIZE_T                  1022
#define IDC_MODEL_FACTOR_T              1022
#define IDC_NO_OF_VERTICES              1023
#define IDC_NO_OF_POLYGONS              1024
#define IDC_NO_OF_ANIMATIONS            1025
#define IDC_NO_OF_FRAMES                1026
#define IDC_TRANSPARENT                 1027
#define IDC_REFLECTIONS_T               1027
#define IDC_FLAT                        1028
#define IDC_ALPHA_GOURAUD               1029
#define IDC_CURRENT_MIP                 1029
#define IDC_HIGH_QUALITY                1029
#define IDC_CURRENT_FACTOR              1029
#define IDC_CURRENT_MIP_FACTOR          1030
#define IDC_COLOR_FILL                  1030
#define IDC_MODEL_DISTANCE              1030
#define IDC_ALPHA_ADD                   1030
#define IDC_SPECULAR_T                  1030
#define IDC_DOUBBLE_SIDED               1031
#define IDC_DOUBLE_SIDED                1031
#define IDC_NO_OF_MIP_MODELS            1031
#define IDC_DIFUSE_T                    1031
#define IDC_CURRENT_MIP_MODEL           1031
#define IDC_EDIT1                       1032
#define IDC_EDIT_HEADING                1032
#define IDC_EDIT_COLOR_NAME             1032
#define IDC_WINDOW_SIZE                 1032
#define IDC_NO_SHADING                  1032
#define IDC_ALPHA_MULTIPLY              1032
#define IDC_MODEL_SWITCH_FACTOR         1032
#define IDC_EDIT_PITCH                  1033
#define IDC_DOUBLE_CLIP_POLYGONS        1033
#define IDC_CLIP_POLYGONS               1033
#define IDC_REFLECTIONS                 1033
#define IDC_EDIT_BANKING                1034
#define IDC_USE_REFLECTIONS             1034
#define IDC_NO_OF_TRIANGLES             1034
#define IDC_USE_DIFUSE                  1034
#define IDC_SPECULAR                    1034
#define IDC_STATIC_HEADING              1035
#define IDC_INVISIBLE                   1035
#define IDC_SPECULAR_COLOR_T            1035
#define IDC_STATIC_PITCH                1036
#define IDC_COLOR_PALETTE_BUTTON1       1036
#define IDC_COLOR_PALETTE_BUTTON_BASE   1036
#define IDC_USE_REFLECTIONS2            1036
#define IDC_REFLECTION_COLOR_T          1036
#define IDC_USE_REFLECTIVITY            1036
#define IDC_STATIC_BANKING              1037
#define IDC_COLOR_PALETTE_BUTTON2       1037
#define IDC_USE_SPECULAR                1037
#define IDC_DIFUSE                      1037
#define IDC_EDIT_X                      1038
#define IDC_COLOR_PALETTE_BUTTON3       1038
#define IDC_MAX_SHADOW                  1038
#define IDC_USE_BUMP                    1038
#define IDC_EDIT_Y                      1039
#define IDC_COLOR_PALETTE_BUTTON4       1039
#define IDC_BUMP_T                      1039
#define IDC_DETAIL                      1039
#define IDC_EDIT_Z                      1040
#define IDC_COLOR_PALETTE_BUTTON5       1040
#define IDC_BUMP                        1040
#define IDC_STATIC_X                    1041
#define IDC_COLOR_PALETTE_BUTTON6       1041
#define IDC_BUMP_COLOR_T                1041
#define IDC_API                         1041
#define IDC_STATIC_Y                    1042
#define IDC_COLOR_PALETTE_BUTTON7       1042
#define IDC_DIFUSE_COLOR_T              1042
#define IDC_STATIC_Z                    1043
#define IDC_COLOR_PALETTE_BUTTON8       1043
#define IDC_COLOR_PALETTE_BUTTON9       1044
#define IDC_EDIT_Z2                     1044
#define IDC_COLOR_PALETTE_BUTTON10      1045
#define IDC_STATIC_Z2                   1045
#define IDC_SPECULAR_COLOR_T2           1045
#define IDC_COLOR_PALETTE_BUTTON11      1046
#define IDC_EDIT_LIGHT_DISTANCE         1046
#define IDC_REFLECTION_COLOR_T2         1046
#define IDC_COLOR_PALETTE_BUTTON12      1047
#define IDC_STATIC_Z3                   1047
#define IDC_COLOR_PALETTE_BUTTON13      1048
#define IDC_EDIT_FOW                    1048
#define IDC_COLOR_PALETTE_BUTTON14      1049
#define IDC_STATIC_FOW                  1049
#define IDC_COLOR_PALETTE_BUTTON15      1050
#define IDC_COLOR_PALETTE_BUTTON16      1051
#define IDC_COLOR_PALETTE_BUTTON17      1052
#define IDC_COLOR_PALETTE_BUTTON18      1053
#define IDC_COLOR_PALETTE_BUTTON19      1054
#define IDC_COLOR_PALETTE_BUTTON20      1055
#define IDC_COLOR_PALETTE_BUTTON21      1056
#define IDC_COLOR_PALETTE_BUTTON22      1057
#define IDC_COLOR_PALETTE_BUTTON23      1058
#define IDC_COLOR_PALETTE_BUTTON24      1059
#define IDC_COLOR_PALETTE_BUTTON25      1060
#define IDC_COLOR_PALETTE_BUTTON26      1061
#define IDC_COLOR_PALETTE_BUTTON27      1062
#define IDC_COLOR_PALETTE_BUTTON28      1063
#define IDC_COLOR_PALETTE_BUTTON29      1064
#define IDC_COLOR_PALETTE_BUTTON30      1065
#define IDC_COLOR_PALETTE_BUTTON31      1066
#define IDC_COLOR_PALETTE_BUTTON32      1067
#define IDC_CURRENT_COLOR               1068
#define IDC_COLOR_PALETTE_BUTTON_END    1068
#define IDC_PICK_COLOR                  1069
#define IDC_PROGRESS1                   1070
#define IDC_PROGRESS_MESSAGE            1071
#define ID_REMOVE                       1073
#define IDC_ADD_TO_MODELER_CHECK        1077
#define IDC_SOURCE_SIZE                 1078
#define IDC_CREATED_SIZE                1079
#define IDC_ALLOWED_SIZE                1080
#define IDC_EDIT_TRANSPARENCY           1082
#define IDC_IS_FILTER_CHECK_BOX         1083
#define IDC_CHOOSE_FILTER_COLOR         1085
#define IDC_FILTER_COLOR_T              1086
#define IDC_SET_TRANSPARENCY_T          1087
#define IDC_CREATED_TEXTURE_NAME_T      1088
#define IDC_MESSAGE_ARGUMENT_T          1089
#define IDC_MESSAGE_T                   1090
#define IDC_MODE                        1091
#define IDC_ANIM_NAME_T                 1093
#define IDC_ANIM_SPEED_T                1094
#define IDC_ANIM_FRAMES_T               1095
#define IDC_ANIM_FRAMES                 1096
#define IDC_ANIM_SPEED                  1097
#define IDC_ANIM_TIME_PASSED_T          1098
#define IDC_ANIM_TIME_PASSED            1099
#define IDC_ANIM_CURRENT_FRAME_T        1100
#define IDC_ANIM_CURRENT_FRAME          1101
#define IDC_ANIMATION_LENGHT_T          1102
#define IDC_ANIM_NAME                   1103
#define IDC_ANIM_STATE_T2               1104
#define IDC_ANIM_STATE                  1105
#define IDC_SURFACE_NAME                1105
#define IDC_SURFACE_HEADING_T           1106
#define IDC_ANIMATION_LENGHT            1106
#define IDC_SURFACE_PITCH_T             1107
#define IDC_SURFACE_BANKING_T           1108
#define IDC_SURFACE_OFFSET_X_T          1109
#define IDC_SURFACE_OFFSET_Y_T          1110
#define IDC_SURFACE_ZOOM_T              1111
#define IDC_SURFACE_HEADING             1112
#define IDC_SURFACE_PITCH               1113
#define IDC_SURFACE_BANKING             1114
#define IDC_SURFACE_OFFSET_X            1115
#define IDC_SURFACE_OFFSET_Y            1116
#define IDC_SURFACE_ZOOM                1117
#define IDC_PREFS_COPY                  1118
#define IDC_MIP_MODEL                   1118
#define IDC_PREFS_MAXIMIZE              1119
#define IDC_PREFS_WINDOW_FIT            1120
#define IDC_PREFS_ALLWAYS_LAMP          1121
#define IDC_PREFS_SET_DEFAULT_COLORS    1122
#define IDC_MODEL_PAPER                 1123
#define IDC_MODEL_INK                   1124
#define IDC_MAPPING_ACTIVE_INK          1125
#define IDC_MAPPING_INACTIVE_INK        1126
#define IDC_WIN_BCG_COLOR               1127
#define IDC_COMBO_FLOOR_TEXTURE         1128
#define IDC_FLOOR_IS_VISIBLE_BY_DEFAULT 1128
#define IDC_COMBO_WIN_BCG_TEXTURE       1129
#define IDC_ADD_WORKING_TEXTURE         1130
#define IDC_REMOVE_WORKING_TEXTURE      1131
#define IDC_MODELER_STARTUP_MODE        1132
#define IDC_PREFS_ALLOW_SOUND_LOCK      1132
#define IDC_TEST_STARTUP_MODE           1134
#define IDC_DEFAULT_AMBIENT_COLOR       1134
#define IDC_TEST_FULL_SCREEN_MODE       1135
#define ID_OK_BUTTON                    1135
#define IDC_PREFS_ALLWAYS_BCG           1135
#define IDC_EXPORT_WIRE_COLOR           1135
#define IDC_MAPPING_PAPER               1136
#define IDC_EDIT_PATCH_NAME             1137
#define IDC_PATCH_BUTTON1               1138
#define IDC_PATCH_BUTTON_BASE           1138
#define IDC_PATCH_BUTTON2               1139
#define IDC_PATCH_BUTTON3               1140
#define IDC_PATCH_BUTTON4               1141
#define IDC_PATCH_BUTTON5               1142
#define IDC_PATCH_BUTTON6               1143
#define IDC_PATCH_BUTTON7               1144
#define IDC_PATCH_BUTTON8               1145
#define IDC_PATCH_BUTTON9               1146
#define IDC_PATCH_BUTTON10              1147
#define IDC_PATCH_BUTTON11              1148
#define IDC_PATCH_BUTTON12              1149
#define IDC_PATCH_BUTTON13              1150
#define IDC_PATCH_BUTTON14              1151
#define IDC_PATCH_BUTTON15              1152
#define IDC_PATCH_BUTTON16              1153
#define IDC_PATCH_BUTTON17              1154
#define IDC_PATCH_BUTTON18              1155
#define IDC_ALPHA                       1155
#define IDC_PATCH_BUTTON19              1156
#define IDC_PATCH_BUTTON20              1157
#define IDC_PATCH_BUTTON21              1158
#define IDC_PATCH_BUTTON22              1159
#define IDC_PATCH_BUTTON23              1160
#define IDC_PATCH_BUTTON24              1161
#define IDC_PATCH_BUTTON25              1162
#define IDC_PATCH_BUTTON26              1163
#define IDC_PATCH_BUTTON27              1164
#define IDC_PATCH_BUTTON28              1165
#define IDC_PATCH_BUTTON29              1166
#define IDC_PATCH_BUTTON30              1167
#define IDC_PATCH_BUTTON31              1168
#define IDC_PATCH_BUTTON32              1169
#define IDC_EDIT_PATCH_STRETCH          1170
#define IDC_LIST2                       1176
#define IDW_THUMBNAIL_WND               1177
#define IDC_COMBO1                      1178
#define IDC_COMBO2                      1179
#define IDC_EDIT_WIDTH                  1179
#define IDC_EDIT_XMIN                   1179
#define IDC_EDIT_HEIGHT                 1180
#define IDC_EDIT_YMIN                   1180
#define IDC_EDIT_LENGHT                 1181
#define IDC_EDIT_ZMIN                   1181
#define IDC_STATIC_WIDTH                1182
#define IDC_STATIC_XMIN                 1182
#define IDC_STATIC_HEIGHT               1183
#define IDC_STATIC_YMIN                 1183
#define IDC_STATIC_LENGHT               1184
#define IDC_STATIC_ZMIN                 1184
#define IDC_STATIC_XCENTER              1185
#define IDC_STATIC_XMAX                 1185
#define IDC_EDIT_XCENTER                1186
#define IDC_EDIT_XMAX                   1186
#define IDC_EDIT_YDOWN                  1187
#define IDC_EDIT_YMAX                   1187
#define IDC_EDIT_ZCENTER                1188
#define IDC_EDIT_ZMAX                   1188
#define IDC_STATIC_YDOWN                1189
#define IDC_STATIC_YMAX                 1189
#define IDC_STATIC_ZCENTER              1190
#define IDC_STATIC_ZMAX                 1190
#define IDC_PHONG                       1192
#define IDC_FLAT_SHADING                1193
#define IDC_MATTE                       1194
#define IDC_SHINY                       1195
#define IDC_METAL                       1196
#define IDC_USE_ALPHA                   1197
#define IDC_OPAQUE                      1197
#define IDC_SKIP_ALPHA                  1198
#define IDC_TRANSLUCENT                 1198
#define IDC_ZERO_TRANSPARENCY           1199
#define IDC_FULL_BRIGHT                 1200
#define IDC_SURFACE_COLOR               1201
#define IDC_COPY                        1202
#define IDC_PASTE                       1203
#define IDC_FILTER                      1205
#define IDC_ALL_SURFACES                1206
#define IDC_FILTER_T                    1208
#define IDC_SURFACE_COLOR_T             1209
#define IDC_SHADING_T                   1209
#define IDC_TRANSLUCENCY_T              1210
#define IDC_FLAT_PROJECTION             1212
#define IDC_SURFACE_LIST                1213
#define IDC_SURFACE_X_OFFSET            1215
#define IDC_SURFACE_Y_OFFSET            1216
#define IDC_APPLICATION_PATH            1216
#define IDC_H_EQ_W                      1219
#define IDC_L_EQ_W                      1220
#define IDC_L_EQ_H                      1221
#define IDC_PREVIOUS_COLLISION_BOX      1223
#define IDC_NEXT_COLLISION_BOX          1224
#define IDC_ADD_COLLISION_BOX           1225
#define IDC_REMOVE_COLLISION_BOX        1226
#define IDC_COLLISION_BOX_INDEX         1227
#define IDC_COLLISION_BOX_NAME          1228
#define IDC_DEFAULT_AMBIENT             1229
#define IDC_ALLIGN_TO_SIZE              1229
#define IDC_DEFAULT_HEADING             1230
#define IDC_ADD_SURFACE                 1230
#define IDC_DEFAULT_PITCH               1231
#define IDC_DEFAULT_BANKING             1232
#define IDC_SURFACE_COMBO               1233
#define IDC_DEFAULT_FOW                 1233
#define IDC_POLYGONS_IN_SURFACE         1234
#define IDC_EDIT_SURFACE_NAME           1235
#define IDC_VERTICES_TO_REMOVE          1236
#define IDC_SURFACE_PRESERVING_FACTOR   1237
#define IDC_ATTACHING_PLACEMENT_INDEX_T 1237
#define IDC_PREVIOUS_ATTACHING_PLACEMENT 1238
#define IDC_ATTACHING_PLACEMENT_NAME    1239
#define IDC_NEXT_ATTACHING_PLACEMENT    1240
#define IDC_ADD_ATTACHING_PLACEMENT     1241
#define IDC_REMOVE_ATTACHING_PLACEMENT  1242
#define IDC_ATTACHING_PLACEMENT_X_OFFSET 1243
#define IDC_ATTACHING_PLACEMENT_Y_OFFSET 1244
#define IDC_ATTACHING_PLACEMENT_Z_OFFSET 1245
#define IDC_ATTACHING_PLACEMENT_X_OFFSET_T 1246
#define IDC_ATTACHING_PLACEMENT_Y_OFFSET_T 1247
#define IDC_ATTACHING_PLACEMENT_Z_OFFSET_T 1248
#define IDC_ATTACHING_PLACEMENT_HEADING_T 1249
#define IDC_ATTACHING_PLACEMENT_PITCH_T 1250
#define IDC_ATTACHING_PLACEMENT_BANKING_T 1251
#define IDC_ATTACHING_PLACEMENT_HEADING 1252
#define IDC_ATTACHING_PLACEMENT_PITCH   1253
#define IDC_ATTACHING_PLACEMENT_BANKING 1254
#define IDC_ATTACHING_MODEL_T           1255
#define IDC_BROWSE_MODEL                1256
#define IDC_ATTACHING_VERTICES          1257
#define IDC_IS_VISIBLE                  1258
#define IDC_MODEL_T                     1259
#define IDC_VERTICES_T                  1260
#define IDC_HAS_PATCHES                 1261
#define IDC_MODEL_ANIMATION_T           1261
#define IDC_HAS_ATTACHED_MODELS         1262
#define IDC_ATTACHMENT_MODEL_ANIMATION_COMBO 1262
#define IDC_ATTACHING_SOUND_NONE        1263
#define IDC_IS_LOOPING                  1264
#define IDC_IS_PLAYING                  1265
#define IDC_SOUND_T                     1266
#define IDC_ATTACHING_SOUND_T           1267
#define IDC_BROWSE_SOUND                1269
#define IDC_SOUND_START_DELAY_T         1270
#define IDC_SOUND_START_DELAY           1271
#define IDC_COLLIDE_AS_BOX              1272
#define IDC_NEW_WIDTH                   1275
#define IDC_NEW_HEIGHT                  1276
#define IDC_SPECULAR_COLOR              1277
#define IDC_REFLECTION_COLOR            1278
#define IDC_SPECULAR_EXPONENT           1278
#define IDC_BUMP_COLOR                  1279
#define IDC_AMBIENT_COLOR               1280
#define IDC_DIFUSE_COLOR                1280
#define IDC_LIGHT_COLOR                 1281
#define IDC_SIZE_IN_PIXELS              1282
#define IDC_PREVIEW_FRAME               1283
#define IDC_GRAPH_FRAME                 1284
#define IDC_NUMERIC_EXPONENT_T          1285
#define IDC_FRAME_RIGHT                 1285
#define IDW_SPECULAR_GRAPH              1286
#define IDC_FRAME_BACK                  1286
#define IDW_SPECULAR_PREVIEW            1287
#define IDC_FRAME_LEFT                  1287
#define IDC_FRAME_BOTTOM                1288
#define IDC_FRAME_DOWN                  1288
#define IDC_AUTO_ROTATE                 1289
#define IDC_FRAME_TOP                   1290
#define IDC_FRAME_UP                    1290
#define IDC_FRAME_FRONT                 1291
#define IDW_REFLECTION_PREVIEW          1292
#define IDW_UP                          1293
#define IDW_FRONT                       1293
#define IDW_DOWN                        1294
#define IDW_RIGHT                       1295
#define IDW_BACK                        1296
#define IDW_LEFT                        1297
#define IDC_PLANAR_MAPPING              1300
#define IDC_SPHERICAL_MAPPING           1301
#define IDC_SHADING                     1301
#define IDC_CYLINDRICAL_MAPPING         1302
#define IDC_TRANSLUCENCY                1302
#define IDC_DIFFUSE_COLOR_T             1303
#define IDC_SELECT_ALL_SURFACES         1304
#define IDC_WIRE_FRAME                  1306
#define IDC_COLORED_SURFACES            1307
#define IDC_COLORED_SURFACES_WITH_NUMBERS 1308
#define IDC_EXPORT_PICTURE_SIZE         1310
#define IDC_SURFACE_LIST_T              1311
#define IDC_EXPORT_PAPER_COLOR          1312
#define IDC_EXPORT_FILE_NAME_T          1313
#define ID_RENDER_BBOX                  32700
#define ID_RENDER_WIRE_NAKED            32701
#define ID_RENDER_WIRE_SOLID            32702
#define ID_RENDER_FLAT_NAKED            32703
#define ID_RENDER_FLAT_COLOR            32704
#define ID_RENDER_FLAT_TEXTURE          32705
#define ID_RENDER_GOURAUD_NAKED         32706
#define ID_RENDER_GOURAUD_TEXTURE       32707
#define ID_RENDER_PHONG_NAKED           32708
#define ID_RENDER_PHONG_TEXTURE         32709
#define ID_PREFS_CHOOSE_PICTURE         32710
#define ID_BACKGROUND_COLOR             32713
#define ID_BACKGROUND_PICTURE           32714
#define ID_PREFS_CHOOSE_INK             32718
#define ID_PREFS_CHOOSE_PAPER           32719
#define ID_ANIM_PLAY                    32788
#define ID_VIEW_ANIMCONTROL             32789
#define ID_ANIM_PREVANIM                32790
#define ID_ANIM_NEXTANIM                32791
#define ID_ANIM_PREVFRAME               32792
#define ID_ANIM_NEXTFRAME               32793
#define ID_ANIM_CHOOSE                  32795
#define ID_SHOW_INFO                    32796
#define ID_TEXTURE_CHOOSE               32797
#define ID_MIP_PRECIZE                  32798
#define ID_ANIM_MIP_ROUGH               32800
#define ID_ANIM_MIP_PRECIZE             32801
#define ID_OPT_AUTO_MIP_MODELING        32802
#define ID_ANIM_ROTATION                32804
#define ID_WINDOW_CLOSE                 32806
#define ID_WINDOW_TOGGLEMAX             32808
#define ID_VIEW_COLOR_PALETTE           32875
#define ID_VIEW_INFO                    32876
#define ID_REND_WIRE_NAKED              32925
#define ID_REND_WIRE_ONOFF              32925
#define ID_REND_WIRE_SOLID              32926
#define ID_REND_HIDDEN_LINES            32926
#define ID_REND_FLAT_NAKED              32927
#define ID_REND_NO_TEXTURE              32927
#define ID_REND_FLAT_COLOR              32928
#define ID_REND_SURFACE_COLORS          32928
#define ID_REND_FLAT_TEXTURE            32929
#define ID_REND_ON_COLORS               32929
#define ID_REND_GOURAUD_NAKED           32930
#define ID_REND_GOURAUD_TEXTURE         32931
#define ID_REND_PHONG_NAKED             32932
#define ID_REND_SHADING_NONE            32932
#define ID_REND_PHONG_TEXTURE           32933
#define ID_REND_BBOX                    32934
#define ID_REND_BBOX_FRAME              32934
#define ID_SHADOW_NONE                  32935
#define ID_SHADOW_APPROXIMATE           32936
#define ID_SHADOW_EXACT                 32937
#define ID_BACKG_COLOR                  32938
#define ID_BACKG_PICTURE                32939
#define ID_PREFS_CHANGE_INK             32943
#define ID_PREFS_CHANGE_PAPER           32944
#define ID_PREFS_CHANGE_PICTURE         32945
#define ID_FILE_ADD_TEXTURE             32946
#define ID_COMBO_CHOOSE_TEXTURE         32947
#define ID_FILE_REMOVE_TEXTURE          32948
#define ID_FILE_CREATE_TEXTURE          32952
#define ID_VIEW_TEXTURECONTROL          32955
#define ID_SCRIPT_OPEN                  32956
#define ID_SCRIPT_MAKE_MODEL            32957
#define ID_UPDATE_FRAMES                32958
#define ID_UPDATE_ANIMATIONS            32959
#define ID_UPDATE_MIPMODELS             32960
#define ID_SCRIPT_UPDATE_ANIMATIONS     32961
#define ID_SCRIPT_UPDATE_MIPMODELS      32962
#define ID_LIGHT_ON                     32966
#define ID_LIGHT_COLOR                  32967
#define ID_REND_OFF_COLORS              32968
#define ID_REND_USE_TEXTURE             32969
#define ID_REND_SHADING_LAMBERT         32970
#define ID_REND_SHADING_GOURAUD         32971
#define ID_REND_SHADING_PHONG           32972
#define ID_REND_BBOX_ALL                32973
#define ID_REND_WHITE_TEXTURE           32974
#define ID_REND_WIRE                    32975
#define ID_BUTTON32977                  32977
#define ID_REND_TEXTURE_ON              32982
#define ID_MAPPING_ON                   32983
#define ID_NEXT_SURFACE                 32987
#define ID_WINDOW_FIT                   32988
#define ID_VIEW_ALL_SURFACES            32989
#define ID_FILE_PREFERENCES             32991
#define ID_WINDOW_CENTER                32992
#define ID_VIEW_MIPLIGHTCONTROL         32993
#define ID_VIEW_SCRIPTCONTROL           32994
#define ID_BACKGROUND_TEXTURE           32995
#define ID_TAKE_SCREEN_SHOOT            32996
#define ID_ANIMATE_BACKGROUND           32997
#define ID_REND_LAMBERT_SHADING         33002
#define ID_REND_WIRE_FRAME              33008
#define ID_VIEW_RENDERCONTROL           33015
#define ID_PICK_COLOR_MODE              -32519
#define ID_RENDER_FLOOR                 33018
#define ID_CHANGE_FLOOR_PICTURE         33020
#define ID_REND_FLOOR                   33021
#define ID_STAINS_REMOVE                33025
#define ID_STAINS_CHOOSE                33026
#define ID_STAINS_ADD                   33027
#define ID_STAINS_DELETE                33028
#define ID_STAINS_INSERT                33029
#define ID_STAINS_PREVIOUS_STAIN        33030
#define ID_STAINS_NEXT_STAIN            33031
#define ID_VIEW_STAINSCONTROL           33032
#define ID_VIEW_SHADINGANDSHADOWCONTROL 33033
#define ID_VIEW_STAINS_PALETTE          33034
#define ID_VIEW_PATCHES_PALETTE         33035
#define ID_SHADOW_WORSE                 33036
#define ID_SHADOW_BETTER                33037
#define ID_FALL_DOWN                    33038
#define ID_ROUND_ANGLES                 33039
#define ID_VIEW_HELP_MOUSE              33040
#define ID_CHANGE_AMBIENT               33041
#define ID_REND_SHINY                   33042
#define ID_REND_METAL                   33043
#define ID_REND_MATTE                   33044
#define ID_SAVE_THUMBNAIL               33045
#define ID_FRAME_RATE                   33046
#define ID_RESTART_ANIMATIONS           33048
#define ID_HEADING                      33050
#define ID_PITCH                        33051
#define ID_BANKING                      33052
#define ID_VIEW_ROTATE_SURFACE          33054
#define ID_VIEW_ROTATE                  33055
#define ID_COLLISION_BOX                33057
#define ID_CENTER_VIEWER                33060
#define ID_RESET_VIEWER                 33061
#define ID_DOLLY_VIEWER                 33062
#define ID_REND_PHONG                   33063
#define ID_PREV_SURFACE                 -32472
#define ID_DOLLY_LIGHT                  33065
#define ID_DOLLY_LIGHT_COLOR            33066
#define ID_SHOW_ALL_BARS                33067
#define ID_TOGGLE_ALL_BARS              33068
#define ID_LOAD_MAPPING                 33069
#define ID_SAVE_MAPPING                 33070
#define ID_EDIT_COPY_ALL                33071
#define ID_EDIT_PASTE_ALL               33072
#define ID_VIEW_MAPPING                 33077
#define ID_CHOOSE_ACTVE_SURFACE         33078
#define ID_LIST_SURFACES                33079
#define ID_LIST_ANIMATIONS              33079
#define ID_SURFACE_NUMBERS              33082
#define ID_LINK_SURFACES                33083
#define ID_PREVIOUS_TEXTURE             33084
#define ID_NEXT_TEXTURE                 33085
#define ID_RECREATE_TEXTURE             33087
#define ID_COLORIZING_MODE              33088
#define ID_CREATE_MIP_MODELS            33090
#define ID_PICK_VERTEX                  -32444
#define ID_SET_CENTER_VERTEX            33094
#define ID_SET_FRONT_VERTEX             33095
#define ID_SET_UP_VERTEX                33096
#define ID_DOLLY_MIP_MODELING           33098
#define ID_ANIM_PLAY_ONCE               -32437
#define ID_PLAY_ANIM_ONCE               33100
#define ID_NEW_TEXTURE_SIZE             33101
#define ID_TILE_TEXTURE                 33102
#define ID_RESET_VIEWER_TO_0            -32433
#define IDC_PATCH_FILE_T                33103
#define IDC_PATCH_STRETCH_T             33104
#define IDC_PATCH_NAME_T                33105
#define ID_ADD_REFLECTION_TEXTURE       33106
#define ID_REMOVE_REFLECTION            33107
#define ID_ADD_SPECULAR                 33110
#define ID_COPY_COLOR                   33111
#define ID_PASTE_COLOR                  33112
#define ID_REMOVE_SPECULAR              33112
#define ID_NUMERIC_ALPHA                33113
#define ID_EDIT_SPECULAR                33113
#define ID_BUMP_TEXTURE                 33119
#define ID_REMOVE_BUMP_TEXTURE          33120
#define ID_ADD_BUMP_TEXTURE             33121
#define ID_REMOVE_BUMP_MAP              33122
#define ID_SMOOTH_MAPPING               33123
#define ID_CYLINDRICAL_MAPPING          33124
#define ID_SPHERICAL_MAPPING            33125
#define ID_CREATE_REFLECTION_TEXTURE    33127
#define ID_VIEW_FXCONTROL               33128
#define ID_SKIN_TEXTURE                 -32406
#define ID_EXPORT_SURFACES              33134
#define ID_NEXT_BCG_TEXTURE             -32400
#define ID_PREVIOUS_BCG_TEXTURE         -32399
#define ID_EXPORT_FOR_SKINING           33138
#define ID_RENDER_SURFACES_IN_COLORS    33140
#define ID_Z_TRANSLATION                33141
#define ID_Z_SPEED                      33142
#define ID_Z_LOOP_TIMES                 33143
#define ID_VIEW_AXIS                    33144
#define ID_BUTTON33145                  33145
#define ID_BUTTON33146                  33146
#define ID_TOGGLE_ALL_SURFACES          33149
#define ID_KEY_A                        33151
#define ID_KEY_T                        33152
#define ID_ANIM_FIRST                   33153
#define ID_ANIM_LAST                    33154
#define ID_TOGGLE_MEASURE_VTX           33155
#define ID_RESET_MEASURE_VTX            33156
#define ID_FIRST_FRAME                  -32379
#define ID_LAST_FRAME                   -32378
#define ID_TESSELLATE_MORE              33159
#define ID_TESSELLATE_LESS              33160
#define IDW_TOOLBAR_MAIN                0xE800
#define IDW_STATUS_BAR                  0xE801
#define IDW_TOOLBAR_ANIMATION           0xE802
#define IDW_TOOLBAR_TEXTURE             0xE803
#define IDW_TOOLBAR_STAINS              0xE804
#define IDW_TOOLBAR_SCRIPT              0xE805
#define IDW_TOOLBAR_MIP_AND_LIGHT       0xE806
#define IDW_TOOLBAR_RENDER              0xE807
#define IDW_TOOLBAR_SHADING_AND_SHADOW  0xE808
#define IDW_TOOLBAR_ROTATION            0xE809
#define IDW_TOOLBAR_MAPPING             0xE80A
#define IDW_TOOLBAR_FX                  0xE80B
#define IDS_INFO_TITLE                  61446
#define IDS_DEFAULT_FONT                61447
#define IDS_DEFAULT_ARIAL               61448

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         33161
#define _APS_NEXT_CONTROL_VALUE         1314
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
