
// blur
GLSL_SHADER const char BLUR_VERT[] =
"#version 100\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"attribute highp vec4 attr_Vertex;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;

GLSL_SHADER const char BLUR_FRAG[] =
"#version 100\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform sampler2D u_fragmentMap0;\n"
"\n"
"void main ( void ) { \n"
"    // ARBfp1 0.000000 \n"
"    // ARB_precision_hint_fastest; \n"
"    vec4 center;\n"
"    vec4 y_min;\n"
"    vec4 y_max;\n"
"    vec4 x_min;\n"
"    vec4 x_max;\n"
"    vec4 avg;\n"
"    center = gl_FragCoord;\n"
"    y_min = center;\n"
"    y_max = center;\n"
"    x_min = center;\n"
"    x_max = center;\n"
"    y_min.y = -2.0 + y_min.y;\n"
"    y_max.y = 3.0 + y_max.y;\n"
"    x_min.x = -4.0 + x_min.x;\n"
"    x_max.x = 2.0 + x_max.x;\n"
"    // program.env[0] = x \n"
"    center = u_windowCoords * center;\n"
"    y_min = u_windowCoords * y_min;\n"
"    y_max = u_windowCoords * y_max;\n"
"    x_min = u_windowCoords * x_min;\n"
"    x_max = u_windowCoords * x_max;\n"
"    // program.env[1] = y \n"
"    center = u_nonPowerOfTwo * center;\n"
"    y_min = u_nonPowerOfTwo * y_min;\n"
"    y_max = u_nonPowerOfTwo * y_max;\n"
"    x_min = u_nonPowerOfTwo * x_min;\n"
"    x_max = u_nonPowerOfTwo * x_max;\n"
"    // get colors from positions \n"
"    center = texture2D ( u_fragmentMap0 , center.xy, center.w );\n"
"    y_min = texture2D ( u_fragmentMap0 , y_min.xy, y_min.w );\n"
"    y_max = texture2D ( u_fragmentMap0 , y_max.xy, y_max.w );\n"
"    x_min = texture2D ( u_fragmentMap0 , x_min.xy, x_min.w );\n"
"    x_max = texture2D ( u_fragmentMap0 , x_max.xy, x_max.w );\n"
"    avg = y_min + center;\n"
"    avg = y_max + avg;\n"
"    avg = x_min + avg;\n"
"    avg = x_max + avg;\n"
"    avg = 0.2 * avg;\n"
"    gl_FragColor = avg;\n"
"}\n"
;

// blur_less_blurry
GLSL_SHADER const char BLUR_LESS_BLURRY_FRAG[] =
"#version 100 \n"
"\n"
"precision mediump float;\n"
"\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform sampler2D u_fragmentMap0;\n"
"\n"
"void main ( void ) { \n"
"    // ARBfp1 0.000000 \n"
"    // ARB_precision_hint_fastest; \n"
"    vec4 center;\n"
"    vec4 y_min;\n"
"    vec4 y_max;\n"
"    vec4 x_min;\n"
"    vec4 x_max;\n"
"    vec4 avg;\n"
"    center = gl_FragCoord;\n"
"    y_min = center;\n"
"    y_max = center;\n"
"    x_min = center;\n"
"    x_max = center;\n"
"    y_min.y = -1.0 + y_min.y;\n"
"    y_max.y = 2.0 + y_max.y;\n"
"    x_min.x = -3.0 + x_min.x;\n"
"    x_max.x = 1.0 + x_max.x;\n"
"    // program.env[0] = x \n"
"    center = u_windowCoords * center;\n"
"    y_min = u_windowCoords * y_min;\n"
"    y_max = u_windowCoords * y_max;\n"
"    x_min = u_windowCoords * x_min;\n"
"    x_max = u_windowCoords * x_max;\n"
"    // program.env[1] = y \n"
"    center = u_nonPowerOfTwo * center;\n"
"    y_min = u_nonPowerOfTwo * y_min;\n"
"    y_max = u_nonPowerOfTwo * y_max;\n"
"    x_min = u_nonPowerOfTwo * x_min;\n"
"    x_max = u_nonPowerOfTwo * x_max;\n"
"    // get colors from positions \n"
"    center = texture2D ( u_fragmentMap0 , center.xy, center.w );\n"
"    y_min = texture2D ( u_fragmentMap0 , y_min.xy, y_min.w );\n"
"    y_max = texture2D ( u_fragmentMap0 , y_max.xy, y_max.w );\n"
"    x_min = texture2D ( u_fragmentMap0 , x_min.xy, x_min.w );\n"
"    x_max = texture2D ( u_fragmentMap0 , x_max.xy, x_max.w );\n"
"    avg = y_min + center;\n"
"    avg = y_max + avg;\n"
"    avg = x_min + avg;\n"
"    avg = x_max + avg;\n"
"    avg = 0.2 * avg;\n"
"    gl_FragColor = avg;\n"
"}\n"
;

// desaturate
GLSL_SHADER const char DESATURATE_VERT[] =
"#version 100 \n"
"\n"
"precision mediump float;\n"
"\n"
"attribute highp vec4 attr_Vertex;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform vec4 u_vertexParm0;\n"
"uniform vec4 u_vertexParm1;\n"
"\n"
"varying vec4 var_TexCoord0;\n"
"varying vec4 var_TexCoord1;\n"
"\n"
"void main ( void ) { \n"
"    // ARBvp1 0.000000 \n"
"    // ARB_position_invariant ; \n"
"    // parameter 0 is the fraction from the current hue to the target hue to map \n"
"    // parameter 1.rgb is the target hue \n"
"    // texture2D 0 is _currentRender \n"
"    // nothing to do but pass the parameters along \n"
"    // 1 - fraction \n"
"    var_TexCoord0 = vec4(1.0) - u_vertexParm0;\n"
"    // fraction * target color \n"
"    var_TexCoord1 = u_vertexParm1 * u_vertexParm0;\n"
"\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"    // ====================================================================== \n"
"}\n"
;
GLSL_SHADER const char DESATURATE_FRAG[] =
"#version 100 \n"
"\n"
"precision mediump float;\n"
"\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform sampler2D u_fragmentMap0;\n"
"\n"
"varying vec4 var_TexCoord1;\n"
"varying vec4 var_TexCoord0;\n"
"\n"
"void main ( void ) { \n"
"    // ARBfp1 0.000000 \n"
"    // ARB_precision_hint_fastest; \n"
"    vec4 R0;\n"
"    vec4 SRC;\n"
"    // calculate the screen texcoord in the 0.0 to 1.0 range \n"
"    R0 = gl_FragCoord * u_windowCoords;\n"
"    // scale by the screen non-power-of-two-adjust \n"
"    R0 = R0 * u_nonPowerOfTwo;\n"
"    // load the screen render \n"
"    SRC = texture2D ( u_fragmentMap0 , R0.xy );\n"
"    // calculate the grey scale version of the color \n"
"    R0.x = SRC.x + SRC.y;\n"
"    R0.x = R0.x + SRC.z;\n"
"    R0 = vec4(R0.x * 0.33);\n"
"    // scale by the target color \n"
"    R0 = R0 * var_TexCoord1;\n"
"    // lerp between the source color and the target color \n"
"    gl_FragColor/*.xyz*/ = SRC * var_TexCoord0 + R0;\n"
"}\n"
;
