
// reflection cubemap(bumpyEnvironment)
GLSL_SHADER const char ES3_BUMPY_ENVIRONMENT_VERT[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"in highp vec4 attr_Vertex;\n"
"in lowp vec4 attr_Color;\n"
"in vec3 attr_Tangent;\n"
"in vec3 attr_Bitangent;\n"
"in vec3 attr_Normal;\n"
"in vec2 attr_TexCoord;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform highp mat4 u_modelMatrix;\n"
"uniform lowp float u_colorModulate; // 0 or 1/255\n"
"uniform lowp float u_colorAdd; // 0 or 1\n"
"uniform vec4 u_viewOrigin;\n"
"\n"
"out vec2 var_TexCoord;\n"
"out lowp vec4 var_Color;\n"
"out mat3 var_TangentToWorldMatrix;\n"
"out highp vec3 var_toEyeWorld; //karin: must highp in GLES\n"
"\n"
"void main(void)\n"
"{\n"
"    // texture 0 takes the unodified texture coordinates\n"
"    var_TexCoord = attr_TexCoord;\n"
"\n"
"    // texture 1 is the vector to the eye in global coordinates\n"
"    var_toEyeWorld = mat3(u_modelMatrix) * vec3(u_viewOrigin - attr_Vertex);\n"
"\n"
"    // texture 2 3 4 gets the transformed tangent\n"
"    mat3 matTangentToLocal = mat3(\n"
"        clamp(attr_Tangent, vec3(-1.0), vec3(1.0)),\n"
"        clamp(attr_Bitangent, vec3(-1.0), vec3(1.0)),\n"
"        clamp(attr_Normal, vec3(-1.0), vec3(1.0))\n"
"    );\n"
"    var_TangentToWorldMatrix = mat3(u_modelMatrix) * matTangentToLocal;\n"
"\n"
"    var_Color = " BYTE_COLOR(attr_Color) " * u_colorModulate + u_colorAdd;\n"
"\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
