
// reflection cubemap(bumpyEnvironment)
GLSL_SHADER const char ES3_BUMPY_ENVIRONMENT_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"in vec2 var_TexCoord;\n"
"in lowp vec4 var_Color;\n"
"in mat3 var_TangentToWorldMatrix;\n"
"in highp vec3 var_toEyeWorld; //karin: must highp in GLES\n"
"\n"
"uniform samplerCube u_fragmentCubeMap0;\n"
"uniform sampler2D u_fragmentMap1; // normal map\n"
"uniform lowp vec4 u_glColor;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    // per-pixel cubic reflextion map calculation\n"
"\n"
"    // texture 0 is the environment cube map\n"
"    // texture 1 is the normal map\n"
"\n"
"    // load the filtered normal map, then normalize to full scale,\n"
"    vec3 localNormal = texture(u_fragmentMap1, var_TexCoord).agb; // doom3's normal map is not rgb\n"
"    localNormal = localNormal * vec3(2.0) - vec3(1.0);\n"
"    localNormal.z = sqrt(max(0.0, 1.0 - localNormal.x * localNormal.x - localNormal.y * localNormal.y));\n"
"    localNormal = normalize(localNormal);\n"
"\n"
"    // transform the surface normal by the local tangent space\n"
"    vec3 globalNormal = var_TangentToWorldMatrix * localNormal;\n"
"\n"
"    // normalize vector to eye\n"
"    vec3 globalEye = normalize(var_toEyeWorld);\n"
"\n"
"    // calculate reflection vector\n"
"    float dotEN = dot(globalEye, globalNormal);\n"
"    vec3 globalReflect = 2.0 * (dotEN * globalNormal) - globalEye;\n"
"\n"
"    // read the environment map with the reflection vector\n"
"    vec3 reflectedColor = texture(u_fragmentCubeMap0, globalReflect).rgb;\n"
"\n"
"#if 0 // TDM\n"
"    // calculate fresnel reflectance.\n"
"    float q = 1.0 - dotEN;\n"
"    float fresnel = 3.0 * q * q * q * q;\n"
"    reflectedColor *= (fresnel + 0.4);\n"
"\n"
"    // tonemap to convert HDR values to range 0.0 - 1.0\n"
"    _gl_FragColor = vec4(reflectedColor / (vec3(1.0) + reflectedColor), 1.0) * u_glColor * var_Color;\n"
"#else // original DOOM3\n"
"    _gl_FragColor = vec4(reflectedColor, 1.0)/* * u_glColor * var_Color */;\n"
"#endif\n"
"}\n"
;
