
// colorProcess
GLSL_SHADER const char ES3_COLORPROCESS_VERT[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"in highp vec4 attr_Vertex;\n"
"in highp vec4 attr_TexCoord;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform highp vec4 u_vertexParm0; // fraction\n"
"uniform highp vec4 u_vertexParm1; // target hue\n"
"\n"
"out highp vec4 var_TexCoord;\n"
"out lowp vec4 var_Color;\n"
"\n"
"// # parameter 0 is the fraction from the current hue to the target hue to map\n"
"// # parameter 1.rgb is the target hue\n"
"// # texture 0 is _currentRender\n"
"\n"
"// # nothing to do but pass the parameters along\n"
"void main(void)\n"
"{\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"\n"
"    var_Color = u_vertexParm1;\n"
"    var_TexCoord.x = attr_TexCoord.x;\n"
"    var_TexCoord.y = 1.0 - attr_TexCoord.y;\n"
"    var_TexCoord.z = u_vertexParm0.x;\n"
"}\n"
;
