
// reflection cubemap(environment)
GLSL_SHADER const char ES3_ENVIRONMENT_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"in vec3 var_TexCoord;\n"
"in lowp vec4 var_Color;\n"
"in vec3 var_normalLocal;\n"
"in vec3 var_toEyeLocal;\n"
"\n"
"uniform samplerCube u_fragmentCubeMap0;\n"
"uniform lowp vec4 u_glColor;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"#if 1\n"
"    // normalize surface normal\n"
"    vec3 normal = normalize(var_normalLocal);\n"
"    // normalize vector to eye\n"
"    vec3 toEye = normalize(var_toEyeLocal);\n"
"\n"
"    // calculate reflection vector\n"
"    float dotEN = dot(toEye, normal);\n"
"    vec3 reflectionVector = vec3(2.0) * normal * vec3(dotEN) - toEye;\n"
"\n"
"    _gl_FragColor = texture(u_fragmentCubeMap0, reflectionVector) * u_glColor * var_Color;\n"
"#else // d3asm\n"
"    _gl_FragColor = texture(u_fragmentCubeMap0, var_TexCoord) * u_glColor * var_Color;\n"
"#endif\n"
"}\n"
;
