
GLSL_SHADER const char ES3_GLOBAL_ILLUMINATION_FRAG[] =
"#version 300 es\n"
"\n"
"//#pragma optimize(off)\n"
"\n"
"//#define _BFG\n"
"//#define BLINN_PHONG\n"
"//#define HALF_LAMBERT\n"
"\n"
"precision highp float;\n"
"\n"
"in vec2 var_TexDiffuse;\n"
"in vec2 var_TexNormal;\n"
"in vec2 var_TexSpecular;\n"
"in lowp vec4 var_Color;\n"
"in vec3 var_L;\n"
"in vec3 var_H;\n"
"#if !defined(_BFG) && !defined(BLINN_PHONG)\n"
"in vec3 var_V;\n"
"#endif\n"
"\n"
"uniform vec4 u_diffuseColor;\n"
"uniform vec4 u_specularColor;\n"
"uniform float u_specularExponent;\n"
"\n"
"uniform sampler2D u_fragmentMap0;    /* u_bumpTexture */\n"
"uniform sampler2D u_fragmentMap1;    /* u_diffuseTexture */\n"
"uniform sampler2D u_fragmentMap2;    /* u_specularTexture */\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"#ifdef _BFG\n"
"    vec4 bumpMap = texture(u_fragmentMap0, var_TexNormal.st);\n"
"    vec3 diffuseMap = texture(u_fragmentMap1, var_TexDiffuse.st).xyz;\n"
"    vec3 specMap = texture(u_fragmentMap2, var_TexSpecular.st).xyz;\n"
"\n"
"    float specularPower = 10.0;\n"
"    vec3 localNormal;\n"
"    localNormal.xy = bumpMap.wy - 0.5;\n"
"    localNormal.z = sqrt(abs(dot(localNormal.xy, localNormal.xy) - 0.25));\n"
"    localNormal = normalize(localNormal);\n"
"    float hDotN = dot(normalize(var_H), localNormal);\n"
"    float specularContribution = pow (abs(hDotN), specularPower);\n"
"\n"
"    vec3 diffuseColor = diffuseMap * (u_diffuseColor.rgb/* * 0.5*/);\n"
"    vec3 specularColor = specMap * specularContribution * u_specularColor.rgb;\n"
"\n"
"    vec3 lightVector = normalize(var_L);\n"
"    float halfLdotN = dot(localNormal, lightVector) * 0.5 + 0.5;\n"
"    halfLdotN *= halfLdotN;\n"
"    float lightColor = u_specularExponent;\n"
#if 0
"    float rim = 1.0 - clamp(hDotN, 0.0, 1.0);\n"
"    float rimPower = 8.0;\n"
"    float rimColor = 0.125 * 1.2 * lightColor * pow(rim, rimPower);\n"
"    vec3 color = (diffuseColor + specularColor) * halfLdotN * lightColor + rimColor;\n"
#endif
"    vec3 color = (diffuseColor + specularColor) * halfLdotN * lightColor;\n"
"    _gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"\n"
"#else\n"
"\n"
"    vec3 L = normalize(var_L);\n"
"    vec3 H = normalize(var_H);\n"
"    vec3 N = 2.0 * texture(u_fragmentMap0, var_TexNormal.st).agb - 1.0;\n"
"    float NdotL = clamp(dot(N, L), 0.0, 1.0);\n"
"\n"
"#ifdef HALF_LAMBERT\n"
"    NdotL *= 0.5;\n"
"    NdotL += 0.5;\n"
"    NdotL = NdotL * NdotL;\n"
"#endif\n"
"    vec3 diffuseColor = texture(u_fragmentMap1, var_TexDiffuse).rgb * u_diffuseColor.rgb;\n"
"    vec3 specularColor = 2.0 * texture(u_fragmentMap2, var_TexSpecular).rgb * u_specularColor.rgb;\n"
"\n"
"#ifdef BLINN_PHONG\n"
"    float NdotH = clamp(dot(N, H), 0.0, 1.0);\n"
"    float specularFalloff = pow(NdotH, 12.0);\n"
"#else\n"
"    vec3 V = normalize(var_V);\n"
"    N = normalize(N);\n"
"    vec3 R = -reflect(L, N);\n"
"    float RdotV = clamp(dot(R, V), 0.0, 1.0);\n"
"    float specularFalloff = pow(RdotV, 3.0);\n"
"#endif\n"
"\n"
"    vec3 color;\n"
"    color = diffuseColor;\n"
"    color += specularFalloff * specularColor;\n"
"    color *= NdotL * u_specularExponent;\n"
"\n"
"    _gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"#endif\n"
"}\n"
;
