
// HeatHaze
GLSL_SHADER const char ES3_HEATHAZE_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_windowCoords;\n"
"in highp vec4 var_TexCoord1;\n"
"in highp vec4 var_TexCoord2;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"// # texture 0 is _currentRender\n"
"// # texture 1 is a normal map that we will use to deform texture 0\n"
"// #\n"
"// # env[0] is the 1.0 to _currentRender conversion\n"
"// # env[1] is the fragment.position to 0.0 - 1.0 conversion\n"
"void main(void)\n"
"{\n"
#if HEATHAZE_BFG // BFG
"    // load the filtered normal map and convert to -1 to 1 range\n"
"    vec4 bumpMap = ( texture( u_fragmentMap1, var_TexCoord1.xy ) * 2.0 ) - 1.0;\n"
"    vec2 localNormal = bumpMap.wy;\n"
"    // calculate the screen texcoord in the 0.0 to 1.0 range\n"
"    vec2 screenTexCoord = (gl_FragCoord.xy ) * u_windowCoords.xy;\n"
"    screenTexCoord += ( localNormal * var_TexCoord2.xy );\n"
"    screenTexCoord = clamp( screenTexCoord, vec2(0.0), vec2(1.0) );\n"
"    screenTexCoord = screenTexCoord * u_nonPowerOfTwo.xy;\n"
"    _gl_FragColor = texture( u_fragmentMap0, screenTexCoord );\n"

#else // 2004

"    vec4 localNormal, R0; // TEMP localNormal, R0;\n"
"\n"
"    vec4 subOne = vec4(-1.0, -1.0, -1.0, -1.0); // PARAM subOne = { -1, -1, -1, -1 };\n"
"    vec4 scaleTwo = vec4(2.0, 2.0, 2.0, 2.0); // PARAM scaleTwo = { 2, 2, 2, 2 };\n"
"\n"
"    //# load the filtered normal map and convert to -1 to 1 range\n"
"    localNormal = texture(u_fragmentMap1, var_TexCoord1.xy); // TEX  localNormal, fragment.texcoord[1], texture[1], 2D;\n"
"    localNormal.x = localNormal.a; // MOV  localNormal.x, localNormal.a;\n"
"    localNormal = (localNormal) * (scaleTwo) + (subOne); // MAD  localNormal, localNormal, scaleTwo, subOne;\n"
"    //localNormal.z = sqrt(max(0.0, 1.0-localNormal.x*localNormal.x-localNormal.y*localNormal.y));\n"
"\n"
"    // # calculate the screen texcoord in the 0.0 to 1.0 range\n"
"    R0 = (gl_FragCoord) * (u_windowCoords); // MUL  R0, fragment.position, program.env[1];\n"
"\n"
"    //localNormal.x /= localNormal.z;\n"
"    //localNormal.y /= localNormal.z;\n"
"\n"
"    // # offset by the scaled localNormal and clamp it to 0.0 - 1.0\n"
"    R0 = clamp((localNormal) * (var_TexCoord2) + (R0), 0.0, 1.0); // MAD_SAT R0, localNormal, fragment.texcoord[2], R0;\n"
"\n"
"    // # scale by the screen non-power-of-two-adjust\n"
"    R0 = (R0) * (u_nonPowerOfTwo); // MUL  R0, R0, program.env[0];\n"
"\n"
"    // # load the screen render\n"
"    _gl_FragColor = texture(u_fragmentMap0, R0.xy); // TEX  result.color.xyz, R0, texture[0], 2D;\n"
#endif
"}\n"
;
