
// interaction(shadow mapping)
GLSL_SHADER const char ES3_INTERACTION_SHADOW_MAPPING_VERT[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision highp float;\n"
"\n"
"//#define BLINN_PHONG\n"
"//#define _PBR\n"
"//#define _AMBIENT\n"
"//#define _POINT_LIGHT\n"
"//#define _SPOT_LIGHT\n"
"//#define _PARALLEL_LIGHT\n"
"//#define PARALLEL_LIGHT_CASCADE_FRUSTUM\n"
"\n"
"out vec2 var_TexDiffuse;\n"
"out vec2 var_TexNormal;\n"
"out vec2 var_TexSpecular;\n"
"out vec4 var_TexLight;\n"
"out lowp vec4 var_Color;\n"
"out vec3 var_L;\n"
"#if defined(BLINN_PHONG) || defined(_PBR) || defined(_AMBIENT)\n"
"out vec3 var_H;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"out vec3 var_V;\n"
"#endif\n"
"#if defined(_PBR)\n"
"out vec3 var_Normal;\n"
"#endif\n"
"\n"
"in vec4 attr_TexCoord;\n"
"in vec3 attr_Tangent;\n"
"in vec3 attr_Bitangent;\n"
"in vec3 attr_Normal;\n"
"in highp vec4 attr_Vertex;\n"
"in lowp vec4 attr_Color;\n"
"\n"
"uniform vec4 u_lightProjectionS;\n"
"uniform vec4 u_lightProjectionT;\n"
"uniform vec4 u_lightFalloff;\n"
"uniform vec4 u_lightProjectionQ;\n"
"uniform lowp float u_colorModulate; // 0 or 1/255\n"
"uniform lowp float u_colorAdd; // 0 or 1\n"
"\n"
"uniform vec4 u_lightOrigin;\n"
"uniform vec4 u_viewOrigin;\n"
"\n"
"uniform vec4 u_bumpMatrixS;\n"
"uniform vec4 u_bumpMatrixT;\n"
"uniform vec4 u_diffuseMatrixS;\n"
"uniform vec4 u_diffuseMatrixT;\n"
"uniform vec4 u_specularMatrixS;\n"
"uniform vec4 u_specularMatrixT;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"#if defined(_AMBIENT)\n"
"out mat3 var_TangentToWorldMatrix;\n"
"#endif\n"
"\n"
"uniform highp mat4 u_modelMatrix;\n"
"uniform highp vec4 globalLightOrigin;\n"
"\n"
"#ifdef _POINT_LIGHT\n"
"out highp vec4 var_VertexPosition;\n"
"out highp vec3 var_VertexToLight;\n"
"#elif defined(_PARALLEL_LIGHT) && defined(PARALLEL_LIGHT_CASCADE_FRUSTUM)\n"
"uniform highp mat4 u_modelViewMatrix;\n"
"out highp vec4 var_ViewPosition;\n"
"out highp vec4 var_VertexPosition;\n"
"#else\n"
"uniform highp mat4 shadowMVPMatrix;\n"
"out highp vec4 var_ShadowCoord;\n"
"#endif\n"
"\n"
"void main(void)\n"
"{\n"
"    mat3 M = mat3(attr_Tangent, attr_Bitangent, attr_Normal);\n"
"\n"
"    var_TexNormal.x = dot(u_bumpMatrixS, attr_TexCoord);\n"
"    var_TexNormal.y = dot(u_bumpMatrixT, attr_TexCoord);\n"
"\n"
"    var_TexDiffuse.x = dot(u_diffuseMatrixS, attr_TexCoord);\n"
"    var_TexDiffuse.y = dot(u_diffuseMatrixT, attr_TexCoord);\n"
"\n"
"    var_TexSpecular.x = dot(u_specularMatrixS, attr_TexCoord);\n"
"    var_TexSpecular.y = dot(u_specularMatrixT, attr_TexCoord);\n"
"\n"
"    var_TexLight.x = dot(u_lightProjectionS, attr_Vertex);\n"
"    var_TexLight.y = dot(u_lightProjectionT, attr_Vertex);\n"
"    var_TexLight.z = dot(u_lightFalloff, attr_Vertex);\n"
"    var_TexLight.w = dot(u_lightProjectionQ, attr_Vertex);\n"
"\n"
"#if defined(_AMBIENT)\n"
"    vec3 L = normalize(vec3(0.0, 0.5, 1.0));\n"
"    var_TangentToWorldMatrix = mat3(u_modelMatrix) * M;\n"
"#else\n"
"    vec3 L = u_lightOrigin.xyz - attr_Vertex.xyz;\n"
"#endif\n"
"    vec3 V = u_viewOrigin.xyz - attr_Vertex.xyz;\n"
"#if defined(BLINN_PHONG) || defined(_PBR) || defined(_AMBIENT)\n"
"    vec3 H = normalize(L) + normalize(V);\n"
"#endif\n"
"\n"
"    var_L = L * M;\n"
"#if defined(BLINN_PHONG) || defined(_PBR) || defined(_AMBIENT)\n"
"    var_H = H * M;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"    var_V = V * M;\n"
"#endif\n"
"#if defined(_PBR)\n"
"    var_Normal = attr_Normal * M;\n"
"#endif\n"
"\n"
"    var_Color = " BYTE_COLOR(attr_Color) " * u_colorModulate + u_colorAdd;\n"
"\n"
"#ifdef _POINT_LIGHT\n"
"    highp vec4 posInLight = u_modelMatrix * attr_Vertex;\n"
"    var_VertexToLight = globalLightOrigin.xyz - posInLight.xyz;\n"
"    var_VertexPosition = attr_Vertex;\n"
"#elif defined(_PARALLEL_LIGHT) && defined(PARALLEL_LIGHT_CASCADE_FRUSTUM)\n"
"    var_ViewPosition = u_modelViewMatrix * attr_Vertex;\n"
"    var_VertexPosition = attr_Vertex;\n"
"#else\n"
"    var_ShadowCoord = attr_Vertex * shadowMVPMatrix;\n"
"#endif\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
