
// interaction
GLSL_SHADER const char ES3_INTERACTION_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision highp float;\n"
"\n"
"//#define BLINN_PHONG\n"
"//#define _PBR\n"
"//#define _AMBIENT\n"
"\n"
"//#define HALF_LAMBERT\n"
"\n"
"in vec2 var_TexDiffuse;\n"
"in vec2 var_TexNormal;\n"
"in vec2 var_TexSpecular;\n"
"in vec4 var_TexLight;\n"
"in lowp vec4 var_Color;\n"
"in vec3 var_L;\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"in vec3 var_H;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"in vec3 var_V;\n"
"#endif\n"
"#if defined(_PBR)\n"
"in vec3 var_Normal;\n"
"#endif\n"
"\n"
"uniform vec4 u_diffuseColor;\n"
"uniform vec4 u_specularColor;\n"
"#if defined(_PBR)\n"
"uniform vec4 u_specularExponent;\n"
"#else\n"
"uniform float u_specularExponent;\n"
"#endif\n"
"\n"
"uniform sampler2D u_fragmentMap0;    /* u_bumpTexture */\n"
"uniform sampler2D u_fragmentMap1;    /* u_lightFalloffTexture */\n"
"uniform sampler2D u_fragmentMap2;    /* u_lightProjectionTexture */\n"
"uniform sampler2D u_fragmentMap3;    /* u_diffuseTexture */\n"
"#if defined(_AMBIENT)\n"
"uniform samplerCube u_fragmentCubeMap4;\n"
"in mat3 var_TangentToWorldMatrix;\n"
"#else\n"
"uniform sampler2D u_fragmentMap4;    /* u_specularTexture */\n"
"uniform sampler2D u_fragmentMap5;    /* u_specularFalloffTexture */\n"
"#endif\n"
"out vec4 _gl_FragColor;\n"
"\n"
"#if defined(_PBR)\n"
_ES3_PBR_GENERAL_FUNCTION
"#endif\n"
"\n"
"void main(void)\n"
"{\n"
"    //float u_specularExponent = 4.0;\n"
"\n"
"    vec3 L = normalize(var_L);\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"    vec3 H = normalize(var_H);\n"
"#endif\n"
"#if defined(BLINN_PHONG) || defined(_AMBIENT)\n"
"    vec3 N = 2.0 * texture(u_fragmentMap0, var_TexNormal.st).agb - 1.0;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"    vec3 V = normalize(var_V);\n"
"    vec3 N = normalize(2.0 * texture(u_fragmentMap0, var_TexNormal.st).agb - 1.0);\n"
"#endif\n"
"\n"
"#if defined(_AMBIENT)\n"
"    vec3 globalNormal = var_TangentToWorldMatrix * N; // transform into ambient map space\n"
"    vec3 ambientValue = texture(u_fragmentCubeMap4, globalNormal).rgb; // load the ambient value\n"
"#endif\n"
"\n"
"    float NdotL = clamp(dot(N, L), 0.0, 1.0);\n"
"#if defined(HALF_LAMBERT)\n"
"    NdotL *= 0.5;\n"
"    NdotL += 0.5;\n"
"    NdotL = NdotL * NdotL;\n"
"#endif\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"    float NdotH = clamp(dot(N, H), 0.0, 1.0);\n"
"#endif\n"
"\n"
"    vec3 lightProjection = textureProj(u_fragmentMap2, var_TexLight.xyw).rgb;\n"
"    vec3 lightFalloff = texture(u_fragmentMap1, vec2(var_TexLight.z, 0.5)).rgb;\n"
"    vec3 diffuseColor = texture(u_fragmentMap3, var_TexDiffuse).rgb * u_diffuseColor.rgb;\n"
"#if defined(_PBR)\n"
"    vec3 AN = normalize(mix(normalize(var_Normal), N, u_specularExponent.y));\n"
"    vec4 Cd = vec4(diffuseColor.rgb, 1.0);\n"
"    vec4 specTex = texture(u_fragmentMap4, var_TexSpecular);\n"
"#ifdef _PBR_RMAO_ONLY\n"
"    vec4 roughness = vec4(specTex.r, specTex.r, specTex.r, specTex.r);\n"
"    vec4 metallic = vec4(specTex.g, specTex.g, specTex.g, specTex.g);\n"
"#else // compat RMAO if u_specularExponent.z == 0 and u_specularExponent.w == 0\n"
"    vec4 roughness = vec4(clamp(specTex.r * (sign(1.0 - abs(sign(u_specularExponent.z))) * 2.0 - 1.0) /* if max == 0, result = 1; else result = -1 */ + u_specularExponent.z, 0.0, 1.0) * max(sign(specTex.r), 0.0) /* if specularTex.r == 0, result = 0, else result = 1 */); // roughness = max - specularTex.r, but if specularTex.r == 0, roughness = 0\n"
"    vec4 metallic = vec4(clamp(specTex.g + u_specularExponent.w, 0.0, 1.0) * max(sign(specTex.g), 0.0) /* if specularTex.g == 0, result = 0, else result = 1 */); // metallic = specularTex.r, but if specularTex.r == 0, metallic = 0\n"
"#endif\n"
"\n"
"    vec4 Cl = vec4(lightProjection * lightFalloff, 1.0);\n"
"    vec3 F0 = vec3(0.04); \n"
"    F0 = mix(F0, Cd.xyz, metallic.xyz);\n"
"\n"
"    // cook-torrance brdf\n"
"    float NDF = DistributionGGX(AN, H, roughness.x);        \n"
"    float G   = GeometrySmith(AN, V, L, roughness.x);      \n"
"    vec3 F    = fresnelSchlick(clamp(dot(H, V), 0.0, 1.0), F0); //max       \n"
"\n"
"    vec3 kS = F;\n"
"    vec3 kD = vec3(1.0) - kS;\n"
"    kD *= 1.0 - metallic.r;\n"
"\n"
"    vec3 numerator    = NDF * G * F;\n"
"    float denominator = 4.0 * max(dot(AN, V), 0.0) * max(dot(AN, L), 0.0);\n"
"    vec3 pbr     = numerator / max(denominator, 0.001);  \n"
"\n"
"#if 1\n"
"    vec4 Lo = (Cd/* * vec4(kD, 1.0)*/ + (u_specularExponent.x * vec4(pbr.rgb, 0.0) * u_specularColor)) * NdotL * Cl;\n"
"    _gl_FragColor = vec4(Lo.rgb, 1.0) * var_Color;\n"
"#else\n"
"    _gl_FragColor = var_Color * Cl * NdotL * Cd + (u_specularExponent.x * vec4(pbr.rgb, 0.0) * (u_specularColor/* * Cl*/));\n"
"#endif\n"
"#elif defined(_AMBIENT)\n"
"    vec3 color = u_specularExponent * /*ambientValue * */diffuseColor * lightProjection * lightFalloff;\n"
"    _gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"#else\n"
"    vec3 specularColor = 2.0 * texture(u_fragmentMap4, var_TexSpecular).rgb * u_specularColor.rgb;\n"
"\n"
"#if defined(BLINN_PHONG)\n"
"    float specularFalloff = pow(NdotH, u_specularExponent);\n"
"#else\n"
"    vec3 R = -reflect(L, N);\n"
"    float RdotV = clamp(dot(R, V), 0.0, 1.0);\n"
"    float specularFalloff = pow(RdotV, u_specularExponent);\n"
"#endif\n"
"\n"
"    vec3 color;\n"
"    color = diffuseColor;\n"
"    color += specularFalloff * specularColor;\n"
"    color *= NdotL * lightProjection;\n"
"    color *= lightFalloff;\n"
"\n"
"    _gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"#endif\n"
"}\n"
;
