
// interaction(shadow mapping)
GLSL_SHADER const char ES3_INTERACTION_SHADOW_MAPPING_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision highp float;\n"
"\n"
"//#define BLINN_PHONG\n"
"//#define _PBR\n"
"//#define _AMBIENT\n"
"//#define _POINT_LIGHT\n"
"//#define _SPOT_LIGHT\n"
"//#define _PARALLEL_LIGHT\n"
"//#define PARALLEL_LIGHT_CASCADE_FRUSTUM\n"
"\n"
"//#define HALF_LAMBERT\n"
"\n"
"in vec2 var_TexDiffuse;\n"
"in vec2 var_TexNormal;\n"
"in vec2 var_TexSpecular;\n"
"in vec4 var_TexLight;\n"
"in lowp vec4 var_Color;\n"
"in vec3 var_L;\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"in vec3 var_H;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"in vec3 var_V;\n"
"#endif\n"
"#if defined(_PBR)\n"
"in vec3 var_Normal;\n"
"#endif\n"
"\n"
"uniform vec4 u_diffuseColor;\n"
"uniform vec4 u_specularColor;\n"
"#if defined(_PBR)\n"
"uniform vec4 u_specularExponent;\n"
"#else\n"
"uniform float u_specularExponent;\n"
"#endif\n"
"\n"
"uniform sampler2D u_fragmentMap0;    /* u_bumpTexture */\n"
"uniform sampler2D u_fragmentMap1;    /* u_lightFalloffTexture */\n"
"uniform sampler2D u_fragmentMap2;    /* u_lightProjectionTexture */\n"
"uniform sampler2D u_fragmentMap3;    /* u_diffuseTexture */\n"
"#if defined(_AMBIENT)\n"
"uniform samplerCube u_fragmentCubeMap4;\n"
"in mat3 var_TangentToWorldMatrix;\n"
"#else\n"
"uniform sampler2D u_fragmentMap4;    /* u_specularTexture */\n"
"uniform sampler2D u_fragmentMap5;    /* u_specularFalloffTexture */\n"
"#endif\n"
"\n"
"uniform highp sampler2DArrayShadow u_fragmentMap6;    /* u_shadowMapTexture */\n"
"uniform sampler2D u_fragmentMap7;    /* u_jitterMapTexture */\n"
"uniform highp vec4 globalLightOrigin;\n"
"uniform mediump float u_uniformParm0; // shadow alpha\n"
"uniform highp vec4 u_uniformParm1; // (shadow map texture size, 1.0 / shadow map texture size, sampler factor, 0)\n"
"uniform highp vec4 u_uniformParm2; // (1.0 / screen width, 1.0 / screen height, jitter texture size, 1.0 / jitter texture size)\n"
"uniform highp float u_uniformParm4; // shadow bias for test\n"
"#define SHADOW_ALPHA u_uniformParm0\n"
"#define SHADOW_MAP_SIZE u_uniformParm1.x\n"
"#define SHADOW_MAP_SIZE_MULTIPLICATOR u_uniformParm1.y\n"
"#define JITTER_SCALE u_uniformParm1.z\n"
"#define SCREEN_SIZE_MULTIPLICATOR u_uniformParm2.xy\n"
"#ifdef _POINT_LIGHT\n"
"in highp vec4 var_VertexPosition;\n"
"uniform highp mat4 shadowMVPMatrix[6];\n"
"in highp vec3 var_VertexToLight;\n"
"#elif defined(_PARALLEL_LIGHT) && defined(PARALLEL_LIGHT_CASCADE_FRUSTUM)\n"
"uniform highp vec4 u_uniformParm3; // Cascade Distances\n"
"uniform highp mat4 shadowMVPMatrix[6];\n"
"in highp vec4 var_ViewPosition;\n"
"in highp vec4 var_VertexPosition;\n"
"#else\n"
"in highp vec4 var_ShadowCoord;\n"
"#endif\n"
"\n"
"#ifdef _DYNAMIC_BIAS\n"
"   #ifdef _PARALLEL_LIGHT\n"
"        #define BIAS_SCALE 0.999991\n"
"    #else\n"
"        #define BIAS_SCALE 0.999\n"
"   #endif\n"
"   #define BIAS(x) ((x) * BIAS_SCALE)\n"
"#elif defined(_FIXED_BIAS)\n"
"    #define BIAS_OFFSET 0.001\n"
"   #define BIAS(x) ((x) - BIAS_OFFSET)\n"
"#else\n"
"   #define BIAS(x) (x)\n"
"#endif\n"
"out vec4 _gl_FragColor;\n"
"\n"
"#if defined(_PBR)\n"
_ES3_PBR_GENERAL_FUNCTION
"#endif\n"
"\n"
"void main(void)\n"
"{\n"
"    //float u_specularExponent = 4.0;\n"
"\n"
"    vec3 L = normalize(var_L);\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"    vec3 H = normalize(var_H);\n"
"#endif\n"
"#if defined(BLINN_PHONG) || defined(_AMBIENT)\n"
"    vec3 N = 2.0 * texture(u_fragmentMap0, var_TexNormal.st).agb - 1.0;\n"
"#endif\n"
"#if (!defined(BLINN_PHONG) && !defined(_AMBIENT)) || defined(_PBR)\n"
"    vec3 V = normalize(var_V);\n"
"    vec3 N = normalize(2.0 * texture(u_fragmentMap0, var_TexNormal.st).agb - 1.0);\n"
"#endif\n"
"\n"
"#if defined(_AMBIENT)\n"
"    vec3 globalNormal = var_TangentToWorldMatrix * N; // transform into ambient map space\n"
"    vec3 ambientValue = texture(u_fragmentCubeMap4, globalNormal).rgb; // load the ambient value\n"
"#endif\n"
"\n"
"    float NdotL = clamp(dot(N, L), 0.0, 1.0);\n"
"#if defined(HALF_LAMBERT)\n"
"    NdotL *= 0.5;\n"
"    NdotL += 0.5;\n"
"    NdotL = NdotL * NdotL;\n"
"#endif\n"
"#if defined(BLINN_PHONG) || defined(_PBR)\n"
"    float NdotH = clamp(dot(N, H), 0.0, 1.0);\n"
"#endif\n"
"\n"
"    vec3 lightProjection = textureProj(u_fragmentMap2, var_TexLight.xyw).rgb;\n"
"    vec3 lightFalloff = texture(u_fragmentMap1, vec2(var_TexLight.z, 0.5)).rgb;\n"
"    vec3 diffuseColor = texture(u_fragmentMap3, var_TexDiffuse).rgb * u_diffuseColor.rgb;\n"
"#if defined(_PBR)\n"
"    vec3 AN = normalize(mix(normalize(var_Normal), N, u_specularExponent.y));\n"
"    vec4 Cd = vec4(diffuseColor.rgb, 1.0);\n"
"    vec4 specTex = texture(u_fragmentMap4, var_TexSpecular);\n"
"#ifdef _PBR_RMAO_ONLY\n"
"    vec4 roughness = vec4(specTex.r, specTex.r, specTex.r, specTex.r);\n"
"    vec4 metallic = vec4(specTex.g, specTex.g, specTex.g, specTex.g);\n"
"#else // compat RMAO if u_specularExponent.z == 0 and u_specularExponent.w == 0\n"
"    vec4 roughness = vec4(clamp(specTex.r * (sign(1.0 - abs(sign(u_specularExponent.z))) * 2.0 - 1.0) /* if max == 0, result = 1; else result = -1 */ + u_specularExponent.z, 0.0, 1.0) * max(sign(specTex.r), 0.0) /* if specularTex.r == 0, result = 0, else result = 1 */); // roughness = max - specularTex.r, but if specularTex.r == 0, roughness = 0\n"
"    vec4 metallic = vec4(clamp(specTex.g + u_specularExponent.w, 0.0, 1.0) * max(sign(specTex.g), 0.0) /* if specularTex.g == 0, result = 0, else result = 1 */); // metallic = specularTex.r, but if specularTex.r == 0, metallic = 0\n"
"#endif\n"
"\n"
"    vec4 Cl = vec4(lightProjection * lightFalloff, 1.0);\n"
"    vec3 F0 = vec3(0.04); \n"
"    F0 = mix(F0, Cd.xyz, metallic.xyz);\n"
"\n"
"    // cook-torrance brdf\n"
"    float NDF = DistributionGGX(AN, H, roughness.x);        \n"
"    float G   = GeometrySmith(AN, V, L, roughness.x);      \n"
"    vec3 F    = fresnelSchlick(clamp(dot(H, V), 0.0, 1.0), F0); //max       \n"
"\n"
"    vec3 kS = F;\n"
"    vec3 kD = vec3(1.0) - kS;\n"
"    kD *= 1.0 - metallic.r;\n"
"\n"
"    vec3 numerator    = NDF * G * F;\n"
"    float denominator = 4.0 * max(dot(AN, V), 0.0) * max(dot(AN, L), 0.0);\n"
"    vec3 pbr     = numerator / max(denominator, 0.001);  \n"
"\n"
"#if 1\n"
"    vec4 color = (Cd/* * vec4(kD, 1.0)*/ + (u_specularExponent.x * vec4(pbr.rgb, 0.0) * u_specularColor)) * NdotL * Cl;\n"
"    color = vec4(color.rgb, 1.0) * var_Color;\n"
"#else\n"
"    vec4 color = var_Color * Cl * NdotL * Cd + (u_specularExponent.x * vec4(pbr.rgb, 0.0) * (u_specularColor/* * Cl*/));\n"
"#endif\n"
"#elif defined(_AMBIENT)\n"
"    vec3 color = u_specularExponent * /*ambientValue * */diffuseColor * lightProjection * lightFalloff;\n"
"#else\n"
"    vec3 specularColor = 2.0 * texture(u_fragmentMap4, var_TexSpecular).rgb * u_specularColor.rgb;\n"
"\n"
"#if defined(BLINN_PHONG)\n"
"    float specularFalloff = pow(NdotH, u_specularExponent);\n"
"#else\n"
"    vec3 R = -reflect(L, N);\n"
"    float RdotV = clamp(dot(R, V), 0.0, 1.0);\n"
"    float specularFalloff = pow(RdotV, u_specularExponent);\n"
"#endif\n"
"#endif\n"
"\n"
ES3_SHADOW_MAPPING_SAMPLE_POISSON_DISK
"    highp float shadow = 0.0;\n"
"#ifdef _POINT_LIGHT\n"
"    int shadowIndex = 0;\n"
"    highp vec3 toLightGlobal = normalize( var_VertexToLight );\n"
"    highp float axis[6] = float[6](\n"
"        -toLightGlobal.x,\n"
"        toLightGlobal.x,\n"
"        -toLightGlobal.y,\n"
"        toLightGlobal.y,\n"
"        -toLightGlobal.z,\n"
"        toLightGlobal.z\n"
"    );\n"
"    for( int i = 0; i < 6; ++i ) {\n"
"        //if( axis[i] > axis[shadowIndex] ) {        shadowIndex = i;    }\n"
"        shadowIndex = axis[i] > axis[shadowIndex] ? i : shadowIndex;\n"
"    }\n"
"    highp vec4 shadowPosition = var_VertexPosition * shadowMVPMatrix[shadowIndex];\n"
"    //vec3 c; if(shadowIndex == 0) c = vec3(1.0, 0.0, 0.0); else if(shadowIndex == 1) c = vec3(1.0, 1.0, 0.0); else if(shadowIndex == 2) c = vec3(0.0, 1.0, 0.0); else if(shadowIndex == 3) c = vec3(0.0, 1.0, 1.0); else if(shadowIndex == 4) c = vec3(0.0, 0.0, 1.0); else c = vec3(1.0, 0.0, 1.0);\n"
"    shadowPosition.xyz /= shadowPosition.w;\n"
"    shadowPosition.w = float(shadowIndex);\n"
"#elif defined(_PARALLEL_LIGHT) && defined(PARALLEL_LIGHT_CASCADE_FRUSTUM)\n"
"    int shadowIndex = 4;\n"
"    highp float viewZ = -var_ViewPosition.z;\n"
"    for( int i = 0; i < 4; ++i ) {\n"
"        shadowIndex = shadowIndex == 4 && viewZ < u_uniformParm3[i] ? i : shadowIndex;\n"
"        //if( viewZ < u_uniformParm3[i] ) {            shadowIndex = i;            break;        }\n"
"    }\n"
"    highp vec4 shadowPosition = var_VertexPosition * shadowMVPMatrix[shadowIndex];\n"
"    shadowPosition.xyz /= shadowPosition.w;\n"
"    shadowPosition.w = float(shadowIndex);\n"
"#else\n"
"    highp vec4 shadowPosition = vec4(var_ShadowCoord.xyz / var_ShadowCoord.w, 0.0);\n"
"#endif\n"
"   // end light type\n"
"    highp float distance = JITTER_SCALE * SHADOW_MAP_SIZE_MULTIPLICATOR;\n"
"    // highp float random = (gl_FragCoord.z + shadowPosition.z) * 0.5;\n"
"    highp float random = texture( u_fragmentMap7, gl_FragCoord.xy * SCREEN_SIZE_MULTIPLICATOR ).r;\n"
"    random *= 3.141592653589793;\n"
"    highp vec2 rot;\n"
"    rot.x = cos( random );\n"
"    rot.y = sin( random );\n"
"    shadowPosition.z = BIAS(shadowPosition.z);\n"
"    for (int i = 0; i < SAMPLES; ++i) {\n"
"        highp vec2 jitter = sampleOffsetTable[i];\n"
"        highp vec2 jitterRotated;\n"
"        jitterRotated.x = jitter.x * rot.x - jitter.y * rot.y;\n"
"        jitterRotated.y = jitter.x * rot.y + jitter.y * rot.x;\n"
"        highp float shadowDepth = texture(u_fragmentMap6, vec4(shadowPosition.st + jitterRotated * distance, shadowPosition.wz));\n"
"        shadow += 1.0 - (1.0 - shadowDepth) * SHADOW_ALPHA;\n"
"        //shadow += shadowDepth > 0.0 ? 1.0 : SHADOW_ALPHA;\n"
"    }\n"
"    const highp float sampleAvg = SAMPLE_MULTIPLICATOR;\n"
"    shadow *= sampleAvg;\n"
"\n"
"#if defined(_PBR)\n"
"    _gl_FragColor = vec4(color.rgb * shadow, color.a);\n"
"#elif defined(_AMBIENT)\n"
"    color *= shadow;\n"
"    _gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"#else\n"
"    vec3 color;\n"
"    color = diffuseColor;\n"
"    color += specularFalloff * specularColor;\n"
"    color *= NdotL * lightProjection;\n"
"    color *= lightFalloff;\n"
"    color *= shadow;\n"
"\n"
"    _gl_FragColor = vec4(color, 1.0) * var_Color;\n"
"#endif\n"
"}\n"
;
