
// megatexture
GLSL_SHADER const char ES3_MEGATEXTURE_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"#define ConvertYCoCgToRGB(x) x.rgb\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"uniform sampler2D u_fragmentMap3;\n"
"uniform sampler2D u_fragmentMap4;\n"
"uniform sampler2D u_fragmentMap5;\n"
"uniform sampler2D u_fragmentMap6;\n"
"uniform sampler2D u_fragmentMap7;\n"
"\n"
"in vec4 var_TexCoord0;\n"
"in vec4 var_TexCoord1;\n"
"in vec4 var_TexCoord2;\n"
"in vec4 var_TexCoord3;\n"
"in vec4 var_TexCoord4;\n"
"in vec4 var_TexCoord5;\n"
"in vec4 var_TexCoord6;\n"
"in vec4 var_TexCoord7;\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec4 mask1, mask2;\n"
"    vec4 invMask1, invMask2;\n"
"    vec4 combined;\n"
"    vec2 scaled;\n"
"    vec4 R2;\n"
"\n"
"    mask1.x = texture(u_fragmentMap0, var_TexCoord0.xy).x;\n"
"    mask1.y = texture(u_fragmentMap0, var_TexCoord1.xy).x;\n"
"    mask1.z = texture(u_fragmentMap0, var_TexCoord2.xy).x;\n"
"    mask1.w = texture(u_fragmentMap0, var_TexCoord3.xy).x;\n"
"\n"
"    mask2.x = texture(u_fragmentMap0, var_TexCoord4.xy).x;\n"
"    mask2.y = texture(u_fragmentMap0, var_TexCoord5.xy).x;\n"
"    mask2.z = texture(u_fragmentMap0, var_TexCoord6.xy).x;\n"
"    mask2.w = 1.0;\n"
"\n"
"    invMask1 = 1.0 - mask1;\n"
"    invMask2 = 1.0 - mask2;\n"
"\n"
"    combined = vec4(0.0);\n"
"    scaled = var_TexCoord7.zw;\n"
"\n"
"    // Sample the lowest quality first.\n"
"    R2 = texture(u_fragmentMap1, scaled.xy);\n"
"    R2.xyz = ConvertYCoCgToRGB(R2);\n"
"    scaled = scaled * 2.0;\n"
"    combined = combined * invMask1.x;\n"
"    combined = (R2 * mask1.x) + combined;\n"
"\n"
"    R2 = texture(u_fragmentMap2, scaled.xy);\n"
"    R2.xyz = ConvertYCoCgToRGB(R2);\n"
"    scaled = scaled * 2.0;\n"
"    combined = combined * invMask1.y;\n"
"    combined = (R2 * mask1.y) + combined;\n"
"\n"
"    R2 = texture(u_fragmentMap3, scaled.xy);\n"
"    R2.xyz = ConvertYCoCgToRGB(R2);\n"
"    scaled = scaled * 2.0;\n"
"    combined = combined * invMask1.z;\n"
"    combined = (R2 * mask1.z) + combined;\n"
"\n"
"    R2 = texture(u_fragmentMap4, scaled.xy);\n"
"    R2.xyz = ConvertYCoCgToRGB(R2);\n"
"    scaled = scaled * 2.0;\n"
"    combined = combined * invMask1.w;\n"
"    combined = (R2 * mask1.w) + combined;\n"
"\n"
"    R2 = texture(u_fragmentMap5, scaled.xy);\n"
"    R2.xyz = ConvertYCoCgToRGB(R2);\n"
"    scaled = scaled * 2.0;\n"
"    combined = combined * invMask2.x;\n"
"    combined = (R2 * mask2.x) + combined;\n"
"\n"
"    R2 = texture(u_fragmentMap6, scaled.xy);\n"
"    R2.xyz = ConvertYCoCgToRGB(R2);\n"
"    scaled = scaled * 2.0;\n"
"    combined = combined * invMask2.y;\n"
"    combined = (R2 * mask2.y) + combined;\n"
"\n"
"    R2 = texture(u_fragmentMap7, scaled.xy);\n"
"    R2.xyz = ConvertYCoCgToRGB(R2);\n"
"    scaled = scaled * 2.0;\n"
"    combined = combined * invMask2.z;\n"
"    combined = (R2 * mask2.z) + combined;\n"
"\n"
"    _gl_FragColor = combined;\n"
"}\n"
;
