
// megatexture
GLSL_SHADER const char ES3_MEGATEXTURE_VERT[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"in highp vec4 attr_Vertex;\n"
"in vec4 attr_TexCoord;\n"
"in lowp vec4 attr_Color;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform vec4 u_megaTextureLevel0;\n"
"uniform vec4 u_megaTextureLevel1;\n"
"uniform vec4 u_megaTextureLevel2;\n"
"uniform vec4 u_megaTextureLevel3;\n"
"uniform vec4 u_megaTextureLevel4;\n"
"uniform vec4 u_megaTextureLevel5;\n"
"uniform vec4 u_megaTextureLevel6;\n"
"uniform vec4 u_megaTextureLevel7;\n"
"uniform vec4 u_megaTextureLevel8;\n"
"\n"
"out vec4 var_TexCoord0;\n"
"out vec4 var_TexCoord1;\n"
"out vec4 var_TexCoord2;\n"
"out vec4 var_TexCoord3;\n"
"out vec4 var_TexCoord4;\n"
"out vec4 var_TexCoord5;\n"
"out vec4 var_TexCoord6;\n"
"out vec4 var_TexCoord7;\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"\n"
"    // Megatexture masks, (texCoord * scale) + offset.\n"
"    var_TexCoord0.xy = ( attr_TexCoord.xy * u_megaTextureLevel0.w ) + u_megaTextureLevel0.xy;\n"
"    var_TexCoord1.xy = ( attr_TexCoord.xy * u_megaTextureLevel1.w ) + u_megaTextureLevel1.xy;\n"
"    var_TexCoord2.xy = ( attr_TexCoord.xy * u_megaTextureLevel2.w ) + u_megaTextureLevel2.xy;\n"
"    var_TexCoord3.xy = ( attr_TexCoord.xy * u_megaTextureLevel3.w ) + u_megaTextureLevel3.xy;\n"
"    var_TexCoord4.xy = ( attr_TexCoord.xy * u_megaTextureLevel4.w ) + u_megaTextureLevel4.xy;\n"
"    var_TexCoord5.xy = ( attr_TexCoord.xy * u_megaTextureLevel5.w ) + u_megaTextureLevel5.xy;\n"
"    var_TexCoord6.xy = ( attr_TexCoord.xy * u_megaTextureLevel6.w ) + u_megaTextureLevel6.xy;\n"
"\n"
"    // Images only have scale.\n"
"    var_TexCoord7.xy = ( attr_TexCoord.xy * u_megaTextureLevel6.w );\n"
"    var_TexCoord7.zw = attr_TexCoord.xy;\n"
"}\n"
;
