
// z-fill
GLSL_SHADER const char ES3_ZFILL_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform lowp vec4 u_glColor;\n"
"#if !defined(NO_ALPHA_TEST)\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform lowp float u_alphaTest;\n"
"\n"
"in vec2 var_TexDiffuse;\n"
"#endif\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"void main(void)\n"
"{\n"
"#if !defined(NO_ALPHA_TEST)\n"
"    if (u_alphaTest > texture(u_fragmentMap0, var_TexDiffuse).a) {\n"
"        discard;\n"
"   }\n"
"#endif\n"
"\n"
"   _gl_FragColor = u_glColor;\n"
"}\n"
;
