#ifndef __AUTO_VERSION_HEADER
#define __AUTO_VERSION_HEADER

// used by the .rc files
#define VERSION_MAJOR_RELEASE			1
#define VERSION_MINOR_RELEASE			4
#define VERSION_INTERNAL_BUILD			2
#define VERSION_BUILD_NUMBER			0

#define VERSION_STRING					"1, 4, 2, 0"
#define VERSION_STRING_DOTTED			"1.4.2"

#endif // __AUTO_VERSION_HEADER
