
// megatexture
GLSL_SHADER const char MEGATEXTURE_VERT[] =
"#version 100\n"
"\n"
"//#pragma optimize(off)\n"
"\n"
"precision highp float;\n"
"\n"
"in highp vec4 attr_Vertex;\n"
"in vec4 attr_TexCoord;\n"
"in lowp vec4 attr_Color;\n"
"\n"
"uniform lowp float u_colorModulate;\n"
"uniform lowp float u_colorAdd;\n"
"\n"
"uniform highp vec4 u_vertexParm0;\n"
"uniform highp vec4 u_vertexParm1;\n"
"uniform highp vec4 u_vertexParm2;\n"
"uniform highp vec4 u_vertexParm3;\n"
"uniform highp vec4 u_vertexParm4;\n"
"uniform highp vec4 u_vertexParm5;\n"
"uniform highp vec4 u_vertexParm6;\n"
"uniform highp vec4 u_vertexParm7;\n"
"uniform highp vec4 u_vertexParm8;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"uniform vec4 u_megaTextureLevel0;\n"
"uniform vec4 u_megaTextureLevel1;\n"
"uniform vec4 u_megaTextureLevel2;\n"
"uniform vec4 u_megaTextureLevel3;\n"
"uniform vec4 u_megaTextureLevel4;\n"
"uniform vec4 u_megaTextureLevel5;\n"
"uniform vec4 u_megaTextureLevel6;\n"
"uniform vec4 u_megaTextureLevel7;\n"
"uniform vec4 u_megaTextureLevel8;\n"
"\n"
"varying vec4 var_TexCoord;\n"
"varying vec4 var_TexCoord0;\n"
"varying vec4 var_TexCoord1;\n"
"varying vec4 var_TexCoord2;\n"
"varying vec4 var_TexCoord3;\n"
"varying vec4 var_TexCoord4;\n"
"varying vec4 var_TexCoord5;\n"
"varying vec4 var_TexCoord6;\n"
"varying vec4 var_TexCoord7;\n"
"\n"
"varying vec4 var_Color;\n"
"\n"
"varying vec2 megaST;\n"
"varying vec4 megaMaskX;\n"
"varying vec4 megaMaskY;\n"
"varying vec4 megaLevelOpacity;\n"
"varying vec4 megaDetailST;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec4 atlasScale = vec4( u_vertexParm1.w, u_vertexParm2.w, u_vertexParm3.w, u_vertexParm4.w );\n"
"    vec4 atlasOffsetX = vec4( u_vertexParm1.x, u_vertexParm2.x, u_vertexParm3.x, u_vertexParm4.x );\n"
"    vec4 atlasOffsetY = vec4( u_vertexParm1.y, u_vertexParm2.y, u_vertexParm3.y, u_vertexParm4.y );\n"
"\n"
"    megaST = attr_TexCoord.xy;\n"
"    megaMaskX = 0.5 - ( megaST.x * atlasScale + atlasOffsetX );\n"
"    megaMaskY = 0.5 - ( megaST.y * atlasScale + atlasOffsetY );\n"
"    megaLevelOpacity = u_vertexParm7;\n"
"    megaDetailST.xy = megaST;\n"
"    megaDetailST.zw = ( megaST - 0.5 ) * u_vertexParm8.x;\n"
"    var_Color = attr_Color * u_colorModulate + u_colorAdd;\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
