include(libraries/curl)
include(libraries/freetype)
include(libraries/jpeg)
include(libraries/ogg)
include(libraries/opus)
include(libraries/openal)
if(NOT DIII4A)
include(libraries/sdl)
endif()
include(libraries/vorbis)
include(libraries/zlib)
