/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_rosuh_libmpg123_MPG123 */

#ifndef _Included_me_rosuh_libmpg123_MPG123
#define _Included_me_rosuh_libmpg123_MPG123
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_rosuh_libmpg123_MPG123_init
  (JNIEnv *, jclass);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    openFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_me_rosuh_libmpg123_MPG123_openFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_me_rosuh_libmpg123_MPG123_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    skipFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_me_rosuh_libmpg123_MPG123_skipFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    seek
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_me_rosuh_libmpg123_MPG123_seek
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    getPosition
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_me_rosuh_libmpg123_MPG123_getPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    getNumChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_me_rosuh_libmpg123_MPG123_getNumChannels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    getRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_me_rosuh_libmpg123_MPG123_getRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    getDuration
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_me_rosuh_libmpg123_MPG123_getDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    openStream
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_me_rosuh_libmpg123_MPG123_openStream
  (JNIEnv *, jclass);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    feed
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_me_rosuh_libmpg123_MPG123_feed
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    readFrame
 * Signature: (J[S)I
 */
JNIEXPORT jshortArray JNICALL Java_com_lizhiweike_audioedit_MPG123_readFrame
        (JNIEnv *, jclass, jlong);

/*
 * Class:     me_rosuh_libmpg123_MPG123
 * Method:    getSeekFrameOffset
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_me_rosuh_libmpg123_MPG123_getSeekFrameOffset
  (JNIEnv *, jclass, jlong, jfloat);

JNIEXPORT jlong JNICALL
Java_me_rosuh_libmpg123_MPG123_getTimeFrame(JNIEnv *env, jclass clazz, jlong handle, jdouble sec);

JNIEXPORT jlong JNICALL
Java_me_rosuh_libmpg123_MPG123_seekFrame(JNIEnv *env, jclass clazz, jlong handle, jfloat offset,
                                         jint mode);

#ifdef __cplusplus
}
#endif
#endif


