
// 2bit retro postprocess
GLSL_SHADER const char ES3_RETRO_2BIT_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"#define RESOLUTION_DIVISOR 4.0\n"
"#define NUM_COLORS 4\n"
"\n"
"uniform sampler2D u_fragmentMap0; // currentRender\n"
"\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_uniformParm0; // rpJitterTexScale\n"
"\n"
"in vec2 var_TexCoord;\n"
"in lowp vec4 var_Color;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"vec3 Average( vec3 pal[NUM_COLORS] )\n"
"{\n"
"    vec3 sum = vec3( 0.0 );\n"
"\n"
"    for( int i = 0; i < NUM_COLORS; i++ )\n"
"    {\n"
"        sum += pal[i];\n"
"    }\n"
"\n"
"    return sum / float( NUM_COLORS );\n"
"}\n"
"\n"
"vec3 Deviation( vec3 pal[NUM_COLORS] )\n"
"{\n"
"    vec3 sum = vec3( 0.0 );\n"
"    vec3 avg = Average( pal );\n"
"\n"
"    for( int i = 0; i < NUM_COLORS; i++ )\n"
"    {\n"
"        sum += abs( pal[i] - avg );\n"
"    }\n"
"\n"
"    return sum / float( NUM_COLORS );\n"
"}\n"
"\n"
"// squared distance to avoid the sqrt of distance function\n"
"float ColorCompare( vec3 a, vec3 b )\n"
"{\n"
"    vec3 diff = b - a;\n"
"    return dot( diff, diff );\n"
"}\n"
"\n"
"// find nearest palette color using Euclidean distance\n"
"vec3 LinearSearch( vec3 c, vec3 pal[NUM_COLORS] )\n"
"{\n"
"    int index = 0;\n"
"    float minDist = ColorCompare( c, pal[0] );\n"
"\n"
"    for( int i = 1; i < NUM_COLORS; i++ )\n"
"    {\n"
"        float dist = ColorCompare( c, pal[i] );\n"
"\n"
"        if( dist < minDist )\n"
"        {\n"
"            minDist = dist;\n"
"            index = i;\n"
"        }\n"
"    }\n"
"\n"
"    return pal[index];\n"
"}\n"
"\n"
_ES3_RETRO_POSTPROCESS_GENERAL_FUNCTION
"\n"
"void main(void)\n"
"{\n"
"    // CGA\n"
"    // https://lospec.com/palette-list/cga-mibend4\n"
"    const vec3 palette[NUM_COLORS] = vec3[NUM_COLORS] (// 4\n"
"        RGB( 41, 31, 35 ),\n"
"        RGB( 189, 80, 47 ),\n"
"        RGB( 52, 209, 175 ),\n"
"        RGB( 247, 236, 185 )\n"
"    );\n"
"\n"
"    vec2 uv = ( var_TexCoord );\n"
"    vec2 uvPixelated = floor( gl_FragCoord.xy / RESOLUTION_DIVISOR ) * RESOLUTION_DIVISOR;\n"
"\n"
"    vec3 quantizationPeriod = vec3( 1.0 / float(NUM_COLORS) );\n"
"    vec3 quantDeviation = Deviation( palette );\n"
"\n"
"    // get pixellated base color\n"
"    vec3 color = texture( u_fragmentMap0, uvPixelated * u_windowCoords.xy * u_nonPowerOfTwo.xy ).rgb;\n"
"\n"
"    vec2 uvDither = uvPixelated;\n"
"    //if( u_uniformParm0.x > 1.0 )\n"
"    {\n"
"        uvDither = gl_FragCoord.xy / ( RESOLUTION_DIVISOR / u_uniformParm0.x );\n"
"    }\n"
"    float dither = DitherArray8x8( uvDither ) - 0.5;\n"
"\n"
"    color.rgb += vec3( dither, dither, dither ) * quantDeviation * u_uniformParm0.y;\n"
"\n"
"    // find closest color match from C64 color palette\n"
"    color = LinearSearch( color.rgb, palette );\n"
"\n"
"    _gl_FragColor = vec4( color, 1.0 );\n"
"}\n"
;
