
// cpc retro postprocess
GLSL_SHADER const char ES3_RETRO_CPC_FRAG[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"#define RESOLUTION_DIVISOR 4.0\n"
"#define NUM_COLORS 31 // original 27\n"
"\n"
"uniform sampler2D u_fragmentMap0; // currentRendert\n"
"\n"
"uniform highp vec4 u_windowCoords;\n"
"uniform highp vec4 u_nonPowerOfTwo;\n"
"uniform highp vec4 u_uniformParm0; // rpJitterTexScale\n"
"\n"
"in vec2 var_TexCoord;\n"
"in lowp vec4 var_Color;\n"
"out vec4 _gl_FragColor;\n"
"\n"
"\n"
"vec3 Average( vec3 pal[NUM_COLORS] )\n"
"{\n"
"    vec3 sum = vec3( 0.0 );\n"
"\n"
"    for( int i = 0; i < NUM_COLORS; i++ )\n"
"    {\n"
"        sum += pal[i];\n"
"    }\n"
"\n"
"    return sum / float( NUM_COLORS );\n"
"}\n"
"\n"
"vec3 Deviation( vec3 pal[NUM_COLORS] )\n"
"{\n"
"    vec3 sum = vec3( 0.0 );\n"
"    vec3 avg = Average( pal );\n"
"\n"
"    for( int i = 0; i < NUM_COLORS; i++ )\n"
"    {\n"
"        sum += abs( pal[i] - avg );\n"
"    }\n"
"\n"
"    return sum / float( NUM_COLORS );\n"
"}\n"
"\n"
"// squared distance to avoid the sqrt of distance function\n"
"float ColorCompare( vec3 a, vec3 b )\n"
"{\n"
"    vec3 diff = b - a;\n"
"    return dot( diff, diff );\n"
"}\n"
"\n"
"// find nearest palette color using Euclidean distance\n"
"vec3 LinearSearch( vec3 c, vec3 pal[NUM_COLORS] )\n"
"{\n"
"    int index = 0;\n"
"    float minDist = ColorCompare( c, pal[0] );\n"
"\n"
"    for( int i = 1; i < NUM_COLORS; i++ )\n"
"    {\n"
"        float dist = ColorCompare( c, pal[i] );\n"
"\n"
"        if( dist < minDist )\n"
"        {\n"
"            minDist = dist;\n"
"            index = i;\n"
"        }\n"
"    }\n"
"\n"
"    return pal[index];\n"
"}\n"
"\n"
_ES3_RETRO_POSTPROCESS_GENERAL_FUNCTION
"\n"
"void main(void)\n"
"{\n"
"    // https://lospec.com/palette-list/ruzzi-cpc\n"
"    const vec3 palette[NUM_COLORS] = vec3[NUM_COLORS]( // 31\n"
"        RGB( 0, 0, 28 ), // dark blue\n"
"        RGB( 28, 0, 28 ), // dark magenta\n"
"        RGB( 33, 30, 32 ),\n"
"        RGB( 85, 85, 104 ),\n"
"\n"
"        RGB( 36, 14, 11 ),\n"
"        RGB( 26, 34, 114 ),\n"
"        RGB( 68, 118, 16 ),\n"
"        RGB( 129, 16, 51 ),\n"
"        RGB( 50, 131, 113 ),\n"
"        RGB( 124, 36, 136 ),\n"
"        RGB( 151, 122, 44 ),\n"
"        RGB( 16, 55, 218 ),\n"
"        RGB( 143, 136, 132 ),\n"
"        RGB( 222, 18, 92 ),\n"
"        RGB( 100, 222, 21 ),\n"
"        RGB( 32, 144, 210 ),\n"
"        RGB( 120, 58, 220 ),\n"
"        RGB( 74, 228, 112 ),\n"
"        RGB( 223, 39, 158 ),\n"
"        RGB( 236, 126, 74 ),\n"
"        RGB( 174, 228, 38 ),\n"
"        RGB( 136, 151, 219 ),\n"
"        RGB( 49, 234, 203 ),\n"
"        RGB( 163, 236, 128 ),\n"
"        RGB( 238, 142, 151 ),\n"
"        RGB( 224, 60, 223 ),\n"
"        RGB( 249, 234, 56 ),\n"
"        RGB( 152, 244, 218 ),\n"
"        RGB( 239, 157, 228 ),\n"
"        RGB( 252, 244, 144 ),\n"
"        RGB( 255, 255, 233 )\n"
"    );\n"
"\n"
"    const vec3 medianAbsoluteDeviation = RGB( 175, 6, 56 );\n"
"    const vec3 deviation = RGB( 67, 70, 62 );\n"
"    \n"
"    vec2 uv = ( var_TexCoord );\n"
"    vec2 uvPixelated = floor( gl_FragCoord.xy / RESOLUTION_DIVISOR ) * RESOLUTION_DIVISOR;\n"
"\n"
"    vec3 quantizationPeriod = vec3( 1.0 / float(NUM_COLORS) );\n"
"    vec3 quantDeviation = Deviation( palette );\n"
"\n"
"    // get pixellated base color\n"
"    vec3 color = texture( u_fragmentMap0, uvPixelated * u_windowCoords.xy * u_nonPowerOfTwo.xy ).rgb;\n"
"\n"
"    vec2 uvDither = uvPixelated;\n"
"    //if( u_uniformParm0.x > 1.0 )\n"
"    {\n"
"        uvDither = gl_FragCoord.xy / ( RESOLUTION_DIVISOR / u_uniformParm0.x );\n"
"    }\n"
"    float dither = DitherArray8x8( uvDither ) - 0.5;\n"
"\n"
"    //color.rgb += vec3( dither, dither, dither ) * quantizationPeriod;\n"
"    color += vec3( dither, dither, dither ) * quantDeviation * u_uniformParm0.y;\n"
"\n"
"    // find closest color match from CPC color palette\n"
"    color = LinearSearch( color, palette );\n"
"\n"
"    //color = texture( u_fragmentMap0, uv ).rgb;\n"
"    _gl_FragColor = vec4( color, 1.0 );\n"
"}\n"
;
