//DEFINE_SPECIAL(name,num,args)

DEFINE_SPECIAL(Door_Open, 1, 5)
DEFINE_SPECIAL(Pushwall_Move, 2, 4)
DEFINE_SPECIAL(Exit_Normal, 3, 1)
DEFINE_SPECIAL(Exit_Secret, 4, 1)
DEFINE_SPECIAL(Teleport_NewMap, 5, 3)
DEFINE_SPECIAL(Exit_VictorySpin, 6, 0)
DEFINE_SPECIAL(Exit_Victory, 7, 1)
DEFINE_SPECIAL(Trigger_Execute, 8, 3)
DEFINE_SPECIAL(StartConversation, 9, 2)
DEFINE_SPECIAL(Door_Elevator, 10, 5)
DEFINE_SPECIAL(Elevator_SwitchFloor, 11, 3)
DEFINE_SPECIAL(Pushwall_MoveNoStop, 12, 4)
DEFINE_SPECIAL(Teleport_Relative, 13, 3)
