/* Copyright (c) 2002-2012 Croteam Ltd. 
This program is free software; you can redistribute it and/or modify
it under the terms of version 2 of the GNU General Public License as published by
the Free Software Foundation


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */

// Animation names
#define MAMUT_ANIM_DEFAULT_ANIMATION 0
#define MAMUT_ANIM_ATTACK01 1
#define MAMUT_ANIM_DEATH 2
#define MAMUT_ANIM_RUN 3
#define MAMUT_ANIM_STAND 4
#define MAMUT_ANIM_WALK 5
#define MAMUT_ANIM_WOUND01 6
#define MAMUT_ANIM_WOUND02 7

// Color names

// Patch names

// Names of collision boxes
#define MAMUT_COLLISION_BOX_DEFAULT 0
#define MAMUT_COLLISION_BOX_DEATH  1

// Attaching position names
#define MAMUT_ATTACHMENT_MAN_FRONT 0
#define MAMUT_ATTACHMENT_MAN_MIDDLE 1
#define MAMUT_ATTACHMENT_MAN_REAR 2

// Sound names
