
// megatexture
GLSL_SHADER const char ES3_MEGATEXTURE_FRAG[] =
"#version 300 es\n"
"\n"
"//#pragma optimize(off)\n"
"\n"
"precision highp float;\n"
"\n"
"#define ConvertYCoCgToRGB(x) x.rgb\n"
"\n"
"uniform sampler2D u_fragmentMap0;\n"
"uniform sampler2D u_fragmentMap1;\n"
"uniform sampler2D u_fragmentMap2;\n"
"uniform sampler2D u_fragmentMap3;\n"
"uniform sampler2D u_fragmentMap4;\n"
"uniform sampler2D u_fragmentMap5;\n"
"uniform sampler2D u_fragmentMap6;\n"
"uniform sampler2D u_fragmentMap7;\n"
"\n"
"in vec4 var_TexCoord;\n"
"in vec4 var_TexCoord0;\n"
"in vec4 var_TexCoord1;\n"
"in vec4 var_TexCoord2;\n"
"in vec4 var_TexCoord3;\n"
"in vec4 var_TexCoord4;\n"
"in vec4 var_TexCoord5;\n"
"in vec4 var_TexCoord6;\n"
"in vec4 var_TexCoord7;\n"
"\n"
"in vec2 megaST;\n"
"in vec4 megaMaskX;\n"
"in vec4 megaMaskY;\n"
"in vec4 megaLevelOpacity;\n"
"in vec4 megaDetailST;\n"
"\n"
"out vec4 _gl_FragColor;\n"
"\n"
"vec2 decodeMegaNormalXY( float alpha ) {\n"
"    float packed_ = floor( alpha * 255.0 + 0.5 );\n"
"    float packedX = mod( packed_, 16.0 );\n"
"    float packedY = floor( packed_ / 16.0 );\n"
"    return vec2( ( packedX - 8.0 ) / ( packedX < 8.0 ? 8.0 : 7.0 ),\n"
"    ( packedY - 8.0 ) / ( packedY < 8.0 ? 8.0 : 7.0 ) );\n"
"}\n"
"\n"
"void main(void)\n"
"{\n"
"    vec4 levelMask = clamp( 16.0 - 32.0 * max( abs( megaMaskX ), abs( megaMaskY ) ), 0.0, 1.0 );\n"
"    levelMask *= megaLevelOpacity;\n"
"    vec4 level1 = texture( u_fragmentMap1, megaST );\n"
"    vec4 level2 = texture( u_fragmentMap2, megaST * 2.0 );\n"
"    vec4 level3 = texture( u_fragmentMap3, megaST * 4.0 );\n"
"    vec4 level4 = texture( u_fragmentMap4, megaST * 8.0 );\n"
"    vec4 level5 = texture( u_fragmentMap5, megaST * 16.0 );\n"
"    vec3 combinedColor = level1.rgb;\n"
"    combinedColor = mix( combinedColor, level2.rgb, levelMask.x );\n"
"    combinedColor = mix( combinedColor, level3.rgb, levelMask.y );\n"
"    combinedColor = mix( combinedColor, level4.rgb, levelMask.z );\n"
"    combinedColor = mix( combinedColor, level5.rgb, levelMask.w );\n"
"    // Terrain vertex colors are authoring layer weights. The compiler has\n"
"    // already resolved those weights and the optional atmosphere bake into the\n"
"    // streamed MegaTexture. They must not tint the final image.\n"
"    _gl_FragColor = level1;\n"
"}\n"
;
