
// environSuit
GLSL_SHADER const char ES3_ENVIROSUIT_VERT[] =
"#version 300 es\n"
"//#pragma optimize(off)\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform highp mat4 u_modelViewProjectionMatrix;\n"
"\n"
"uniform highp vec4 u_vertexParm0; // local[0]    scroll\n"
"uniform highp vec4 u_vertexParm1; // local[1]    deform magnitude (1.0 is reasonable, 2.0 is twice as wavy, 0.5 is half as wavy, etc)\n"
"\n"
"in vec4 attr_TexCoord;\n"
"in highp vec4 attr_Vertex;\n"
"\n"
"out vec2 var_TexCoord0; // texCoord[1] is the model surface texture coords\n"
"// out vec4 var_TexCoord1; // texCoord[2] is the copied deform magnitude\n"
"out vec4 var_Color;\n"
"\n"
"void main(void)\n"
"{\n"
"    // texture 1 takes the texture coordinates and adds a scroll\n"
"    var_TexCoord0 = attr_TexCoord.xy;\n"
"    // var_TexCoord1 = attr_TexCoord + u_vertrxParm0;\n"
"\n"
"    // magnitude of scale\n"
"    var_Color = u_vertexParm1;\n"
"\n"
"    gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
"}\n"
;
